(function () {
  var f = window.pofrazeFilm;
  window.POFRAZE_FILMS = window.POFRAZE_FILMS.concat([
    f("casablanca", "Касабланка", "Casablanca", 1942, "фильм", ["romance", "war", "slow"], ["here's looking at you kid", "play it sam", "we'll always have paris", "of all the gin joints", "луис это начало прекрасной дружбы"], "Касабланка"),
    f("psycho", "Психо", "Psycho", 1960, "фильм", ["horror", "slow", "dark"], ["душа не моется", "мотель бейтса", "shower scene", "мать", "norman bates"], "Психо"),
    f("2001", "Космическая одиссея 2001", "2001: A Space Odyssey", 1968, "фильм", ["space", "slow", "mind-power"], ["open the pod bay doors hal", "i'm sorry dave", "монолит", "hal 9000", "к кубрику"], "Космическая одиссея 2001"),
    f("clockwork", "Заводной апельсин", "A Clockwork Orange", 1971, "фильм", ["dark", "chaotic", "mind-power"], ["ultra violence", "ludovico", "alex delarge", "moloko", "i was cured all right"], "Заводной апельсин"),
    f("apocalypse", "Апокалипсис сегодня", "Apocalypse Now", 1979, "фильм", ["war", "dark", "slow"], ["i love the smell of napalm", "the horror", "kurtz", "never get out of the boat", " charlie don't surf"], "Апокалипсис сегодня"),
    f("full-metal", "Цельнометаллическая оболочка", "Full Metal Jacket", 1987, "фильм", ["war", "dark", "irony"], ["how i love the smell", "born to kill", "private joker", "this is my rifle", "merry christmas"], "Цельнометаллическая оболочка"),
    f("saving-ryan", "Спасти рядового Райана", "Saving Private Ryan", 1998, "фильм", ["war", "family", "dark"], ["earn this", "james ryan", "омаха", "капитан миллер", "братья райан"], "Спасти рядового Райана"),
    f("schindler", "Список Шиндлера", "Schindler's List", 1993, "фильм", ["war", "family", "slow"], ["whoever saves one life", "oshner", "power is when we have every justification to kill", "имя в списке"], "Список Шиндлера"),
    f("braveheart", "Храброе сердце", "Braveheart", 1995, "фильм", ["war", "family", "ambition"], ["they may take our lives", "freedom", "william wallace", "свобода", "шотландия"], "Храброе сердце"),
    f("private-ryan-wait", "Тонкая красная линия", "The Thin Red Line", 1998, "фильм", ["war", "slow", "dark"], ["what's this war in the heart of nature", "гвадалканал", " whiteness"], "Тонкая красная линия"),
    f("heat", "Схватка", "Heat", 1995, "фильм", ["crime", "slick-urban", "tempo"], ["don't let yourself get attached", "i'm never going back", "neil mcCauley", "vincent hanna", "кофе"], "Схватка"),
    f("departed", "Отступники", "The Departed", 2006, "фильм", ["crime", "slick-urban", "tempo"], ["i want my people on the inside", "costello", "крыса", "бостон", "who's the rat"], "Отступники"),
    f("no-country", "Старикам тут не место", "No Country for Old Men", 2007, "фильм", ["crime", "slow", "dark"], ["what's the most you ever lost on a coin toss", "anton chigurh", "монетка", "call it"], "Старикам тут не место"),
    f("there-will", "Нефть", "There Will Be Blood", 2007, "фильм", ["ambition", "dark", "slow"], ["i drink your milkshake", "daniel plainview", "i am a family man", "молочный коктейль"], "Нефть There Will Be Blood"),
    f("fargo-film", "Фарго", "Fargo", 1996, "фильм", ["crime", "irony", "slow"], ["oh yah", "wood chipper", "minnesota", "jerry lundegaard"], "Фарго фильм"),
    f("big-lebowski", "Большой Лебовски", "The Big Lebowski", 1998, "фильм", ["comedy", "irony", "chaotic"], ["the dude abides", "this aggression will not stand", "ковёр", "dude"], "Большой Лебовски"),
    f("no-country2", "Старикам тут не место", "No Country for Old Men", 2007, "фильм", ["crime", "slow", "dark"], ["call it"], "skip-dup"),
    f("oceans11", "Одиннадцать друзей Оушена", "Ocean's Eleven", 2001, "фильм", ["heist", "slick-urban", "comedy"], ["rusty", "danny ocean", "vegas", "we have people"], "Одиннадцать друзей Оушена"),
    f("catch-me", "Поймай меня, если сможешь", "Catch Me If You Can", 2002, "фильм", ["heist", "tempo", "comedy"], ["frank abagnale", "fbi", "чеки", "пилот"], "Поймай меня если сможешь"),
    f("gone-girl", "Исчезнувшая", "Gone Girl", 2014, "фильм", ["dark", "mind-power", "slow"], ["cool girl", "nick dunne", "дневник", "я хорошая жена"], "Исчезнувшая"),
    f("zodiac", "Зодиак", "Zodiac", 2007, "фильм", ["crime", "slow", "dark"], ["this is the zodiac speaking", "сан франциско", "шифр", "газеты"], "Зодиак"),
    f("prisoners", "Пленницы", "Prisoners", 2013, "фильм", ["crime", "dark", "slow"], ["where is she", "hugh jackman", "подвал", "дождь"], "Пленницы"),
    f("sicario", "Сикарио", "Sicario", 2015, "фильм", ["crime", "dark", "slow"], ["you are not a wolf", "cartel", "alejandro", "граница"], "Сикарио"),
    f("nightcrawler", "Стрингер", "Nightcrawler", 2014, "фильм", ["dark", "ambition", "slick-urban"], ["if it bleeds it leads", "lou bloom", "новости", "los angeles"], "Стрингер Nightcrawler"),
    f("whiplash-already", "Одержимость", "Whiplash", 2014, "фильм", ["ambition", "dark", "tempo"], ["not my tempo"], "skip"),
    f("ex-machina", "Из машины", "Ex Machina", 2014, "фильм", ["mind-power", "slow", "dark"], ["ava", "turing test", "covenant", "искусственный интеллект"], "Из машины"),
    f("her", "Она", "Her", 2013, "фильм", ["romance", "slick-urban", "slow"], ["os1", "samantha", "я влюблён в операционную систему", "theodore"], "Она Her"),
    f("blade-old", "Бегущий по лезвию", "Blade Runner", 1982, "фильм", ["slow", "dark", "slick-urban"], ["tears in rain", "like tears in rain", "replicant", "deckard", "время умирать"], "Бегущий по лезвию"),
    f("alien-romulus", "Чужой: Ромул", "Alien: Romulus", 2024, "фильм", ["horror", "space", "tempo"], ["in space no one can hear", "facehugger", "колония"], "Чужой Ромул"),
    f("top-gun", "Топ Ган", "Top Gun", 1986, "фильм", ["tempo", "ambition", "romance"], ["i feel the need", "the need for speed", "maverick", "goose", "highway to the danger zone"], "Топ Ган"),
    f("top-gun-2", "Топ Ган: Мэверик", "Top Gun: Maverick", 2022, "фильм", ["tempo", "family", "ambition"], ["talk to me goose", "don't think just do", "maverick", "ростер"], "Топ Ган Мэверик"),
    f("mi-fallout", "Миссия невыполнима: Последствия", "Mission: Impossible – Fallout", 2018, "фильм", ["tempo", "heist", "ambition"], ["your mission should you choose", "ethan hunt", "this is not a drill"], "Миссия невыполнима Последствия"),
    f("john-wick-4", "Джон Уик 4", "John Wick: Chapter 4", 2023, "фильм", ["tempo", "crime", "dark"], ["baba yaga", "continental", "anyone who meets you dies", "пин"], "Джон Уик 4"),
    f("mad-max-2", "Безумный Макс 2", "Mad Max 2", 1981, "фильм", ["tempo", "war", "chaotic"], ["two days ago i saw a vehicle", "was teland", "gasoline"], "Безумный Макс 2"),
    f("knives-out", "Достать ножи", "Knives Out", 2019, "фильм", ["comedy", "crime", "irony"], ["blanc", "i suspect foul play", "пончик", "завещание"], "Достать ножи"),
    f("glass-onion", "Достать ножи: Стеклянная луковица", "Glass Onion", 2022, "фильм", ["comedy", "crime", "irony"], ["disruptor", "island", "blanc", "головоломка"], "Стеклянная луковица"),
    f("everything", "Всё везде и сразу", "Everything Everywhere All at Once", 2022, "фильм", ["chaotic", "family", "mind-power"], ["hot dog fingers", "multiverse", "bagel", "googly eyes", "во всём сразу"], "Всё везде и сразу"),
    f("eeaaowait", "Дюна: Часть вторая", "Dune: Part Two", 2024, "фильм", ["space", "war", "slow"], ["power over spice", "lisan al gaib", "песчаный червь", "я пустынная мышь"], "Дюна часть вторая"),
    f("oppen-already", "Оппенгеймер", "Oppenheimer", 2023, "фильм", ["mind-power", "slow", "war"], ["now i am become death"], "skip"),
    f("barbie-already", "Барби", "Barbie", 2023, "фильм", ["comedy", "irony", "romance"], ["i'm just ken"], "skip"),
    f("spiderman-into", "Человек-паук: Через вселенные", "Spider-Man: Into the Spider-Verse", 2018, "фильм", ["kids", "tempo", "family"], ["anyone can wear the mask", "miles morales", "leap of faith", "what's up danger"], "Человек-паук Через вселенные"),
    f("spiderman-across", "Человек-паук: Паутина вселенных", "Spider-Man: Across the Spider-Verse", 2023, "фильм", ["kids", "tempo", "family"], ["canon event", "gwen", "spot", "miles"], "Человек-паук Паутина вселенных"),
    f("kungfu-panda", "Кунг-фу Панда", "Kung Fu Panda", 2008, "фильм", ["kids", "comedy", "fantasy"], ["skadoosh", "there is no secret ingredient", "po", "драконий воин"], "Кунг-фу Панда"),
    f("zootopia", "Зверополис", "Zootopia", 2016, "фильм", ["kids", "comedy", "crime"], ["try everything", "judy hopps", "nick wilde", "у нас лапки"], "Зверополис"),
    f("encanto", "Энканто", "Encanto", 2021, "фильм", ["kids", "family", "fantasy"], ["we don't talk about bruno", "bruno", "casita", "дар"], "Энканто"),
    f("soul", "Душа", "Soul", 2020, "фильм", ["kids", "mind-power", "comedy"], ["spark", "joe gardner", "jazz", "великое после"], "Душа Pixar"),
    f("coco-already", "Тайна Коко", "Coco", 2017, "фильм", ["kids", "family", "fantasy"], ["remember me"], "skip"),
    f("ratatouille", "Рататуй", "Ratatouille", 2007, "фильм", ["kids", "comedy", "ambition"], ["anyone can cook", "remy", "gusteau", "anyone can cook"], "Рататуй"),
    f("incredibles", "Суперсемейка", "The Incredibles", 2004, "фильм", ["kids", "tempo", "family"], ["no capes", "i'm not happy bob", "dash", "elastigirl"], "Суперсемейка"),
    f("finding-dory", "В поисках Дори", "Finding Dory", 2016, "фильм", ["kids", "family", "comedy"], ["just keep swimming", "i suffer from short term memory loss", "дори"], "В поисках Дори"),
    f("up-already", "Вверх", "Up", 2009, "фильм", ["kids", "family", "romance"], ["adventure is out there"], "skip"),
    f("wall-e-already", "ВАЛЛ-И", "WALL·E", 2008, "фильм", ["kids", "space", "romance"], ["eve"], "skip"),
    f("a-star", "Звезда родилась", "A Star Is Born", 2018, "фильм", ["romance", "ambition", "dark"], ["maybe it's time", "shallow", "ally", "jackson maine"], "Звезда родилась"),
    f("bohemian", "Богемская рапсодия", "Bohemian Rhapsody", 2018, "фильм", ["ambition", "family", "tempo"], ["we are the champions", "freddie", "live aid", "queen"], "Богемская рапсодия"),
    f("social-already", "Социальная сеть", "The Social Network", 2010, "фильм", ["ambition", "slick-urban", "mind-power"], ["drop out"], "skip"),
    f("big-short", "Игра на понижение", "The Big Short", 2015, "фильм", ["ambition", "irony", "mind-power"], ["the bubble", "subprime", "марго робби в ванне объясняет"], "Игра на понижение"),
    f("moneyball", "Человек, который изменил всё", "Moneyball", 2011, "фильм", ["sport", "mind-power", "ambition"], ["how can you not be romantic about baseball", "brad pitt", "статистика"], "Moneyball"),
    f("imitation", "Игра в имитацию", "The Imitation Game", 2014, "фильм", ["mind-power", "war", "slow"], ["are you paying attention", "turing", "enigma", "sometimes it is the people"], "Игра в имитацию"),
    f("theory-everything", "Вселенная Стивена Хокинга", "The Theory of Everything", 2014, "фильм", ["romance", "slow", "mind-power"], ["there should be no boundaries", "hawking", "чёрные дыры"], "Вселенная Стивена Хокинга"),
    f("revenant", "Выживший", "The Revenant", 2015, "фильм", ["slow", "dark", "war"], ["as long as you can still grab a breath", "glass", "медведь", "revenger"], "Выживший"),
    f("birdman", "Бёрдмэн", "Birdman", 2014, "фильм", ["ambition", "chaotic", "slick-urban"], ["you are a movie star", "broadway", "riggan"], "Бёрдмэн"),
    f("spotlight", "В центре внимания", "Spotlight", 2015, "фильм", ["slow", "crime", "mind-power"], ["we got them", "boston globe", "церковь", "расследование"], "В центре внимания"),
    f("moonlight", "Лунный свет", "Moonlight", 2016, "фильм", ["slow", "family", "romance"], ["who is you", "little", "black", "chiron"], "Лунный свет"),
    f("shape-water", "Форма воды", "The Shape of Water", 2017, "фильм", ["romance", "fantasy", "slow"], ["unable to perceive", "amphibian man", "эльза"], "Форма воды"),
    f("pan", "Лабиринт Фавна", "Pan's Labyrinth", 2006, "фильм", ["fantasy", "war", "dark"], ["ofelia", "фавн", "лабиринт", "послушная девочка"], "Лабиринт Фавна"),
    f("oldboy-already", "Олдбой", "Oldboy", 2003, "фильм", ["dark", "crime", "chaotic"], ["laugh and the world laughs with you"], "skip"),
    f("parasite-already", "Паразиты", "Parasite", 2019, "фильм", ["dark", "crime", "slow"], ["jessica only child of a chicago"], "skip"),
    f("memories", "Воспоминания об убийстве", "Memories of Murder", 2003, "фильм", ["crime", "slow", "dark"], ["дождь", "серийный", "корея 80-е"], "Воспоминания об убийстве"),
    f("old-boy-wait", "Олдбой", "Oldboy", 2003, "фильм", ["dark", "crime", "chaotic"], ["15 years"], "skip"),
    f("chungking", "Чунцинский экспресс", "Chungking Express", 1994, "фильм", ["romance", "slick-urban", "slow"], ["expiry date", "ананас", "гонконг"], "Чунцинский экспресс"),
    f("in-mood", "Любовное настроение", "In the Mood for Love", 2000, "фильм", ["romance", "slow", "slick-urban"], ["he remembers those vanished years", "chow", "коридор"], "Любовное настроение"),
    f("hero-yimou", "Герой", "Hero", 2002, "фильм", ["war", "slow", "fantasy"], ["цвет", "без имени", "китай"], "Герой Чжан Имоу"),
    f("crouching", "Крадущийся тигр, затаившийся дракон", "Crouching Tiger, Hidden Dragon", 2000, "фильм", ["fantasy", "romance", "tempo"], ["green destiny", "крыша", "меч"], "Крадущийся тигр"),
    f("3idiots", "3 идиота", "3 Idiots", 2009, "фильм", ["comedy", "ambition", "family"], ["all is well", "ранчо", "инженерка", "aal izz well"], "3 идиота"),
    f("slumdog", "Миллионер из трущоб", "Slumdog Millionaire", 2008, "фильм", ["romance", "ambition", "tempo"], ["it is written", "who wants to be a millionaire", "джамал"], "Миллионер из трущоб"),
    f("amalie-already", "Амели", "Amélie", 2001, "фильм", ["romance", "comedy", "slick-urban"], ["garden gnome"], "skip"),
    f("intouch-already", "1+1", "Intouchables", 2011, "фильм", ["comedy", "family", "romance"], ["earth wind and fire"], "skip"),
    f("life-is-already", "Жизнь прекрасна", "Life Is Beautiful", 1997, "фильм", ["family", "war", "irony"], ["buongiorno principessa"], "skip"),
    f("amelie-more", "Амели", "Amélie", 2001, "фильм", ["romance", "comedy", "slick-urban"], ["skip"], "skip"),
    f("notebook", "Дневник памяти", "The Notebook", 2004, "фильм", ["romance", "family", "slow"], ["if you're a bird i'm a bird", "noah", "allison", "дождь"], "Дневник памяти"),
    f("titanic-already", "Титаник", "Titanic", 1997, "фильм", ["romance", "family", "slow"], ["i'm the king of the world", "never let go"], "skip"),
    f("pretty-woman", "Красотка", "Pretty Woman", 1990, "фильм", ["romance", "comedy", "slick-urban"], ["big mistake", "royalty", "вивиан", "edward"], "Красотка"),
    f("dirty-dancing", "Грязные танцы", "Dirty Dancing", 1987, "фильм", ["romance", "tempo", "family"], ["nobody puts baby in a corner", "baby", "johnny", "the time of my life"], "Грязные танцы"),
    f("grease", "Бриолин", "Grease", 1978, "фильм", ["romance", "comedy", "kids"], ["you're the one that i want", "summer nights", "sandy", "danny"], "Бриолин"),
    f("moulin", "Мулен Руж", "Moulin Rouge!", 2001, "фильм", ["romance", "chaotic", "tempo"], ["the greatest thing you'll ever learn", "satine", "christian", "bohemian"], "Мулен Руж"),
    f("la-la-already", "Ла-Ла Ленд", "La La Land", 2016, "фильм", ["romance", "ambition", "slick-urban"], ["city of stars"], "skip"),
    f("ghost", "Привидение", "Ghost", 1990, "фильм", ["romance", "fantasy", "slow"], ["ditto", "unchained melody", "pottery", "сэм"], "Привидение"),
    f("sixth-sense", "Шестое чувство", "The Sixth Sense", 1999, "фильм", ["horror", "slow", "mind-power"], ["i see dead people", "я вижу мёртвых", "cole", "malcolm"], "Шестое чувство"),
    f("others", "Другие", "The Others", 2001, "фильм", ["horror", "slow", "family"], ["we are the others", "шторы", "дети"], "Другие"),
    f("orphan", "Сирота", "Orphan", 2009, "фильм", ["horror", "dark", "family"], ["esther", "не ребёнок"], "Сирота"),
    f("hereditary", "Реинкарнация", "Hereditary", 2018, "фильм", ["horror", "dark", "slow"], ["paimon", " Toni", "голова", "cult"], "Реинкарнация"),
    f("midsommar", "Солнцестояние", "Midsommar", 2019, "фильм", ["horror", "slow", "chaotic"], ["sweden", "cult", "dani", "белый день"], "Солнцестояние"),
    f("witch", "Ведьма", "The Witch", 2015, "фильм", ["horror", "slow", "dark"], ["wouldst thou like to live deliciously", "black philip", "пуритане"], "Ведьма 2015"),
    f("lighthouse", "Маяк", "The Lighthouse", 2019, "фильм", ["horror", "slow", "dark"], ["why'd ya spill yer beans", "willem dafoe", "маяк", "чайки"], "Маяк"),
    f("get-out-already", "Прочь", "Get Out", 2017, "фильм", ["horror", "mind-power", "dark"], ["sunken place"], "skip"),
    f("us", "Мы", "Us", 2019, "фильм", ["horror", "mind-power", "dark"], ["it's us", "tethered", "hands across america"], "Мы Us"),
    f("nope", "Нет", "Nope", 2022, "фильм", ["horror", "slow", "space"], ["i don't think so", "ojo", "лошадь", "тарелка"], "Нет Nope"),
    f("quiet-already", "Тихое место", "A Quiet Place", 2018, "фильм", ["horror", "family", "slow"], ["don't make a sound"], "skip"),
    f("it-already", "Оно", "It", 2017, "фильм", ["horror", "kids", "dark"], ["you'll float too"], "skip"),
    f("shining", "Сияние", "The Shining", 1980, "фильм", ["horror", "slow", "dark"], ["here's johnny", "all work and no play", "redrum", "отель оверлук", "сияние"], "Сияние"),
    f("exorcist", "Изгоняющий дьявола", "The Exorcist", 1973, "фильм", ["horror", "slow", "dark"], ["the power of christ compels you", "реган", "изгнание"], "Изгоняющий дьявола"),
    f("halloween", "Хэллоуин", "Halloween", 1978, "фильм", ["horror", "tempo", "dark"], ["michael myers", "the night he came home", "лори"], "Хэллоуин"),
    f("scream-already", "Крик", "Scream", 1996, "фильм", ["horror", "irony", "tempo"], ["do you like scary movies"], "skip"),
    f("saw", "Пила", "Saw", 2004, "фильм", ["horror", "mind-power", "dark"], ["want to play a game", "jigsaw", "ключ в животе"], "Пила"),
    f("ring", "Звонок", "The Ring", 2002, "фильм", ["horror", "slow", "dark"], ["seven days", "видеокассета", "самара"], "Звонок"),
    f("conjuring-already", "Заклятие", "The Conjuring", 2013, "фильм", ["horror", "family", "dark"], ["annabelle"], "skip"),
    f("annabelle", "Проклятие Аннабель", "Annabelle", 2014, "фильм", ["horror", "dark", "slow"], ["кукла", "warren"], "Аннабель"),
    f("baba", "Астрал", "Insidious", 2010, "фильм", ["horror", "family", "dark"], ["further", "красный демон", "астрал"], "Астрал"),
  ]);
  window.POFRAZE_FILMS = window.POFRAZE_FILMS.filter(function (film) {
    return film.watchQuery !== "skip" && film.watchQuery !== "skip-dup";
  });
})();
