window.POFRAZE_FILMS = window.POFRAZE_FILMS.concat([
  {
    id: "brother-2",
    title: "Брат 2",
    originalTitle: "Brother 2",
    year: 2000,
    type: "фильм",
    initials: "Б2",
    color: "#7f93ab",
    vibes: ["street", "crime", "dark"],
    quotes: [
      "вы кто такие давайте до свидания",
      "русский с американцем братья навек",
      "в чём сила",
    ],
    watchQuery: "Брат 2",
  },
  {
    id: "operation-y",
    title: "Операция «Ы» и другие приключения Шурика",
    originalTitle: "",
    year: 1965,
    type: "фильм",
    initials: "ОЫ",
    color: "#e8d5a0",
    vibes: ["irony", "comedy", "soviet"],
    quotes: [
      "надо фёдор надо",
      "кто не работает тот ест",
      "студент который всегда готов",
    ],
    watchQuery: "Операция Ы",
  },
  {
    id: "caucasian",
    title: "Кавказская пленница",
    originalTitle: "",
    year: 1966,
    type: "фильм",
    initials: "КП",
    color: "#e2c48a",
    vibes: ["irony", "comedy", "soviet"],
    quotes: [
      "студент который всегда готов",
      "жить хорошо а хорошо жить ещё лучше",
      "короче склифосовский",
    ],
    watchQuery: "Кавказская пленница",
  },
  {
    id: "office-romance",
    title: "Служебный роман",
    originalTitle: "",
    year: 1977,
    type: "фильм",
    initials: "СР",
    color: "#d8c4b8",
    vibes: ["romance", "comedy", "soviet"],
    quotes: [
      "новосельцев",
      "вы такая интересная женщина",
      "статистика знает всё",
    ],
    watchQuery: "Служебный роман",
  },
  {
    id: "moscow-tears",
    title: "Москва слезам не верит",
    originalTitle: "",
    year: 1979,
    type: "фильм",
    initials: "МС",
    color: "#d4b0b8",
    vibes: ["romance", "family", "soviet"],
    quotes: [
      "москва слезам не верит",
      "в сорок лет жизнь только начинается",
      "какая ты стала",
    ],
    watchQuery: "Москва слезам не верит",
  },
  {
    id: "kin-dza-dza",
    title: "Кин-дза-дза!",
    originalTitle: "",
    year: 1986,
    type: "фильм",
    initials: "КД",
    color: "#c9b48a",
    vibes: ["irony", "space", "soviet"],
    quotes: [
      "ку",
      "пепелац",
      "чатырдвацатый",
      "вы из какого сектора",
    ],
    watchQuery: "Кин-дза-дза",
  },
  {
    id: "guest-future",
    title: "Гостья из будущего",
    originalTitle: "",
    year: 1984,
    type: "сериал",
    initials: "ГБ",
    color: "#9ec4e0",
    vibes: ["kids", "space", "soviet"],
    quotes: [
      "алиса селезнёва",
      "михроны",
      "это же будущее",
    ],
    watchQuery: "Гостья из будущего",
  },
  {
    id: "twelve-chairs",
    title: "12 стульев",
    originalTitle: "",
    year: 1971,
    type: "фильм",
    initials: "12",
    color: "#dcc89a",
    vibes: ["irony", "heist", "soviet"],
    quotes: [
      "гигант мысли отец русской демократии",
      "лед тронулся господа присяжные заседатели",
      "деньги утром стулья вечером",
    ],
    watchQuery: "12 стульев Гайдай",
  },
  {
    id: "national-hunt",
    title: "Особенности национальной охоты",
    originalTitle: "",
    year: 1995,
    type: "фильм",
    initials: "ОН",
    color: "#b8c49a",
    vibes: ["irony", "comedy", "street"],
    quotes: [
      "ну за охоту",
      "финн ничего не понимает",
      "это традиция",
    ],
    watchQuery: "Особенности национальной охоты",
  },
  {
    id: "grom",
    title: "Майор Гром: Чумной Доктор",
    originalTitle: "",
    year: 2021,
    type: "фильм",
    initials: "МГ",
    color: "#c45a5a",
    vibes: ["crime", "slick-urban", "tempo"],
    quotes: [
      "петербург это я",
      "чумной доктор",
      "я работаю в полиции",
    ],
    watchQuery: "Майор Гром Чумной Доктор",
  },
  {
    id: "word-of-boy",
    title: "Слово пацана. Кровь на асфальте",
    originalTitle: "",
    year: 2023,
    type: "сериал",
    initials: "СП",
    color: "#8a7a6a",
    vibes: ["street", "crime", "dark"],
    quotes: [
      "слово пацана",
      "казань",
      "мы пацаны",
      "чушпан",
      "чушпаны",
      "маларь",
      "яма",
      "пацан сказал пацан сделал",
    ],
    watchQuery: "Слово пацана",
  },
  {
    id: "kitchen",
    title: "Кухня",
    originalTitle: "",
    year: 2012,
    type: "сериал",
    initials: "КУ",
    color: "#e0b070",
    vibes: ["comedy", "ambition", "chaotic"],
    quotes: [
      "шеф это шеф",
      "victor barinov",
      "на кухне я бог",
    ],
    watchQuery: "Кухня сериал",
  },
  {
    id: "forrest",
    title: "Форрест Гамп",
    originalTitle: "Forrest Gump",
    year: 1994,
    type: "фильм",
    initials: "ФГ",
    color: "#c9d48a",
    vibes: ["family", "romance", "irony"],
    quotes: [
      "жизнь как коробка шоколадных конфет",
      "беги форрест беги",
      "я не глупый",
    ],
    watchQuery: "Форрест Гамп",
  },
  {
    id: "shawshank",
    title: "Побег из Шоушенка",
    originalTitle: "The Shawshank Redemption",
    year: 1994,
    type: "фильм",
    initials: "ПШ",
    color: "#a09080",
    vibes: ["slow", "family", "dark"],
    quotes: [
      "надежда это хорошая вещь",
      "занять вас на минутку",
      "библиотека",
    ],
    watchQuery: "Побег из Шоушенка",
  },
  {
    id: "green-mile",
    title: "Зелёная миля",
    originalTitle: "The Green Mile",
    year: 1999,
    type: "фильм",
    initials: "ЗМ",
    color: "#8ab090",
    vibes: ["slow", "family", "dark"],
    quotes: [
      "он как мышь в ловушке",
      "джон коффи",
      "чудо",
    ],
    watchQuery: "Зелёная миля",
  },
  {
    id: "titanic",
    title: "Титаник",
    originalTitle: "Titanic",
    year: 1997,
    type: "фильм",
    initials: "ТТ",
    color: "#8ab8d4",
    vibes: ["romance", "family", "slow"],
    quotes: [
      "я король мира",
      "место на двери",
      "never let go",
      "джек",
    ],
    watchQuery: "Титаник",
  },
  {
    id: "home-alone",
    title: "Один дома",
    originalTitle: "Home Alone",
    year: 1990,
    type: "фильм",
    initials: "ОД",
    color: "#e0a090",
    vibes: ["kids", "comedy", "family"],
    quotes: [
      "счастливого рождества мерзкие уроды",
      "я забыл кевина",
      "это мой дом",
    ],
    watchQuery: "Один дома",
  },
  {
    id: "back-future",
    title: "Назад в будущее",
    originalTitle: "Back to the Future",
    year: 1985,
    type: "фильм",
    initials: "НБ",
    color: "#7ec8e0",
    vibes: ["tempo", "comedy", "kids"],
    quotes: [
      "великий скотт",
      "1.21 гигаватта",
      "дороги нужны там где мы их прокладываем",
      "макфлай",
    ],
    watchQuery: "Назад в будущее",
  },
  {
    id: "terminator-2",
    title: "Терминатор 2: Судный день",
    originalTitle: "Terminator 2",
    year: 1991,
    type: "фильм",
    initials: "Т2",
    color: "#9aa4b0",
    vibes: ["tempo", "dark", "family"],
    quotes: [
      "я вернусь",
      "hasta la vista baby",
      "он не чувствует боли",
    ],
    watchQuery: "Терминатор 2",
  },
  {
    id: "hp1",
    title: "Гарри Поттер и философский камень",
    originalTitle: "Harry Potter and the Philosopher's Stone",
    year: 2001,
    type: "фильм",
    initials: "ГП",
    color: "#c9a050",
    vibes: ["fantasy", "kids", "family"],
    quotes: [
      "ты волшебник гарри",
      "платформа девять и три четверти",
      "распределяющая шляпа",
    ],
    watchQuery: "Гарри Поттер философский камень",
  },
  {
    id: "lotr",
    title: "Властелин колец: Братство Кольца",
    originalTitle: "The Lord of the Rings",
    year: 2001,
    type: "фильм",
    initials: "ВК",
    color: "#7a9a70",
    vibes: ["fantasy", "war", "family"],
    quotes: [
      "ты не пройдёшь",
      "моя прелесть",
      "один властелин чтобы править всеми",
      "фродо",
    ],
    watchQuery: "Властелин колец Братство",
  },
  {
    id: "shrek",
    title: "Шрек",
    originalTitle: "Shrek",
    year: 2001,
    type: "фильм",
    initials: "ШР",
    color: "#8cb85a",
    vibes: ["comedy", "kids", "fantasy"],
    quotes: [
      "огры как луковицы",
      "я осёл",
      "жить болотом",
    ],
    watchQuery: "Шрек",
  },
  {
    id: "lion-king",
    title: "Король Лев",
    originalTitle: "The Lion King",
    year: 1994,
    type: "фильм",
    initials: "КЛ",
    color: "#e0b050",
    vibes: ["kids", "family", "fantasy"],
    quotes: [
      "hakuna matata",
      "помни кто ты",
      "круг жизни",
    ],
    watchQuery: "Король Лев",
  },
  {
    id: "pirates",
    title: "Пираты Карибского моря: Проклятие Чёрной жемчужины",
    originalTitle: "Pirates of the Caribbean",
    year: 2003,
    type: "фильм",
    initials: "ПК",
    color: "#c9a070",
    vibes: ["comedy", "tempo", "fantasy"],
    quotes: [
      "джек воробей",
      "это пиратский кодекс",
      "спасите меня",
    ],
    watchQuery: "Пираты Карибского моря",
  },
  {
    id: "intouchables",
    title: "1+1",
    originalTitle: "Intouchables",
    year: 2011,
    type: "фильм",
    initials: "11",
    color: "#d4c4a0",
    vibes: ["comedy", "family", "romance"],
    quotes: [
      "танцуй",
      "я твой сиделка",
      "это не жалость",
    ],
    watchQuery: "1+1 Untouchables",
  },
  {
    id: "parasite",
    title: "Паразиты",
    originalTitle: "Parasite",
    year: 2019,
    type: "фильм",
    initials: "ПР",
    color: "#6a8a6a",
    vibes: ["dark", "crime", "slow"],
    quotes: [
      "запахло бедностью",
      "план",
      "подвал",
    ],
    watchQuery: "Паразиты",
  },
  {
    id: "whiplash",
    title: "Одержимость",
    originalTitle: "Whiplash",
    year: 2014,
    type: "фильм",
    initials: "ОД",
    color: "#c05040",
    vibes: ["ambition", "dark", "tempo"],
    quotes: [
      "not quite my tempo",
      "не совсем мой темп",
      "лучший джаз",
    ],
    watchQuery: "Одержимость Whiplash",
  },
  {
    id: "john-wick",
    title: "Джон Уик",
    originalTitle: "John Wick",
    year: 2014,
    type: "фильм",
    initials: "Дж",
    color: "#3a3a40",
    vibes: ["tempo", "crime", "dark"],
    quotes: [
      "он убил мою собаку",
      "баба яга",
      "континенталь",
    ],
    watchQuery: "Джон Уик",
  },
  {
    id: "mad-max",
    title: "Безумный Макс: Дорога ярости",
    originalTitle: "Mad Max: Fury Road",
    year: 2015,
    type: "фильм",
    initials: "ММ",
    color: "#d4783a",
    vibes: ["tempo", "war", "chaotic"],
    quotes: [
      "witness me",
      "засвидетельствуй меня",
      "мы едем за водой",
    ],
    watchQuery: "Безумный Макс Дорога ярости",
  },
  {
    id: "dune",
    title: "Дюна",
    originalTitle: "Dune",
    year: 2021,
    type: "фильм",
    initials: "ДЮ",
    color: "#c9b07a",
    vibes: ["space", "slow", "war"],
    quotes: [
      "страх убийца разума",
      "специя должна течь",
      "я пустынная мышь",
    ],
    watchQuery: "Дюна 2021",
  },
  {
    id: "oppenheimer",
    title: "Оппенгеймер",
    originalTitle: "Oppenheimer",
    year: 2023,
    type: "фильм",
    initials: "ОП",
    color: "#f0d090",
    vibes: ["mind-power", "slow", "war"],
    quotes: [
      "я стал смертью разрушителем миров",
      "бомба",
      "лос аламос",
    ],
    watchQuery: "Оппенгеймер",
  },
  {
    id: "barbie",
    title: "Барби",
    originalTitle: "Barbie",
    year: 2023,
    type: "фильм",
    initials: "ББ",
    color: "#f090c0",
    vibes: ["comedy", "irony", "romance"],
    quotes: [
      "я барби",
      "барбиленд",
      "кен",
    ],
    watchQuery: "Барби 2023",
  },
  {
    id: "sherlock",
    title: "Шерлок",
    originalTitle: "Sherlock",
    year: 2010,
    type: "сериал",
    initials: "ШЛ",
    color: "#b0c0d0",
    vibes: ["mind-power", "slick-urban", "tempo"],
    quotes: [
      "элементарно",
      "я шерлок холмс",
      "скучно",
      "ватсон",
    ],
    watchQuery: "Шерлок BBC",
  },
  {
    id: "friends",
    title: "Друзья",
    originalTitle: "Friends",
    year: 1994,
    type: "сериал",
    initials: "ДР",
    color: "#e0c070",
    vibes: ["comedy", "romance", "family"],
    quotes: [
      "we were on a break",
      "у нас был перерыв",
      "как дела",
      "централ перк",
    ],
    watchQuery: "Друзья сериал",
  },
  {
    id: "stranger",
    title: "Очень странные дела",
    originalTitle: "Stranger Things",
    year: 2016,
    type: "сериал",
    initials: "ОС",
    color: "#c04040",
    vibes: ["horror", "kids", "fantasy"],
    quotes: [
      "friends don't lie",
      "друзья не врут",
      "изнанка",
      "одиннадцать",
    ],
    watchQuery: "Очень странные дела",
  },
  {
    id: "squid",
    title: "Игра в кальмара",
    originalTitle: "Squid Game",
    year: 2021,
    type: "сериал",
    initials: "ИК",
    color: "#e07090",
    vibes: ["dark", "crime", "tempo"],
    quotes: [
      "игра в кальмара",
      "красный свет зелёный свет",
      "долги",
    ],
    watchQuery: "Игра в кальмара",
  },
  {
    id: "witcher",
    title: "Ведьмак",
    originalTitle: "The Witcher",
    year: 2019,
    type: "сериал",
    initials: "ВД",
    color: "#7a8a6a",
    vibes: ["fantasy", "dark", "war"],
    quotes: [
      "убить чудовище",
      "судьба",
      "цири",
      "плотва",
    ],
    watchQuery: "Ведьмак сериал",
  },
  {
    id: "house",
    title: "Доктор Хаус",
    originalTitle: "House M.D.",
    year: 2004,
    type: "сериал",
    initials: "ДХ",
    color: "#b05050",
    vibes: ["mind-power", "irony", "slow"],
    quotes: [
      "все врут",
      "это не волчанка",
      "викодин",
    ],
    watchQuery: "Доктор Хаус",
  },
  {
    id: "money-heist",
    title: "Бумажный дом",
    originalTitle: "La Casa de Papel",
    year: 2017,
    type: "сериал",
    initials: "БД",
    color: "#c04040",
    vibes: ["heist", "tempo", "crime"],
    quotes: [
      "белла чао",
      "профессор",
      "мы печатаем деньги",
    ],
    watchQuery: "Бумажный дом",
  },
  {
    id: "avengers",
    title: "Мстители: Финал",
    originalTitle: "Avengers: Endgame",
    year: 2019,
    type: "фильм",
    initials: "МС",
    color: "#5a6ab0",
    vibes: ["tempo", "family", "fantasy"],
    quotes: [
      "я железный человек",
      "собраться",
      "мстители",
    ],
    watchQuery: "Мстители Финал",
  },
  {
    id: "spider",
    title: "Человек-паук: Нет пути домой",
    originalTitle: "Spider-Man: No Way Home",
    year: 2021,
    type: "фильм",
    initials: "ЧП",
    color: "#c04040",
    vibes: ["tempo", "kids", "family"],
    quotes: [
      "с большой силой приходит большая ответственность",
      "нет пути домой",
      "я паук",
    ],
    watchQuery: "Человек-паук Нет пути домой",
  },
  {
    id: "deadpool",
    title: "Дэдпул",
    originalTitle: "Deadpool",
    year: 2016,
    type: "фильм",
    initials: "ДП",
    color: "#c03030",
    vibes: ["comedy", "tempo", "irony"],
    quotes: [
      "максимум усилий",
      "четвёртая стена",
      "я дэдпул",
    ],
    watchQuery: "Дэдпул",
  },
]);
