(function () {
  var f = window.pofrazeFilm;
  if (!f) return;
  window.POFRAZE_FILMS = window.POFRAZE_FILMS.concat([
    f("avengers-1", "Мстители", "The Avengers", 2012, "фильм", ["tempo", "fantasy", "family"], ["we have a hulk", "i'm always angry"], "Мстители 2012"),
    f("ultron", "Мстители: Эра Альтрона", "Avengers: Age of Ultron", 2015, "фильм", ["tempo", "fantasy", "family"], ["i am ultron"], "Эра Альтрона"),
    f("infinity-war", "Мстители: Война бесконечности", "Avengers: Infinity War", 2018, "фильм", ["tempo", "fantasy", "dark"], ["i am inevitable", "why is gamora"], "Война бесконечности"),
    f("winter-soldier-ok", "Первый мститель: Другая война", "Captain America: The Winter Soldier", 2014, "фильм", ["tempo", "war", "slick-urban"], ["skip-dup"], "skip-dup"),
    f("ant-man", "Человек-муравей", "Ant-Man", 2015, "фильм", ["comedy", "tempo", "kids"], ["i do some dumb things"], "Человек-муравей"),
    f("guardians-2", "Стражи Галактики. Часть 2", "Guardians of the Galaxy Vol. 2", 2017, "фильм", ["comedy", "space", "family"], ["he may have been your father boy but he wasn't your daddy"], "Стражи Галактики 2"),
    f("guardians-3", "Стражи Галактики. Часть 3", "Guardians of the Galaxy Vol. 3", 2023, "фильм", ["comedy", "space", "family"], ["i love you guys"], "Стражи Галактики 3"),
    f("doctor-strange-2", "Доктор Стрэндж: В мультивселенной безумия", "Doctor Strange in the Multiverse of Madness", 2022, "фильм", ["fantasy", "horror", "tempo"], ["are you happy"], "Мультивселенная безумия"),
    f("no-way-home-ok", "Человек-паук: Нет пути домой", "Spider-Man: No Way Home", 2021, "фильм", ["tempo", "kids", "family"], ["skip-dup"], "skip-dup"),
    f("homecoming", "Человек-паук: Возвращение домой", "Spider-Man: Homecoming", 2017, "фильм", ["tempo", "kids", "comedy"], ["if you're nothing without the suit you shouldn't have it"], "Человек-паук Возвращение домой"),
    f("far-from-home", "Человек-паук: Вдали от дома", "Spider-Man: Far From Home", 2019, "фильм", ["tempo", "kids", "comedy"], ["i love you guys i'm sorry"], "Человек-паук Вдали от дома"),
    f("captain-marvel", "Капитан Марвел", "Captain Marvel", 2019, "фильм", ["tempo", "space", "war"], ["higher further faster"], "Капитан Марвел"),
    f("black-widow", "Чёрная вдова", "Black Widow", 2021, "фильм", ["tempo", "family", "slick-urban"], ["i've got red in my ledger"], "Чёрная вдова"),
    f("shang-chi", "Шан-Чи и легенда десяти колец", "Shang-Chi and the Legend of the Ten Rings", 2021, "фильм", ["tempo", "fantasy", "family"], ["and now i must warn you"], "Шан-Чи"),
    f("wakanda-2", "Чёрная пантера: Ваканда навсегда", "Black Panther: Wakanda Forever", 2022, "фильм", ["family", "war", "fantasy"], ["wakanda forever"], "Ваканда навсегда"),
    f("thor-2", "Тор 2: Царство тьмы", "Thor: The Dark World", 2013, "фильм", ["fantasy", "comedy", "tempo"], ["i'll have both"], "Тор Царство тьмы"),
    f("thor-4", "Тор: Любовь и гром", "Thor: Love and Thunder", 2022, "фильм", ["comedy", "fantasy", "tempo"], ["the goat boat"], "Тор Любовь и гром"),
    f("batman-begins", "Бэтмен: Начало", "Batman Begins", 2005, "фильм", ["dark", "crime", "slick-urban"], ["it's not who i am underneath but what i do that defines me"], "Бэтмен Начало"),
    f("the-batman", "Бэтмен", "The Batman", 2022, "фильм", ["dark", "crime", "slow"], ["i am vengeance"], "Бэтмен 2022"),
    f("joker-2", "Джокер: Безумие на двоих", "Joker: Folie à Deux", 2024, "фильм", ["dark", "romance", "crime"], ["that's life"], "Джокер Безумие на двоих"),
    f("man-of-steel", "Человек из стали", "Man of Steel", 2013, "фильм", ["tempo", "fantasy", "family"], ["you are my son"], "Человек из стали"),
    f("wonder-woman", "Чудо-женщина", "Wonder Woman", 2017, "фильм", ["war", "fantasy", "tempo"], ["it's not about deserve it's about what you believe"], "Чудо-женщина"),
    f("aquaman", "Аквамен", "Aquaman", 2018, "фильм", ["tempo", "fantasy", "family"], ["i'm going home"], "Аквамен"),
    f("x-men", "Люди Икс", "X-Men", 2000, "фильм", ["tempo", "fantasy", "family"], ["mutant and proud"], "Люди Икс"),
    f("x2", "Люди Икс 2", "X2", 2003, "фильм", ["tempo", "fantasy", "war"], ["the next war will be mutant"], "Люди Икс 2"),
    f("days-future", "Люди Икс: Дни минувшего будущего", "X-Men: Days of Future Past", 2014, "фильм", ["tempo", "fantasy", "mind-power"], ["just because someone stumbles and loses their path"], "Дни минувшего будущего"),
    f("first-class", "Люди Икс: Первый класс", "X-Men: First Class", 2011, "фильм", ["tempo", "war", "fantasy"], ["mutant and proud"], "Первый класс"),
    f("deadpool-2", "Дэдпул 2", "Deadpool 2", 2018, "фильм", ["comedy", "tempo", "irony"], ["maximum effort", "family"], "Дэдпул 2"),
    f("matrix-2", "Матрица: Перезагрузка", "The Matrix Reloaded", 2003, "фильм", ["mind-power", "tempo", "dark"], ["choice is an illusion"], "Матрица Перезагрузка"),
    f("matrix-3", "Матрица: Революция", "The Matrix Revolutions", 2003, "фильм", ["mind-power", "tempo", "war"], ["everything that has a beginning has an end"], "Матрица Революция"),
    f("hobbit-1", "Хоббит: Нежданное путешествие", "The Hobbit: An Unexpected Journey", 2012, "фильм", ["fantasy", "kids", "family"], ["i'm going on an adventure"], "Хоббит Нежданное путешествие"),
    f("hobbit-2", "Хоббит: Пустошь Смауга", "The Hobbit: The Desolation of Smaug", 2013, "фильм", ["fantasy", "tempo", "war"], ["i am fire i am death"], "Хоббит Пустошь Смауга"),
    f("hobbit-3", "Хоббит: Битва пяти воинств", "The Hobbit: The Battle of the Five Armies", 2014, "фильм", ["fantasy", "war", "family"], ["will you follow me one last time"], "Хоббит Битва пяти воинств"),
    f("hp6", "Гарри Поттер и Принц-полукровка", "Harry Potter and the Half-Blood Prince", 2009, "фильм", ["fantasy", "kids", "dark"], ["it is the unknown we fear when we look upon death and darkness"], "Гарри Поттер Принц-полукровка"),
    f("fantastic-beasts", "Фантастические твари и где они обитают", "Fantastic Beasts and Where to Find Them", 2016, "фильм", ["fantasy", "kids", "comedy"], ["my philosophy is that worrying means you suffer twice"], "Фантастические твари"),
    f("star-trek-09", "Стартрек", "Star Trek", 2009, "фильм", ["space", "tempo", "comedy"], ["the needs of the many"], "Стартрек 2009"),
    f("wrath-khan", "Звёздный путь 2: Гнев Хана", "Star Trek II: The Wrath of Khan", 1982, "фильм", ["space", "war", "family"], ["khan", "the needs of the many outweigh the needs of the few"], "Гнев Хана"),
    f("into-darkness", "Стартрек: Возмездие", "Star Trek Into Darkness", 2013, "фильм", ["space", "tempo", "war"], ["the needs of the many"], "Стартрек Возмездие"),
    f("fast-furious", "Форсаж", "The Fast and the Furious", 2001, "фильм", ["tempo", "crime", "family"], ["i live my life a quarter mile at a time"], "Форсаж"),
    f("tokyo-drift", "Тройной форсаж: Токийский дрифт", "The Fast and the Furious: Tokyo Drift", 2006, "фильм", ["tempo", "slick-urban", "kids"], ["drift"], "Токийский дрифт"),
    f("furious-7", "Форсаж 7", "Furious 7", 2015, "фильм", ["tempo", "family", "crime"], ["i don't have friends i got family"], "Форсаж 7"),
    f("mi-1", "Миссия невыполнима", "Mission: Impossible", 1996, "фильм", ["tempo", "heist", "slick-urban"], ["this tape will self destruct"], "Миссия невыполнима"),
    f("ghost-protocol", "Миссия невыполнима: Протокол Фантом", "Mission: Impossible – Ghost Protocol", 2011, "фильм", ["tempo", "heist", "slick-urban"], ["the secretary will disavow"], "Протокол Фантом"),
    f("last-crusade", "Индиана Джонс и последний крестовый поход", "Indiana Jones and the Last Crusade", 1989, "фильм", ["tempo", "comedy", "fantasy"], ["he chose poorly"], "Последний крестовый поход"),
    f("pirates-2", "Пираты Карибского моря: Сундук мертвеца", "Pirates of the Caribbean: Dead Man's Chest", 2006, "фильм", ["comedy", "fantasy", "tempo"], ["the compass doesn't point north"], "Сундук мертвеца"),
    f("pirates-3", "Пираты Карибского моря: На краю света", "Pirates of the Caribbean: At World's End", 2007, "фильм", ["fantasy", "tempo", "war"], ["hoist the colours"], "На краю света"),
    f("jurassic-world", "Мир Юрского периода", "Jurassic World", 2015, "фильм", ["tempo", "kids", "horror"], ["the park is open"], "Мир Юрского периода"),
    f("godzilla-14", "Годзилла", "Godzilla", 2014, "фильм", ["tempo", "horror", "war"], ["let them fight"], "Годзилла 2014"),
    f("kong", "Конг: Остров черепа", "Kong: Skull Island", 2017, "фильм", ["tempo", "horror", "war"], ["is that a monkey"], "Конг Остров черепа"),
    f("dawn-apes", "Планета обезьян: Революция", "Dawn of the Planet of the Apes", 2014, "фильм", ["war", "slow", "family"], ["ape not kill ape"], "Планета обезьян Революция"),
    f("alien-3", "Чужой 3", "Alien 3", 1992, "фильм", ["horror", "space", "dark"], ["you've been in my life so long i can't remember anything else"], "Чужой 3"),
    f("prometheus", "Прометей", "Prometheus", 2012, "фильм", ["space", "horror", "slow"], ["big things have small beginnings"], "Прометей"),
    f("covenant", "Чужой: Завет", "Alien: Covenant", 2017, "фильм", ["horror", "space", "dark"], ["serve in heaven or reign in hell"], "Чужой Завет"),
    f("prey", "Добыча", "Prey", 2022, "фильм", ["tempo", "horror", "war"], ["if it bleeds we can kill it"], "Добыча"),
    f("t3", "Терминатор 3: Восстание машин", "Terminator 3: Rise of the Machines", 2003, "фильм", ["tempo", "dark", "family"], ["i'm back"], "Терминатор 3"),
    f("dark-fate", "Терминатор: Тёмные судьбы", "Terminator: Dark Fate", 2019, "фильм", ["tempo", "dark", "family"], ["i'll be back"], "Терминатор Тёмные судьбы"),
    f("rocky-2", "Рокки 2", "Rocky II", 1979, "фильм", ["sport", "family", "ambition"], ["yo adrian"], "Рокки 2"),
    f("rocky-4", "Рокки 4", "Rocky IV", 1985, "фильм", ["sport", "war", "ambition"], ["if i can change and you can change everybody can change"], "Рокки 4"),
    f("creed", "Крид: Наследие Рокки", "Creed", 2015, "фильм", ["sport", "family", "ambition"], ["one step at a time one punch at a time"], "Крид"),
    f("rambo", "Рэмбо: Первая кровь", "First Blood", 1982, "фильм", ["war", "tempo", "dark"], ["they drew first blood"], "Рэмбо Первая кровь"),
    f("die-hard-2", "Крепкий орешек 2", "Die Hard 2", 1990, "фильм", ["tempo", "crime", "irony"], ["how can the same shit happen to the same guy twice"], "Крепкий орешек 2"),
    f("home-alone-2", "Один дома 2: Затерянный в Нью-Йорке", "Home Alone 2: Lost in New York", 1992, "фильм", ["kids", "comedy", "family"], ["keep the change ya filthy animal"], "Один дома 2"),
    f("ghostbusters-afterlife", "Охотники за привидениями: Наследники", "Ghostbusters: Afterlife", 2021, "фильм", ["comedy", "fantasy", "kids"], ["who you gonna call"], "Охотники за привидениями Наследники"),
    f("beetlejuice-2", "Битлджус Битлджус", "Beetlejuice Beetlejuice", 2024, "фильм", ["comedy", "horror", "fantasy"], ["it's showtime"], "Битлджус Битлджус"),
    f("wonka", "Вонка", "Wonka", 2023, "фильм", ["kids", "comedy", "fantasy"], ["every good thing in this world started with a dream"], "Вонка"),
    f("wicked", "Злая", "Wicked", 2024, "фильм", ["fantasy", "kids", "romance"], ["defying gravity"], "Злая Wicked"),
    f("moana-2", "Моана 2", "Moana 2", 2024, "фильм", ["kids", "fantasy", "family"], ["we know the way"], "Моана 2"),
    f("frozen-2", "Холодное сердце 2", "Frozen II", 2019, "фильм", ["kids", "fantasy", "family"], ["into the unknown"], "Холодное сердце 2"),
    f("toy-story-2", "История игрушек 2", "Toy Story 2", 1999, "фильм", ["kids", "comedy", "family"], ["to infinity and beyond"], "История игрушек 2"),
    f("toy-story-3", "История игрушек 3", "Toy Story 3", 2010, "фильм", ["kids", "family", "comedy"], ["so long partner"], "История игрушек 3"),
    f("finding-dory", "В поисках Дори", "Finding Dory", 2016, "фильм", ["kids", "comedy", "family"], ["just keep swimming"], "В поисках Дори"),
    f("monsters-inc", "Корпорация монстров", "Monsters, Inc.", 2001, "фильм", ["kids", "comedy", "family"], ["we scare because we care"], "Корпорация монстров"),
    f("zootopia", "Зверополис", "Zootopia", 2016, "фильм", ["kids", "comedy", "crime"], ["try everything"], "Зверополис"),
    f("encanto", "Энканто", "Encanto", 2021, "фильм", ["kids", "family", "fantasy"], ["we don't talk about bruno"], "Энканто"),
    f("mario", "Братья Супер Марио в кино", "The Super Mario Bros. Movie", 2023, "фильм", ["kids", "comedy", "tempo"], ["it's a me mario"], "Братья Супер Марио"),
    f("sonic", "Соник в кино", "Sonic the Hedgehog", 2020, "фильм", ["kids", "comedy", "tempo"], ["you're too slow"], "Соник в кино"),
    f("twilight-2", "Сумерки. Сага. Новолуние", "The Twilight Saga: New Moon", 2009, "фильм", ["romance", "fantasy", "kids"], ["the lion fell in love with the lamb"], "Новолуние"),
    f("catching-fire", "Голодные игры: И вспыхнет пламя", "The Hunger Games: Catching Fire", 2013, "фильм", ["tempo", "war", "kids"], ["if we burn you burn with us"], "И вспыхнет пламя"),
    f("mockingjay", "Голодные игры: Сойка-пересмешница", "The Hunger Games: Mockingjay – Part 1", 2014, "фильм", ["war", "tempo", "kids"], ["people of panem we fight we dare we end our hunger for justice"], "Сойка-пересмешница"),
    f("maze-runner", "Бегущий в лабиринте", "The Maze Runner", 2014, "фильм", ["tempo", "kids", "dark"], ["wickedness"], "Бегущий в лабиринте"),
    f("divergent", "Дивергент", "Divergent", 2014, "фильм", ["tempo", "kids", "mind-power"], ["faction before blood"], "Дивергент"),
    f("bridgerton", "Бриджертоны", "Bridgerton", 2020, "сериал", ["romance", "irony", "family"], ["dear gentle reader"], "Бриджертоны"),
    f("ted-lasso", "Тед Лассо", "Ted Lasso", 2020, "сериал", ["comedy", "sport", "family"], ["be curious not judgemental", "football is life"], "Тед Лассо"),
    f("severance", "Разделение", "Severance", 2022, "сериал", ["mind-power", "slow", "dark"], ["the work is mysterious and important"], "Разделение"),
    f("yellowjackets", "Йеллоуджекетс", "Yellowjackets", 2021, "сериал", ["horror", "dark", "slow"], ["we were never lost"], "Йеллоуджекетс"),
    f("invincible", "Неуязвимый", "Invincible", 2021, "сериал", ["tempo", "dark", "family"], ["think mark think"], "Неуязвимый"),
    f("bojack", "Конь БоДжек", "BoJack Horseman", 2014, "сериал", ["comedy", "dark", "irony"], ["that's too much man"], "Конь БоДжек"),
    f("south-park", "Южный парк", "South Park", 1997, "сериал", ["comedy", "irony", "chaotic"], ["oh my god they killed kenny"], "Южный парк"),
    f("family-guy", "Гриффины", "Family Guy", 1999, "сериал", ["comedy", "irony", "family"], ["giggity"], "Гриффины"),
    f("avatar-atla", "Аватар: Легенда об Аанге", "Avatar: The Last Airbender", 2005, "сериал", ["fantasy", "kids", "family"], ["i'm the last airbender"], "Аватар Легенда об Аанге"),
    f("mononoke", "Принцесса Мононоке", "Princess Mononoke", 1997, "фильм", ["fantasy", "war", "slow"], ["see with eyes unclouded"], "Принцесса Мононоке"),
    f("totoro", "Мой сосед Тоторо", "My Neighbor Totoro", 1988, "фильм", ["kids", "fantasy", "family"], ["totoro"], "Мой сосед Тоторо"),
    f("howl", "Ходячий замок", "Howl's Moving Castle", 2004, "фильм", ["fantasy", "romance", "kids"], ["a heart is a heavy burden"], "Ходячий замок"),
    f("kiki", "Ведьмина служба доставки", "Kiki's Delivery Service", 1989, "фильм", ["kids", "comedy", "fantasy"], ["we fly with our spirit"], "Ведьмина служба доставки"),
    f("grave-fireflies", "Могила светлячков", "Grave of the Fireflies", 1988, "фильм", ["war", "family", "slow"], ["why do fireflies have to die so soon"], "Могила светлячков"),
    f("akira", "Акира", "Akira", 1988, "фильм", ["tempo", "dark", "mind-power"], ["kaneda"], "Акира"),
    f("ghost-shell", "Призрак в доспехах", "Ghost in the Shell", 1995, "фильм", ["slow", "mind-power", "slick-urban"], ["the net is vast and infinite"], "Призрак в доспехах"),
    f("weathering", "Дитя погоды", "Weathering with You", 2019, "фильм", ["romance", "fantasy", "kids"], ["i want to be with you"], "Дитя погоды"),
    f("suzume", "Судзумэ, закрывающая двери", "Suzume", 2022, "фильм", ["fantasy", "kids", "tempo"], ["don't look back"], "Судзумэ"),
    f("jujutsu-0", "Магическая битва 0", "Jujutsu Kaisen 0", 2021, "фильм", ["fantasy", "tempo", "dark"], ["i'll save you even if it kills me"], "Магическая битва 0"),
    f("fmab", "Стальной алхимик", "Fullmetal Alchemist: Brotherhood", 2009, "сериал", ["fantasy", "war", "family"], ["a lesson without pain is meaningless", "equivalent exchange"], "Стальной алхимик"),
    f("hxh", "Хантер х Хантер", "Hunter x Hunter", 2011, "сериал", ["fantasy", "tempo", "family"], ["you should enjoy the little detours"], "Хантер х Хантер"),
    f("bleach", "Блич", "Bleach", 2004, "сериал", ["fantasy", "tempo", "dark"], ["bankai"], "Блич"),
    f("evangelion", "Евангелион", "Neon Genesis Evangelion", 1995, "сериал", ["dark", "mind-power", "slow"], ["congratulations"], "Евангелион"),
    f("cowboy-bebop", "Ковбой Бибоп", "Cowboy Bebop", 1998, "сериал", ["slick-urban", "slow", "space"], ["see you space cowboy"], "Ковбой Бибоп"),
    f("ahsoka", "Асока", "Ahsoka", 2023, "сериал", ["fantasy", "space", "war"], ["i am no jedi"], "Асока"),
    f("andor-ok", "Андор", "Andor", 2022, "сериал", ["war", "slow", "space"], ["skip-dup"], "skip-dup"),
    f("fallout-ok", "Фоллаут", "Fallout", 2024, "сериал", ["tempo", "irony", "war"], ["skip-dup"], "skip-dup"),
    f("twisters", "Смерч 2", "Twisters", 2024, "фильм", ["tempo", "family", "slow"], ["if you feel it chase it"], "Смерч 2"),
    f("fall-guy", "Каскадёр", "The Fall Guy", 2024, "фильм", ["comedy", "tempo", "romance"], ["i'm a stuntman"], "Каскадёр"),
    f("poor-things", "Бедные-несчастные", "Poor Things", 2023, "фильм", ["irony", "romance", "mind-power"], ["i have the world to eat"], "Бедные-несчастные"),
    f("anatomy-fall", "Анатомия падения", "Anatomy of a Fall", 2023, "фильм", ["crime", "slow", "mind-power"], ["did you kill your husband"], "Анатомия падения"),
    f("zone-interest", "Зона интересов", "The Zone of Interest", 2023, "фильм", ["war", "slow", "dark"], ["i want to live how i want"], "Зона интересов"),
    f("holdovers", "Оставленные", "The Holdovers", 2023, "фильм", ["comedy", "family", "slow"], ["i find the world a bitter and complicated place"], "Оставленные"),
    f("past-lives", "Прошлые жизни", "Past Lives", 2023, "фильм", ["romance", "slow", "family"], ["you dream in a language i can't understand"], "Прошлые жизни"),
    f("killers-moon", "Убийцы цветочной луны", "Killers of the Flower Moon", 2023, "фильм", ["crime", "slow", "dark"], ["can you find the wolves in this picture"], "Убийцы цветочной луны"),
    f("challengers", "Претенденты", "Challengers", 2024, "фильм", ["sport", "romance", "tempo"], ["i'm gonna win"], "Претенденты"),
    f("furiosa", "Фуриоса: Хроники Безумного Макса", "Furiosa: A Mad Max Saga", 2024, "фильм", ["tempo", "war", "dark"], ["i am the fifth"], "Фуриоса"),
    f("civil-war-garland", "Гражданская война", "Civil War", 2024, "фильм", ["war", "slow", "dark"], ["what kind of american are you"], "Гражданская война Гарланд"),
    f("minecraft", "Майнкрафт в кино", "A Minecraft Movie", 2025, "фильм", ["kids", "comedy", "fantasy"], ["i am steve", "chicken jockey"], "Майнкрафт в кино"),
    f("novocaine", "Новокаин", "Novocaine", 2025, "фильм", ["tempo", "comedy", "crime"], ["i can't feel pain"], "Новокаин"),
    f("sinners", "Грешники", "Sinners", 2025, "фильм", ["horror", "dark", "tempo"], ["the south"], "Грешники"),
    f("companion", "Компаньонка", "Companion", 2025, "фильм", ["horror", "mind-power", "slick-urban"], ["i'm not what you think"], "Компаньонка"),
    f("mickey-17", "Микки 17", "Mickey 17", 2025, "фильм", ["space", "irony", "slow"], ["i'm expendable"], "Микки 17"),
    f("the-substance", "Субстанция", "The Substance", 2024, "фильм", ["horror", "irony", "dark"], ["have you ever dreamt of a better version of yourself"], "Субстанция"),
    f("conclave", "Конклав", "Conclave", 2024, "фильм", ["slow", "mind-power", "ambition"], ["certainty is the great enemy of unity"], "Конклав"),
    f("emilia-perez", "Эмилия Перес", "Emilia Pérez", 2024, "фильм", ["crime", "irony", "tempo"], ["un hombre"], "Эмилия Перес"),
    f("anora", "Анора", "Anora", 2024, "фильм", ["comedy", "romance", "street"], ["anora"], "Анора"),
    f("brutalist", "Бруталист", "The Brutalist", 2024, "фильм", ["slow", "ambition", "family"], ["it is not enough to be hungry"], "Бруталист"),
    f("dune-prophecy", "Дюна: Пророчество", "Dune: Prophecy", 2024, "сериал", ["fantasy", "slow", "family"], ["the sisterhood"], "Дюна Пророчество"),
    f("shogun", "Сёгун", "Shōgun", 2024, "сериал", ["war", "slow", "ambition"], ["skip-dup"], "skip-dup"),
    f("the-penguin", "Пингвин", "The Penguin", 2024, "сериал", ["crime", "dark", "slick-urban"], ["i'm oz cobb"], "Пингвин"),
    f("agatha", "Агата Все дороги ведут", "Agatha All Along", 2024, "сериал", ["fantasy", "comedy", "dark"], ["the trial"], "Агата"),
    f("skeleton-crew", "Звёздные войны: Скелетный экипаж", "Star Wars: Skeleton Crew", 2024, "сериал", ["space", "kids", "tempo"], ["we're lost"], "Скелетный экипаж"),
    f("andor-s2", "Андор", "Andor", 2022, "сериал", ["war", "slow", "space"], ["skip-dup"], "skip-dup"),
    f("white-lotus-s3", "Белый лотос", "The White Lotus", 2021, "сериал", ["irony", "dark", "slow"], ["skip-dup"], "skip-dup"),
    f("the-studio", "Студия", "The Studio", 2025, "сериал", ["comedy", "ambition", "slick-urban"], ["hollywood"], "Студия сериал"),
    f("adolescence", "Подросток", "Adolescence", 2025, "сериал", ["crime", "slow", "family"], ["one take"], "Подросток"),
    f("severance-s2", "Разделение", "Severance", 2022, "сериал", ["mind-power", "slow", "dark"], ["skip-dup"], "skip-dup"),
    f("last-of-us-s2", "Одни из нас", "The Last of Us", 2023, "сериал", ["dark", "family", "horror"], ["skip-dup"], "skip-dup"),
    f("andor-ok2", "Андор", "Andor", 2022, "сериал", ["war", "slow", "space"], ["skip-dup"], "skip-dup"),
    f("pokrovskie-ok", "Покровские ворота", "", 1982, "фильм", ["soviet", "comedy", "romance"], ["skip-dup"], "skip-dup"),
    f("formula-love-ok", "Формула любви", "", 1984, "фильм", ["soviet", "comedy", "romance"], ["skip-dup"], "skip-dup"),
    f("office-romance-ok", "Служебный роман", "", 1977, "фильм", ["soviet", "comedy", "romance"], ["skip-dup"], "skip-dup"),
    f("love-and-pigeons", "Любовь и голуби", "", 1984, "фильм", ["soviet", "comedy", "family"], ["skip-dup"], "skip-dup"),
    f("afonya-ok", "Афоня", "", 1975, "фильм", ["soviet", "comedy", "street"], ["skip-dup"], "skip-dup"),
    f("eldest-son", "Старший сын", "", 1975, "фильм", ["soviet", "family", "irony"], ["я ваш сын"], "Старший сын"),
    f("autumn-marathon", "Осенний марафон", "", 1979, "фильм", ["soviet", "irony", "romance"], ["бузыкин"], "Осенний марафон"),
    f("unfinished-piece", "Неоконченная пьеса для механического пианино", "", 1977, "фильм", ["soviet", "slow", "irony"], ["чехов"], "Неоконченная пьеса"),
    f("slave-of-love", "Раба любви", "", 1976, "фильм", ["soviet", "romance", "slow"], ["немое кино"], "Раба любви"),
    f("cranes", "Летят журавли", "", 1957, "фильм", ["war", "romance", "slow"], ["летят журавли"], "Летят журавли"),
    f("ballad-soldier", "Баллада о солдате", "", 1959, "фильм", ["war", "family", "romance"], ["в отпуск"], "Баллада о солдате"),
    f("ivan-childhood", "Иваново детство", "", 1962, "фильм", ["war", "slow", "dark"], ["иван"], "Иваново детство"),
    f("andrei-rublev", "Андрей Рублёв", "", 1966, "фильм", ["slow", "war", "family"], ["рублёв"], "Андрей Рублёв"),
    f("solaris-tark", "Солярис", "", 1972, "фильм", ["space", "slow", "mind-power"], ["океан", "хари"], "Солярис Тарковский"),
    f("mirror-tark", "Зеркало", "", 1975, "фильм", ["slow", "family", "mind-power"], ["зеркало"], "Зеркало Тарковский"),
    f("stalker-tark", "Сталкер", "", 1979, "фильм", ["slow", "mind-power", "dark"], ["зона", "комната желаний"], "Сталкер"),
    f("nostalghia", "Ностальгия", "", 1983, "фильм", ["slow", "mind-power", "romance"], ["свеча"], "Ностальгия"),
    f("sacrifice-tark", "Жертвоприношение", "", 1986, "фильм", ["slow", "family", "dark"], ["жертва"], "Жертвоприношение"),
    f("come-and-see", "Иди и смотри", "", 1985, "фильм", ["war", "dark", "slow"], ["иди и смотри"], "Иди и смотри"),
    f("commisar", "Комиссар", "", 1967, "фильм", ["war", "family", "slow"], ["комиссар"], "Комиссар"),
    f("letter-never", "Письма мёртвого человека", "", 1986, "фильм", ["dark", "slow", "space"], ["после атомной"], "Письма мёртвого человека"),
    f("kin-dza-ok", "Кин-дза-дза!", "", 1986, "фильм", ["soviet", "irony", "space"], ["skip-dup"], "skip-dup"),
    f("moscow-does-not", "Москва слезам не верит", "", 1980, "фильм", ["soviet", "romance", "family"], ["skip-dup"], "skip-dup"),
    f("irony-ok", "Ирония судьбы, или С лёгким паром!", "", 1975, "фильм", ["soviet", "romance", "comedy"], ["skip-dup"], "skip-dup"),
    f("gentlemen-ok", "Джентльмены удачи", "", 1971, "фильм", ["soviet", "comedy", "heist"], ["skip-dup"], "skip-dup"),
    f("operation-y-ok", "Операция «Ы» и другие приключения Шурика", "", 1965, "фильм", ["soviet", "comedy", "irony"], ["skip-dup"], "skip-dup"),
    f("caucasian-ok", "Кавказская пленница", "", 1966, "фильм", ["soviet", "comedy", "irony"], ["skip-dup"], "skip-dup"),
    f("diamond-ok", "Бриллиантовая рука", "", 1968, "фильм", ["soviet", "comedy", "heist"], ["skip-dup"], "skip-dup"),
    f("ivan-v-ok", "Иван Васильевич меняет профессию", "", 1973, "фильм", ["soviet", "comedy", "fantasy"], ["skip-dup"], "skip-dup"),
    f("meeting-ok", "Место встречи изменить нельзя", "", 1979, "сериал", ["soviet", "crime", "slow"], ["skip-dup"], "skip-dup"),
    f("seventeen-ok", "Семнадцать мгновений весны", "", 1973, "сериал", ["soviet", "war", "slow"], ["skip-dup"], "skip-dup"),
    f("sherlock-holmes-livanov", "Приключения Шерлока Холмса и доктора Ватсона", "", 1979, "сериал", ["soviet", "crime", "mind-power"], ["элементарно ватсон", "холмс"], "Шерлок Холмс Ливанов"),
    f("little-red", "Обыкновенное чудо", "", 1978, "фильм", ["soviet", "fantasy", "romance"], ["обыкновенное чудо"], "Обыкновенное чудо"),
    f("charodei-ok", "Чародеи", "", 1982, "фильм", ["soviet", "comedy", "fantasy"], ["skip-dup"], "skip-dup"),
    f("guest-ok", "Гостья из будущего", "", 1984, "сериал", ["soviet", "kids", "space"], ["skip-dup"], "skip-dup"),
    f("elektron-ok", "Приключения Электроника", "", 1979, "сериал", ["soviet", "kids", "comedy"], ["skip-dup"], "skip-dup"),
    f("valuev", "Приключения Буратино", "", 1975, "фильм", ["soviet", "kids", "fantasy"], ["буратино", "карабас"], "Приключения Буратино"),
    f("old-man-hottabych", "Старик Хоттабыч", "", 1956, "фильм", ["soviet", "kids", "fantasy"], ["ляпота"], "Старик Хоттабыч"),
    f("kingdom-crooked", "Королевство кривых зеркал", "", 1963, "фильм", ["soviet", "kids", "fantasy"], ["оля и ялё"], "Королевство кривых зеркал"),
    f("morozko", "Морозко", "", 1964, "фильм", ["soviet", "kids", "fantasy"], ["по щучьему велению", "морозко"], "Морозко"),
    f("sadko", "Садко", "", 1952, "фильм", ["soviet", "fantasy", "kids"], ["садко"], "Садко"),
    f("amphibian", "Человек-амфибия", "", 1961, "фильм", ["soviet", "romance", "fantasy"], ["ихтиандр"], "Человек-амфибия"),
    f("questor", "Квест", "", 2015, "сериал", ["tempo", "mind-power", "crime"], ["квест москва"], "Квест сериал"),
    f("gogol", "Гоголь", "", 2017, "фильм", ["horror", "fantasy", "crime"], ["виц", "диканка"], "Гоголь фильм"),
    f("vikings", "Викинги", "Vikings", 2013, "сериал", ["war", "family", "dark"], ["odin", "ragnar"], "Викинги"),
    f("the-expanse", "Пространство", "The Expanse", 2015, "сериал", ["space", "slow", "tempo"], ["remember the cant"], "Пространство"),
    f("battlestar", "Звёздный крейсер Галактика", "Battlestar Galactica", 2004, "сериал", ["space", "war", "mind-power"], ["so say we all"], "Звёздный крейсер Галактика"),
    f("firefly", "Светлячок", "Firefly", 2002, "сериал", ["space", "comedy", "tempo"], ["i aim to misbehave"], "Светлячок"),
    f("serenity", "Миссия Серенити", "Serenity", 2005, "фильм", ["space", "tempo", "war"], ["i aim to misbehave"], "Серенити"),
    f("farscape", "На краю вселенной", "Farscape", 1999, "сериал", ["space", "comedy", "tempo"], ["that was uncharted"], "На краю вселенной"),
    f("stargate", "Звёздные врата SG-1", "Stargate SG-1", 1997, "сериал", ["space", "tempo", "war"], ["indeed"], "Звёздные врата SG-1"),
    f("x-files", "Секретные материалы", "The X-Files", 1993, "сериал", ["slow", "mind-power", "dark"], ["the truth is out there", "i want to believe"], "Секретные материалы"),
    f("twin-peaks", "Твин Пикс", "Twin Peaks", 1990, "сериал", ["slow", "dark", "mind-power"], ["the owls are not what they seem", "damn fine coffee"], "Твин Пикс"),
    f("fargo-tv", "Фарго", "Fargo", 2014, "сериал", ["crime", "irony", "slow"], ["this is a true story"], "Фарго сериал"),
    f("true-detective-ok", "Настоящий детектив", "True Detective", 2014, "сериал", ["crime", "dark", "slow"], ["skip-dup"], "skip-dup"),
    f("ozark", "Озарк", "Ozark", 2017, "сериал", ["crime", "slow", "family"], ["money"], "Озарк"),
    f("narcos-mexico", "Нарко: Мексика", "Narcos: Mexico", 2018, "сериал", ["crime", "ambition", "tempo"], ["plaza"], "Нарко Мексика"),
    f("mindhunter-ok", "Охотник за разумом", "Mindhunter", 2017, "сериал", ["crime", "slow", "mind-power"], ["skip-dup"], "skip-dup"),
    f("dahmer", "Монстр: История Джеффри Дамера", "Dahmer", 2022, "сериал", ["crime", "dark", "slow"], ["jeffrey"], "Дамер"),
    f("you-netflix", "Ты", "You", 2018, "сериал", ["crime", "dark", "romance"], ["hello you"], "Ты сериал"),
    f("sex-education", "Половое воспитание", "Sex Education", 2019, "сериал", ["comedy", "romance", "kids"], ["clinic"], "Половое воспитание"),
    f("umbrella", "Академия Амбрелла", "The Umbrella Academy", 2019, "сериал", ["fantasy", "comedy", "family"], ["number five"], "Академия Амбрелла"),
    f("locke-key", "Ключи Локков", "Locke & Key", 2020, "сериал", ["fantasy", "horror", "kids"], ["the keys"], "Ключи Локков"),
    f("sandman", "Песочный человек", "The Sandman", 2022, "сериал", ["fantasy", "slow", "dark"], ["i am dream of the endless"], "Песочный человек"),
    f("witcher-ok", "Ведьмак", "The Witcher", 2019, "сериал", ["fantasy", "tempo", "dark"], ["skip-dup"], "skip-dup"),
    f("house-dragon-ok", "Дом Дракона", "House of the Dragon", 2022, "сериал", ["family", "dark", "war"], ["skip-dup"], "skip-dup"),
    f("rings-power", "Властелин колец: Кольца власти", "The Lord of the Rings: The Rings of Power", 2022, "сериал", ["fantasy", "war", "slow"], ["the rings of power"], "Кольца власти"),
    f("wheel-time", "Колесо времени", "The Wheel of Time", 2021, "сериал", ["fantasy", "war", "family"], ["the wheel weaves"], "Колесо времени"),
    f("foundation", "Основание", "Foundation", 2021, "сериал", ["space", "slow", "mind-power"], ["psychohistory"], "Основание"),
    f("silow", "Сило", "Silo", 2023, "сериал", ["slow", "mind-power", "dark"], ["the silo"], "Сило"),
    f("fallout-show", "Фоллаут", "Fallout", 2024, "сериал", ["tempo", "irony", "war"], ["war never changes"], "skip-dup"),
    f("last-of-us-ok", "Одни из нас", "The Last of Us", 2023, "сериал", ["dark", "family", "horror"], ["skip-dup"], "skip-dup"),
  ]);
})();
