(function () {
  var f = window.pofrazeFilm;
  if (!f) return;
  window.POFRAZE_FILMS = window.POFRAZE_FILMS.concat([
    f("mean-girls", "Дрянные девчонки", "Mean Girls", 2004, "фильм", ["comedy", "kids", "irony"], ["on wednesdays we wear pink", "you can't sit with us"], "Дрянные девчонки"),
    f("breakfast-club", "Клуб «Завтрак»", "The Breakfast Club", 1985, "фильм", ["kids", "slow", "family"], ["we're all pretty bizarre", "don't you forget about me"], "Клуб Завтрак"),
    f("ferris", "Феррис Бьюллер берёт выходной", "Ferris Bueller's Day Off", 1986, "фильм", ["comedy", "kids", "tempo"], ["life moves pretty fast", "bueller bueller"], "Феррис Бьюллер"),
    f("clueless", "Бестолковые", "Clueless", 1995, "фильм", ["comedy", "romance", "kids"], ["as if", "whatever"], "Бестолковые"),
    f("exorcist", "Изгоняющий дьявола", "The Exorcist", 1973, "фильм", ["horror", "dark", "slow"], ["the power of christ compels you", "your mother sucks cocks in hell"], "Изгоняющий дьявола"),
    f("halloween", "Хэллоуин", "Halloween", 1978, "фильм", ["horror", "slow", "dark"], ["was it the boogeyman", "michael myers"], "Хэллоуин"),
    f("elm-street", "Кошмар на улице Вязов", "A Nightmare on Elm Street", 1984, "фильм", ["horror", "dark", "mind-power"], ["whatever you do don't fall asleep", "freddy krueger"], "Кошмар на улице Вязов"),
    f("poltergeist", "Полтергейст", "Poltergeist", 1982, "фильм", ["horror", "family", "dark"], ["they're here"], "Полтергейст"),
    f("ghost", "Привидение", "Ghost", 1990, "фильм", ["romance", "fantasy", "slow"], ["ditto", "the pottery"], "Привидение"),
    f("dirty-dancing", "Грязные танцы", "Dirty Dancing", 1987, "фильм", ["romance", "family", "tempo"], ["nobody puts baby in a corner"], "Грязные танцы"),
    f("when-harry", "Когда Гарри встретил Салли", "When Harry Met Sally", 1989, "фильм", ["romance", "comedy", "slick-urban"], ["i'll have what she's having"], "Когда Гарри встретил Салли"),
    f("some-like", "В джазе только девушки", "Some Like It Hot", 1959, "фильм", ["comedy", "romance", "irony"], ["well nobody's perfect"], "В джазе только девушки"),
    f("graduate", "Выпускник", "The Graduate", 1967, "фильм", ["romance", "irony", "slow"], ["plastics", "mrs robinson"], "Выпускник"),
    f("midnight-cowboy", "Полуночный ковбой", "Midnight Cowboy", 1969, "фильм", ["slow", "street", "dark"], ["i'm walkin here"], "Полуночный ковбой"),
    f("network", "Телесеть", "Network", 1976, "фильм", ["ambition", "irony", "slick-urban"], ["i'm as mad as hell and i'm not going to take this anymore"], "Телесеть"),
    f("wall-street", "Уолл-стрит", "Wall Street", 1987, "фильм", ["ambition", "slick-urban", "crime"], ["greed is good", "greed for lack of a better word is good"], "Уолл-стрит"),
    f("waterfront", "В порту", "On the Waterfront", 1954, "фильм", ["crime", "ambition", "slow"], ["i coulda been a contender"], "В порту"),
    f("sunset-blvd", "Бульвар Сансет", "Sunset Boulevard", 1950, "фильм", ["dark", "ambition", "slow"], ["i am big it's the pictures that got small"], "Бульвар Сансет"),
    f("strangelove", "Доктор Стрейнджлав", "Dr. Strangelove", 1964, "фильм", ["war", "irony", "comedy"], ["gentlemen you can't fight in here this is the war room"], "Доктор Стрейнджлав"),
    f("princess-bride", "Принцесса-невеста", "The Princess Bride", 1987, "фильм", ["fantasy", "comedy", "romance"], ["as you wish", "inconceivable", "hello my name is inigo montoya you killed my father prepare to die"], "Принцесса-невеста"),
    f("holy-grail", "Монти Пайтон и Священный Грааль", "Monty Python and the Holy Grail", 1975, "фильм", ["comedy", "fantasy", "irony"], ["it's just a flesh wound", "ni"], "Монти Пайтон Священный Грааль"),
    f("life-brian", "Житие Брайана", "Life of Brian", 1979, "фильм", ["comedy", "irony", "war"], ["he's not the messiah he's a very naughty boy"], "Житие Брайана"),
    f("dead-poets", "Общество мёртвых поэтов", "Dead Poets Society", 1989, "фильм", ["ambition", "family", "slow"], ["o captain my captain", "carpe diem seize the day"], "Общество мёртвых поэтов"),
    f("good-will", "Умница Уилл Хантинг", "Good Will Hunting", 1997, "фильм", ["mind-power", "family", "slow"], ["how do you like them apples", "it's not your fault"], "Умница Уилл Хантинг"),
    f("rain-man", "Человек дождя", "Rain Man", 1988, "фильм", ["family", "slow", "comedy"], ["i'm an excellent driver", "uh oh"], "Человек дождя"),
    f("taken", "Заложница", "Taken", 2008, "фильм", ["tempo", "crime", "family"], ["i have a very particular set of skills"], "Заложница"),
    f("bourne", "Идентификация Борна", "The Bourne Identity", 2002, "фильм", ["tempo", "mind-power", "slick-urban"], ["i can tell you the license plate numbers of all six cars outside"], "Идентификация Борна"),
    f("ghostbusters", "Охотники за привидениями", "Ghostbusters", 1984, "фильм", ["comedy", "fantasy", "tempo"], ["who you gonna call"], "Охотники за привидениями"),
    f("gremlins", "Гремлины", "Gremlins", 1984, "фильм", ["horror", "comedy", "kids"], ["don't get them wet", "don't feed them after midnight"], "Гремлины"),
    f("beetlejuice", "Битлджус", "Beetlejuice", 1988, "фильм", ["comedy", "horror", "fantasy"], ["it's showtime"], "Битлджус"),
    f("karate-kid", "Парень-каратист", "The Karate Kid", 1984, "фильм", ["sport", "family", "kids"], ["wax on wax off"], "Парень-каратист"),
    f("fifth-element", "Пятый элемент", "The Fifth Element", 1997, "фильм", ["space", "tempo", "comedy"], ["multipass", "aziz light"], "Пятый элемент"),
    f("men-in-black", "Люди в чёрном", "Men in Black", 1997, "фильм", ["comedy", "space", "tempo"], ["you know the difference between you and me i make this look good"], "Люди в чёрном"),
    f("robocop", "Робокоп", "RoboCop", 1987, "фильм", ["tempo", "crime", "dark"], ["dead or alive you're coming with me"], "Робокоп"),
    f("thing", "Нечто", "The Thing", 1982, "фильм", ["horror", "space", "slow"], ["i know i'm human", "nobody trusts anybody now"], "Нечто"),
    f("trainspotting", "На игле", "Trainspotting", 1996, "фильм", ["chaotic", "street", "dark"], ["choose life"], "На игле"),
    f("american-psycho", "Американский психопат", "American Psycho", 2000, "фильм", ["dark", "slick-urban", "irony"], ["i have to return some videotapes"], "Американский психопат"),
    f("american-beauty", "Красота по-американски", "American Beauty", 1999, "фильм", ["irony", "family", "slow"], ["look closer"], "Красота по-американски"),
    f("eternal", "Вечное сияние чистого разума", "Eternal Sunshine of the Spotless Mind", 2004, "фильм", ["romance", "mind-power", "slow"], ["meet me in montauk"], "Вечное сияние чистого разума"),
    f("notting-hill", "Ноттинг Хилл", "Notting Hill", 1999, "фильм", ["romance", "comedy", "slick-urban"], ["i'm just a girl standing in front of a boy asking him to love her"], "Ноттинг Хилл"),
    f("love-actually", "Реальная любовь", "Love Actually", 2003, "фильм", ["romance", "comedy", "family"], ["to me you are perfect"], "Реальная любовь"),
    f("devil-prada", "Дьявол носит Prada", "The Devil Wears Prada", 2006, "фильм", ["ambition", "comedy", "slick-urban"], ["florals for spring groundbreaking"], "Дьявол носит Prada"),
    f("legally-blonde", "Блондинка в законе", "Legally Blonde", 2001, "фильм", ["comedy", "ambition", "romance"], ["what like it's hard"], "Блондинка в законе"),
    f("lotr-2", "Властелин колец: Две крепости", "The Lord of the Rings: The Two Towers", 2002, "фильм", ["fantasy", "war", "family"], ["shall i describe it to you or would you like me to find you a box"], "Властелин колец Две крепости"),
    f("lotr-3", "Властелин колец: Возвращение короля", "The Lord of the Rings: The Return of the King", 2003, "фильм", ["fantasy", "war", "family"], ["my friends you bow to no one", "for frodo"], "Властелин колец Возвращение короля"),
    f("hp2", "Гарри Поттер и Тайная комната", "Harry Potter and the Chamber of Secrets", 2002, "фильм", ["fantasy", "kids", "family"], ["i'll be in my bedroom making no noise and pretending that i don't exist"], "Гарри Поттер Тайная комната"),
    f("hp3", "Гарри Поттер и узник Азкабана", "Harry Potter and the Prisoner of Azkaban", 2004, "фильм", ["fantasy", "kids", "dark"], ["happiness can be found even in the darkest of times"], "Гарри Поттер узник Азкабана"),
    f("hp7", "Гарри Поттер и Дары Смерти: Часть 2", "Harry Potter and the Deathly Hallows – Part 2", 2011, "фильм", ["fantasy", "war", "family"], ["not my daughter you bitch"], "Гарри Поттер Дары Смерти"),
    f("casino-royale", "Казино Рояль", "Casino Royale", 2006, "фильм", ["slick-urban", "tempo", "romance"], ["do i look like i give a damn", "bond james bond"], "Казино Рояль"),
    f("skyfall", "007: Координаты «Скайфолл»", "Skyfall", 2012, "фильм", ["slick-urban", "dark", "tempo"], ["take the bloody shot"], "Скайфолл"),
    f("dr-no", "Доктор Ноу", "Dr. No", 1962, "фильм", ["slick-urban", "tempo", "romance"], ["bond james bond"], "Доктор Ноу"),
    f("return-jedi", "Возвращение джедая", "Return of the Jedi", 1983, "фильм", ["fantasy", "space", "family"], ["i am a jedi like my father before me"], "Возвращение джедая"),
    f("force-awakens", "Пробуждение силы", "Star Wars: The Force Awakens", 2015, "фильм", ["fantasy", "space", "tempo"], ["chewie we're home"], "Пробуждение силы"),
    f("rogue-one", "Изгой-один", "Rogue One", 2016, "фильм", ["war", "space", "dark"], ["rebellions are built on hope"], "Изгой-один"),
    f("majors", "Мажор", "", 2014, "сериал", ["crime", "slick-urban", "tempo"], ["игорь соколовский", "гибдд", "папа"], "Мажор"),
    f("trigger", "Триггер", "", 2020, "сериал", ["mind-power", "slow", "dark"], ["провокация", "психолог"], "Триггер"),
    f("epidemic", "Эпидемия", "", 2019, "сериал", ["horror", "slow", "family"], ["вирус", "москва вымирает"], "Эпидемия сериал"),
    f("pishcheblok", "Пищеблок", "", 2021, "сериал", ["horror", "kids", "soviet"], ["пионерлагерь", "вампиры"], "Пищеблок"),
    f("text-film", "Текст", "", 2019, "фильм", ["crime", "slick-urban", "dark"], ["переписка", "месть"], "Текст фильм"),
    f("ice-film", "Лёд", "", 2018, "фильм", ["romance", "sport", "family"], ["фигурное катание", "лёд"], "Лёд фильм"),
    f("crew-2016", "Экипаж", "", 2016, "фильм", ["tempo", "family", "space"], ["самолёт", "экипаж"], "Экипаж 2016"),
    f("groundhog", "День сурка", "Groundhog Day", 1993, "фильм", ["comedy", "romance", "irony"], ["i got you babe", "what if there is no tomorrow"], "День сурка"),
    f("truman", "Шоу Трумана", "The Truman Show", 1998, "фильм", ["mind-power", "irony", "slow"], ["good morning and in case i don't see you good afternoon good evening and good night"], "Шоу Трумана"),
    f("speed", "Скорость", "Speed", 1994, "фильм", ["tempo", "crime", "slick-urban"], ["pop quiz hotshot"], "Скорость"),
    f("mask", "Маска", "The Mask", 1994, "фильм", ["comedy", "fantasy", "chaotic"], ["ssssmokin", "somebody stop me"], "Маска"),
    f("ace-ventura", "Эйс Вентура: Розыск домашних животных", "Ace Ventura: Pet Detective", 1994, "фильм", ["comedy", "chaotic", "irony"], ["alrighty then"], "Эйс Вентура"),
    f("dumb-dumber", "Тупой и ещё тупее", "Dumb and Dumber", 1994, "фильм", ["comedy", "chaotic", "romance"], ["so you're telling me there's a chance"], "Тупой и ещё тупее"),
    f("hangover", "Мальчишник в Вегасе", "The Hangover", 2009, "фильм", ["comedy", "chaotic", "heist"], ["we lost doug", "what happens in vegas"], "Мальчишник в Вегасе"),
    f("superbad", "Суперперцы", "Superbad", 2007, "фильм", ["comedy", "kids", "chaotic"], ["you called me mclovin"], "Суперперцы"),
    f("anchorman", "Телеведущий", "Anchorman", 2004, "фильм", ["comedy", "irony", "slick-urban"], ["i'm kind of a big deal", "stay classy san diego"], "Телеведущий"),
    f("zoolander", "Образцовый самец", "Zoolander", 2001, "фильм", ["comedy", "irony", "slick-urban"], ["i'm pretty sure there's a lot more to life than being really really ridiculously good looking"], "Образцовый самец"),
    f("tropic-thunder", "Солдаты неудачи", "Tropic Thunder", 2008, "фильм", ["comedy", "war", "irony"], ["i know who i am i'm the dude playing the dude disguised as another dude"], "Солдаты неудачи"),
    f("step-brothers", "Сводные братья", "Step Brothers", 2008, "фильм", ["comedy", "family", "chaotic"], ["did we just become best friends"], "Сводные братья"),
    f("ten-things", "10 причин моей ненависти", "10 Things I Hate About You", 1999, "фильм", ["comedy", "romance", "kids"], ["i burn i pine i perish"], "10 причин моей ненависти"),
    f("juno", "Джуно", "Juno", 2007, "фильм", ["comedy", "romance", "kids"], ["honest to blog"], "Джуно"),
    f("little-sunshine", "Маленькая мисс Счастье", "Little Miss Sunshine", 2006, "фильм", ["comedy", "family", "irony"], ["you do what you gotta do"], "Маленькая мисс Счастье"),
    f("hunger-games", "Голодные игры", "The Hunger Games", 2012, "фильм", ["tempo", "war", "kids"], ["may the odds be ever in your favor"], "Голодные игры"),
    f("twilight", "Сумерки", "Twilight", 2008, "фильм", ["romance", "fantasy", "kids"], ["and so the lion fell in love with the lamb"], "Сумерки"),
    f("narnia", "Хроники Нарнии: Лев, колдунья и волшебный шкаф", "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe", 2005, "фильм", ["fantasy", "kids", "family"], ["once a king or queen in narnia always a king or queen"], "Хроники Нарнии"),
    f("paddington", "Приключения Паддингтона", "Paddington", 2014, "фильм", ["kids", "comedy", "family"], ["please look after this bear"], "Паддингтон"),
    f("paddington-2", "Приключения Паддингтона 2", "Paddington 2", 2017, "фильм", ["kids", "comedy", "family"], ["if we're kind and polite the world will be right"], "Паддингтон 2"),
    f("hp4", "Гарри Поттер и Кубок огня", "Harry Potter and the Goblet of Fire", 2005, "фильм", ["fantasy", "kids", "tempo"], ["i solemnly swear that i am up to no good"], "Гарри Поттер Кубок огня"),
    f("hp5", "Гарри Поттер и Орден Феникса", "Harry Potter and the Order of the Phoenix", 2007, "фильм", ["fantasy", "kids", "dark"], ["i must not tell lies"], "Гарри Поттер Орден Феникса"),
    f("winter-soldier", "Первый мститель: Другая война", "Captain America: The Winter Soldier", 2014, "фильм", ["tempo", "war", "slick-urban"], ["on your left"], "Первый мститель Другая война"),
    f("thor-ragnarok", "Тор: Рагнарёк", "Thor: Ragnarok", 2017, "фильм", ["comedy", "fantasy", "tempo"], ["he's a friend from work"], "Тор Рагнарёк"),
    f("doctor-strange", "Доктор Стрэндж", "Doctor Strange", 2016, "фильм", ["fantasy", "mind-power", "tempo"], ["i've come to bargain"], "Доктор Стрэндж"),
    f("civil-war-mcu", "Первый мститель: Противостояние", "Captain America: Civil War", 2016, "фильм", ["tempo", "family", "war"], ["so was i"], "Противостояние"),
    f("deadpool-wolverine", "Дэдпул и Росомаха", "Deadpool & Wolverine", 2024, "фильм", ["comedy", "tempo", "irony"], ["welcome to the mcu pal", "good to see you again"], "Дэдпул и Росомаха"),
    f("inside-out-2", "Головоломка 2", "Inside Out 2", 2024, "фильм", ["kids", "mind-power", "comedy"], ["i'm anxiety"], "Головоломка 2"),
    f("v-vendetta", "V значит Вендетта", "V for Vendetta", 2005, "фильм", ["war", "mind-power", "dark"], ["remember remember the fifth of november", "people should not be afraid of their governments"], "V значит Вендетта"),
    f("casino-scorcese", "Казино", "Casino", 1995, "фильм", ["crime", "ambition", "slick-urban"], ["when you love someone you gotta trust them"], "Казино Скорсезе"),
    f("good-bad-ugly", "Хороший, плохой, злой", "The Good, the Bad and the Ugly", 1966, "фильм", ["war", "tempo", "irony"], ["when you have to shoot shoot don't talk"], "Хороший плохой злой"),
    f("unforgiven", "Непрощённый", "Unforgiven", 1992, "фильм", ["dark", "slow", "war"], ["deserve's got nothing to do with it"], "Непрощённый"),
    f("irishman", "Ирландец", "The Irishman", 2019, "фильм", ["crime", "slow", "family"], ["it's what it is"], "Ирландец"),
    f("donnie-brasco", "Донни Браско", "Donnie Brasco", 1997, "фильм", ["crime", "slow", "slick-urban"], ["fuhgeddaboudit"], "Донни Браско"),
    f("lethal-weapon", "Смертельное оружие", "Lethal Weapon", 1987, "фильм", ["tempo", "crime", "comedy"], ["i'm too old for this"], "Смертельное оружие"),
    f("commando", "Коммандо", "Commando", 1985, "фильм", ["tempo", "war", "comedy"], ["let off some steam bennett"], "Коммандо"),
    f("total-recall", "Вспомнить всё", "Total Recall", 1990, "фильм", ["tempo", "space", "mind-power"], ["get your ass to mars"], "Вспомнить всё"),
    f("nobody", "Никто", "Nobody", 2021, "фильм", ["tempo", "crime", "family"], ["i'm just a dad"], "Никто"),
    f("soul", "Душа", "Soul", 2020, "фильм", ["kids", "mind-power", "comedy"], ["jazz is not just music"], "Душа"),
    f("madagascar", "Мадагаскар", "Madagascar", 2005, "фильм", ["kids", "comedy", "family"], ["you didn't think i was going to eat you did you"], "Мадагаскар"),
    f("ice-age", "Ледниковый период", "Ice Age", 2002, "фильм", ["kids", "comedy", "family"], ["i'm not fat it's all this fur"], "Ледниковый период"),
    f("pokrovskie", "Покровские ворота", "", 1982, "фильм", ["soviet", "comedy", "romance"], ["а вы батенька бонвиван"], "Покровские ворота"),
    f("station-two", "Вокзал для двоих", "", 1982, "фильм", ["soviet", "romance", "slow"], ["вокзал для двоих"], "Вокзал для двоих"),
    f("courier", "Курьер", "", 1986, "фильм", ["soviet", "comedy", "romance"], ["курьер"], "Курьер"),
    f("samogon", "Самогонщики", "", 1961, "фильм", ["soviet", "comedy", "heist"], ["трус балбес бывалый", "самогон"], "Самогонщики"),
    f("igla", "Игла", "", 1988, "фильм", ["soviet", "street", "dark"], ["мы вас любим", "виктор цой"], "Игла"),
    f("mir-druzhba", "Мир! Дружба! Жвачка!", "", 2020, "сериал", ["comedy", "kids", "soviet"], ["жвачка", "девяностые"], "Мир Дружба Жвачка"),
    f("zhuki", "Жуки", "", 2019, "сериал", ["comedy", "street", "irony"], ["калининград", "жуки"], "Жуки"),
    f("chikatilo", "Чикатило", "", 2021, "сериал", ["crime", "dark", "slow"], ["ростовский маньяк"], "Чикатило"),
  ]);
})();
