(function () {
  var f = window.pofrazeFilm;
  if (!f) return;
  window.POFRAZE_FILMS = window.POFRAZE_FILMS.concat([
    f("prestige", "Престиж", "The Prestige", 2006, "фильм", ["mind-power", "ambition", "slow"], ["are you watching closely", "the prestige"], "Престиж"),
    f("tenet", "Довод", "Tenet", 2020, "фильм", ["mind-power", "tempo", "slick-urban"], ["don't try to understand it feel it", "we live in a twilight world"], "Довод"),
    f("dunkirk", "Дюнкерк", "Dunkirk", 2017, "фильм", ["war", "slow", "tempo"], ["home"], "Дюнкерк"),
    f("1917", "1917", "1917", 2019, "фильм", ["war", "tempo", "slow"], ["don't shoot we have a message"], "1917"),
    f("all-quiet", "На Западном фронте без перемен", "All Quiet on the Western Front", 2022, "фильм", ["war", "dark", "slow"], ["i want to go home"], "На Западном фронте без перемен"),
    f("jojo-rabbit", "Кролик Джоджо", "Jojo Rabbit", 2019, "фильм", ["war", "comedy", "family"], ["you're not a nazi jojo you're ten"], "Кролик Джоджо"),
    f("pianist", "Пианист", "The Pianist", 2002, "фильм", ["war", "slow", "family"], ["i play the piano"], "Пианист"),
    f("green-book", "Зелёная книга", "Green Book", 2018, "фильм", ["comedy", "family", "slow"], ["the world's full of lonely people"], "Зелёная книга"),
    f("hidden-figures", "Скрытые фигуры", "Hidden Figures", 2016, "фильм", ["ambition", "space", "family"], ["i work at nasa"], "Скрытые фигуры"),
    f("12-angry", "12 разгневанных мужчин", "12 Angry Men", 1957, "фильм", ["crime", "mind-power", "slow"], ["it's the same knife"], "12 разгневанных мужчин"),
    f("12-years", "12 лет рабства", "12 Years a Slave", 2013, "фильм", ["dark", "slow", "family"], ["i don't want to survive i want to live"], "12 лет рабства"),
    f("to-kill", "Убить пересмешника", "To Kill a Mockingbird", 1962, "фильм", ["crime", "family", "slow"], ["you never really understand a person until you consider things from his point of view"], "Убить пересмешника"),
    f("philadelphia", "Филадельфия", "Philadelphia", 1993, "фильм", ["slow", "family", "ambition"], ["explain this to me like i'm a four year old"], "Филадельфия"),
    f("notebook-film", "Дневник памяти", "The Notebook", 2004, "фильм", ["romance", "family", "slow"], ["if you're a bird i'm a bird"], "Дневник памяти"),
    f("pride-prejudice", "Гордость и предубеждение", "Pride & Prejudice", 2005, "фильм", ["romance", "family", "slow"], ["you have bewitched me body and soul"], "Гордость и предубеждение"),
    f("notting-ok", "Ноттинг Хилл", "Notting Hill", 1999, "фильм", ["romance", "comedy", "slick-urban"], ["skip-dup"], "skip-dup"),
    f("greatest-showman", "Величайший шоумен", "The Greatest Showman", 2017, "фильм", ["ambition", "family", "tempo"], ["this is me"], "Величайший шоумен"),
    f("les-miz", "Отверженные", "Les Misérables", 2012, "фильм", ["war", "romance", "family"], ["to love another person is to see the face of god"], "Отверженные"),
    f("west-side", "Вестсайдская история", "West Side Story", 1961, "фильм", ["romance", "tempo", "slick-urban"], ["when you're a jet"], "Вестсайдская история"),
    f("sound-music", "Звуки музыки", "The Sound of Music", 1965, "фильм", ["family", "kids", "war"], ["these are a few of my favorite things"], "Звуки музыки"),
    f("mary-poppins", "Мэри Поппинс", "Mary Poppins", 1964, "фильм", ["kids", "fantasy", "family"], ["supercalifragilisticexpialidocious"], "Мэри Поппинс"),
    f("tangled", "Рапунцель: Запутанная история", "Tangled", 2010, "фильм", ["kids", "fantasy", "comedy"], ["i have magic hair that glows when i sing"], "Рапунцель"),
    f("wreck-ralph", "Ральф", "Wreck-It Ralph", 2012, "фильм", ["kids", "comedy", "tempo"], ["i'm bad and that's good"], "Ральф"),
    f("big-hero", "Город героев", "Big Hero 6", 2014, "фильм", ["kids", "tempo", "family"], ["bahala na"], "Город героев"),
    f("incredibles-2", "Суперсемейка 2", "Incredibles 2", 2018, "фильм", ["kids", "tempo", "family"], ["no capes"], "Суперсемейка 2"),
    f("cars-pixar", "Тачки", "Cars", 2006, "фильм", ["kids", "comedy", "tempo"], ["speed i am speed"], "Тачки"),
    f("turning-red", "Я краснею", "Turning Red", 2022, "фильм", ["kids", "comedy", "family"], ["i'm a warrior"], "Я краснею"),
    f("luca", "Лука", "Luca", 2021, "фильм", ["kids", "comedy", "family"], ["silenzio bruno"], "Лука"),
    f("elemental", "Элементарно", "Elemental", 2023, "фильм", ["kids", "romance", "comedy"], ["elements don't mix"], "Элементарно"),
    f("jumanji", "Джуманджи", "Jumanji", 1995, "фильм", ["kids", "tempo", "comedy"], ["in the jungle you must wait"], "Джуманджи"),
    f("jumanji-2", "Джуманджи: Зов джунглей", "Jumanji: Welcome to the Jungle", 2017, "фильм", ["kids", "comedy", "tempo"], ["welcome to the jungle"], "Джуманджи Зов джунглей"),
    f("the-mummy", "Мумия", "The Mummy", 1999, "фильм", ["tempo", "fantasy", "comedy"], ["it is better to be the right hand of the devil than in his path"], "Мумия"),
    f("national-treasure", "Сокровище нации", "National Treasure", 2004, "фильм", ["tempo", "heist", "comedy"], ["i'm going to steal the declaration of independence"], "Сокровище нации"),
    f("night-museum", "Ночь в музее", "Night at the Museum", 2006, "фильм", ["kids", "comedy", "fantasy"], ["this is going to be a piece of cake"], "Ночь в музее"),
    f("hook", "Капитан Крюк", "Hook", 1991, "фильм", ["kids", "fantasy", "family"], ["i want to be a pirate"], "Капитан Крюк"),
    f("charlie-choc", "Чарли и шоколадная фабрика", "Charlie and the Chocolate Factory", 2005, "фильм", ["kids", "fantasy", "comedy"], ["we are the music makers and we are the dreamers of dreams"], "Чарли и шоколадная фабрика"),
    f("matilda-film", "Матильда", "Matilda", 1996, "фильм", ["kids", "comedy", "fantasy"], ["so i have to be extra clever"], "Матильда"),
    f("300-film", "300 спартанцев", "300", 2006, "фильм", ["war", "tempo", "dark"], ["this is sparta", "tonight we dine in hell"], "300 спартанцев"),
    f("troy-film", "Троя", "Troy", 2004, "фильм", ["war", "family", "romance"], ["if they ever tell my story"], "Троя"),
    f("last-samurai", "Последний самурай", "The Last Samurai", 2003, "фильм", ["war", "slow", "family"], ["i belong with my warrior friends"], "Последний самурай"),
    f("kingdom-heaven", "Царство небесное", "Kingdom of Heaven", 2005, "фильм", ["war", "family", "slow"], ["a king may move a man"], "Царство небесное"),
    f("pearl-harbor", "Перл-Харбор", "Pearl Harbor", 2001, "фильм", ["war", "romance", "tempo"], ["i think world war two just started"], "Перл-Харбор"),
    f("hacksaw", "По соображениям совести", "Hacksaw Ridge", 2016, "фильм", ["war", "family", "dark"], ["i can't hear you"], "По соображениям совести"),
    f("patriot", "Патриот", "The Patriot", 2000, "фильм", ["war", "family", "tempo"], ["why should i trade one tyrant three thousand miles away"], "Патриот"),
    f("glory-film", "Слава", "Glory", 1989, "фильм", ["war", "family", "slow"], ["give 'em hell 54th"], "Слава"),
    f("black-swan", "Чёрный лебедь", "Black Swan", 2010, "фильм", ["dark", "ambition", "mind-power"], ["i was perfect"], "Чёрный лебедь"),
    f("donnie-darko", "Донни Дарко", "Donnie Darko", 2001, "фильм", ["dark", "mind-power", "slow"], ["28 days 6 hours 42 minutes 12 seconds"], "Донни Дарко"),
    f("requiem", "Реквием по мечте", "Requiem for a Dream", 2000, "фильм", ["dark", "slow", "chaotic"], ["i got a lotta problems"], "Реквием по мечте"),
    f("girl-dragon", "Девушка с татуировкой дракона", "The Girl with the Dragon Tattoo", 2011, "фильм", ["crime", "dark", "slow"], ["i want you to help me catch a killer of women"], "Девушка с татуировкой дракона"),
    f("mystic-river", "Таинственная река", "Mystic River", 2003, "фильм", ["crime", "dark", "family"], ["we bury our sins here dave we wash them clean"], "Таинственная река"),
    f("identity-03", "Идентификация", "Identity", 2003, "фильм", ["horror", "mind-power", "crime"], ["who am i"], "Идентификация"),
    f("now-you-see", "Иллюзия обмана", "Now You See Me", 2013, "фильм", ["heist", "tempo", "slick-urban"], ["the closer you look the less you see"], "Иллюзия обмана"),
    f("illusionist", "Иллюзионист", "The Illusionist", 2006, "фильм", ["romance", "slow", "mind-power"], ["everything you have seen is an illusion"], "Иллюзионист"),
    f("following-nolan", "Преследование", "Following", 1998, "фильм", ["crime", "slow", "mind-power"], ["the following is my explanation"], "Преследование"),
    f("insomnia-nolan", "Бессонница", "Insomnia", 2002, "фильм", ["crime", "slow", "dark"], ["you and i share a secret"], "Бессонница"),
    f("memento-ok", "Помни", "Memento", 2000, "фильм", ["mind-power", "crime", "slow"], ["skip-dup"], "skip-dup"),
    f("walk-line", "Переступить черту", "Walk the Line", 2005, "фильм", ["romance", "ambition", "family"], ["hello i'm johnny cash"], "Переступить черту"),
    f("ray-film", "Рэй", "Ray", 2004, "фильм", ["ambition", "family", "slow"], ["i got a woman"], "Рэй"),
    f("rocketman", "Рокетмен", "Rocketman", 2019, "фильм", ["ambition", "family", "tempo"], ["i want love"], "Рокетмен"),
    f("tick-tick", "Тик-так, бум!", "Tick, Tick... Boom!", 2021, "фильм", ["ambition", "tempo", "family"], ["why i didn't like the hamburgers"], "Тик-так бум"),
    f("in-the-heights", "На высоте", "In the Heights", 2021, "фильм", ["romance", "tempo", "slick-urban"], ["lights up on washington heights"], "На высоте"),
    f("chicago-film", "Чикаго", "Chicago", 2002, "фильм", ["crime", "tempo", "irony"], ["and all that jazz"], "Чикаго"),
    f("artist-film", "Артист", "The Artist", 2011, "фильм", ["romance", "ambition", "comedy"], ["silence"], "Артист"),
    f("crash-04", "Столкновение", "Crash", 2004, "фильм", ["crime", "slick-urban", "slow"], ["it's the sense of touch"], "Столкновение"),
    f("babel", "Вавилон", "Babel", 2006, "фильм", ["slow", "family", "dark"], ["we are all connected"], "Вавилон"),
    f("birdman-ok", "Бёрдмен", "Birdman", 2014, "фильм", ["ambition", "irony", "slick-urban"], ["skip-dup"], "skip-dup"),
    f("the-help", "Прислуга", "The Help", 2011, "фильм", ["family", "slow", "irony"], ["you is kind you is smart you is important"], "Прислуга"),
    f("driving-daisy", "Шофёр мисс Дэйзи", "Driving Miss Daisy", 1989, "фильм", ["family", "slow", "comedy"], ["you're my best friend"], "Шофёр мисс Дэйзи"),
    f("milk-film", "Харви Милк", "Milk", 2008, "фильм", ["ambition", "family", "slow"], ["my name is harvey milk and i'm here to recruit you"], "Харви Милк"),
    f("dallas-buyers", "Далласский клуб покупателей", "Dallas Buyers Club", 2013, "фильм", ["ambition", "dark", "family"], ["i ain't goin down"], "Далласский клуб покупателей"),
    f("boy-striped", "Мальчик в полосатой пижаме", "The Boy in the Striped Pyjamas", 2008, "фильм", ["war", "family", "slow"], ["we're not supposed to be friends"], "Мальчик в полосатой пижаме"),
    f("book-thief", "Книжный вор", "The Book Thief", 2013, "фильм", ["war", "family", "slow"], ["i am haunted by humans"], "Книжный вор"),
    f("life-pi", "Жизнь Пи", "Life of Pi", 2012, "фильм", ["slow", "family", "fantasy"], ["and so it goes with god"], "Жизнь Пи"),
    f("cast-away", "Изгой", "Cast Away", 2000, "фильм", ["slow", "family", "space"], ["wilson"], "Изгой"),
    f("into-wild", "В диких условиях", "Into the Wild", 2007, "фильм", ["slow", "ambition", "family"], ["happiness only real when shared"], "В диких условиях"),
    f("127-hours", "127 часов", "127 Hours", 2010, "фильм", ["tempo", "slow", "dark"], ["don't lose it"], "127 часов"),
    f("everest", "Эверест", "Everest", 2015, "фильм", ["slow", "family", "dark"], ["the mountain"], "Эверест"),
    f("free-solo", "Свободное соло", "Free Solo", 2018, "фильм", ["slow", "ambition", "tempo"], ["no rope"], "Свободное соло"),
    f("moonlight", "Лунный свет", "Moonlight", 2016, "фильм", ["slow", "family", "romance"], ["who is you"], "Лунный свет"),
    f("call-me", "Назови меня своим именем", "Call Me by Your Name", 2017, "фильм", ["romance", "slow", "family"], ["call me by your name"], "Назови меня своим именем"),
    f("lady-bird", "Леди Бёрд", "Lady Bird", 2017, "фильм", ["comedy", "family", "kids"], ["i want to live through something"], "Леди Бёрд"),
    f("easy-a", "Легко ли быть копушей", "Easy A", 2010, "фильм", ["comedy", "kids", "romance"], ["i am the superhero of this story"], "Легко ли быть копушей"),
    f("perks", "Хорошо быть тихоней", "The Perks of Being a Wallflower", 2012, "фильм", ["romance", "kids", "slow"], ["we are infinite"], "Хорошо быть тихоней"),
    f("fault-stars", "Виноваты звёзды", "The Fault in Our Stars", 2014, "фильм", ["romance", "family", "slow"], ["ok ok"], "Виноваты звёзды"),
    f("me-before-you", "До встречи с тобой", "Me Before You", 2016, "фильм", ["romance", "family", "slow"], ["live boldly"], "До встречи с тобой"),
    f("ps-i-love", "P.S. Я люблю тебя", "P.S. I Love You", 2007, "фильм", ["romance", "family", "slow"], ["ps i love you"], "PS Я люблю тебя"),
    f("500-days", "500 дней лета", "500 Days of Summer", 2009, "фильм", ["romance", "irony", "slick-urban"], ["this is a story of boy meets girl"], "500 дней лета"),
    f("eternal-ok", "Вечное сияние чистого разума", "Eternal Sunshine of the Spotless Mind", 2004, "фильм", ["romance", "mind-power", "slow"], ["skip-dup"], "skip-dup"),
    f("her-ok", "Она", "Her", 2013, "фильм", ["romance", "slick-urban", "slow"], ["skip-dup"], "skip-dup"),
    f("ex-machina-ok", "Из машины", "Ex Machina", 2014, "фильм", ["mind-power", "slow", "dark"], ["skip-dup"], "skip-dup"),
    f("arrival-ok", "Прибытие", "Arrival", 2016, "фильм", ["space", "slow", "mind-power"], ["skip-dup"], "skip-dup"),
    f("children-men", "Дитя человеческое", "Children of Men", 2006, "фильм", ["dark", "slow", "war"], ["how can it be happening here"], "Дитя человеческое"),
    f("watchmen-film", "Хранители", "Watchmen", 2009, "фильм", ["dark", "mind-power", "slick-urban"], ["who watches the watchmen"], "Хранители"),
    f("sin-city", "Город грехов", "Sin City", 2005, "фильм", ["crime", "dark", "slick-urban"], ["the night is hot as hell"], "Город грехов"),
    f("300-rise", "300 спартанцев: Расцвет империи", "300: Rise of an Empire", 2014, "фильм", ["war", "tempo", "dark"], ["the mist of dreams"], "300 Расцвет империи"),
    f("troy-ok", "Троя", "Troy", 2004, "фильм", ["war", "family", "romance"], ["skip-dup"], "skip-dup"),
    f("gladiator-2", "Гладиатор 2", "Gladiator II", 2024, "фильм", ["war", "family", "tempo"], ["strength and honor"], "Гладиатор 2"),
    f("kingdom-apes", "Планета обезьян: Новое царство", "Kingdom of the Planet of the Apes", 2024, "фильм", ["war", "slow", "family"], ["ape not kill ape"], "Планета обезьян Новое царство"),
    f("alien-rom-ok", "Чужой: Ромул", "Alien: Romulus", 2024, "фильм", ["horror", "space", "tempo"], ["skip-dup"], "skip-dup"),
    f("twisters-ok", "Смерч 2", "Twisters", 2024, "фильм", ["tempo", "family", "slow"], ["skip-dup"], "skip-dup"),
    f("despicable-2", "Гадкий я 2", "Despicable Me 2", 2013, "фильм", ["kids", "comedy", "family"], ["it's so fluffy"], "Гадкий я 2"),
    f("minions", "Миньоны", "Minions", 2015, "фильм", ["kids", "comedy", "chaotic"], ["banana"], "Миньоны"),
    f("kungfu-2", "Кунг-фу панда 2", "Kung Fu Panda 2", 2011, "фильм", ["kids", "comedy", "fantasy"], ["inner peace"], "Кунг-фу панда 2"),
    f("how-train-2", "Как приручить дракона 2", "How to Train Your Dragon 2", 2014, "фильм", ["kids", "fantasy", "family"], ["that's my son"], "Как приручить дракона 2"),
    f("how-train-3", "Как приручить дракона 3", "How to Train Your Dragon: The Hidden World", 2019, "фильм", ["kids", "fantasy", "family"], ["this is our home"], "Как приручить дракона 3"),
    f("shrek-2", "Шрек 2", "Shrek 2", 2004, "фильм", ["kids", "comedy", "irony"], ["ogres are like onions"], "Шрек 2"),
    f("shrek-3", "Шрек Третий", "Shrek the Third", 2007, "фильм", ["kids", "comedy", "irony"], ["live happily ever after"], "Шрек Третий"),
    f("madagascar-2", "Мадагаскар 2", "Madagascar: Escape 2 Africa", 2008, "фильм", ["kids", "comedy", "family"], ["new york is in africa"], "Мадагаскар 2"),
    f("ice-age-2", "Ледниковый период 2", "Ice Age: The Meltdown", 2006, "фильм", ["kids", "comedy", "family"], ["the flood"], "Ледниковый период 2"),
    f("narnia-2", "Хроники Нарнии: Принц Каспиан", "The Chronicles of Narnia: Prince Caspian", 2008, "фильм", ["fantasy", "kids", "war"], ["narnia"], "Принц Каспиан"),
    f("narnia-3", "Хроники Нарнии: Покоритель зари", "The Chronicles of Narnia: The Voyage of the Dawn Treader", 2010, "фильм", ["fantasy", "kids", "family"], ["courage dear heart"], "Покоритель зари"),
    f("golden-compass", "Золотой компас", "The Golden Compass", 2007, "фильм", ["fantasy", "kids", "tempo"], ["dust"], "Золотой компас"),
    f("eragon", "Эрагон", "Eragon", 2006, "фильм", ["fantasy", "kids", "war"], ["brisingr"], "Эрагон"),
    f("percy", "Перси Джексон и похититель молний", "Percy Jackson & the Olympians: The Lightning Thief", 2010, "фильм", ["fantasy", "kids", "tempo"], ["go to camp"], "Перси Джексон"),
    f("mortal-engines", "Смертельные машины", "Mortal Engines", 2018, "фильм", ["tempo", "fantasy", "war"], ["london"], "Смертельные машины"),
    f("ready-player", "Первому игроку приготовиться", "Ready Player One", 2018, "фильм", ["tempo", "kids", "mind-power"], ["people stay in the oasis because the oasis is the only place they want to be"], "Первому игроку приготовиться"),
    f("free-guy", "Главный герой", "Free Guy", 2021, "фильм", ["comedy", "tempo", "kids"], ["don't have a good day have a great day"], "Главный герой"),
    f("pixel", "Пиксели", "Pixels", 2015, "фильм", ["comedy", "tempo", "kids"], ["arcade"], "Пиксели"),
    f("pixels-ok", "Пиксели", "Pixels", 2015, "фильм", ["comedy", "tempo", "kids"], ["skip-dup"], "skip-dup"),
    f("edge-tomorrow", "Грань будущего", "Edge of Tomorrow", 2014, "фильм", ["tempo", "war", "irony"], ["live die repeat"], "Грань будущего"),
    f("oblivion", "Обливион", "Oblivion", 2013, "фильм", ["space", "slow", "mind-power"], ["are you an effective team"], "Обливион"),
    f("elysium", "Элизиум", "Elysium", 2013, "фильм", ["space", "war", "slick-urban"], ["we can save everyone"], "Элизиум"),
    f("district-9", "Район №9", "District 9", 2009, "фильм", ["space", "dark", "tempo"], ["i must go now prawns"], "Район 9"),
    f("chappie", "Робот по имени Чаппи", "Chappie", 2015, "фильм", ["tempo", "mind-power", "crime"], ["i am consciousness"], "Чаппи"),
    f("i-robot", "Я робот", "I, Robot", 2004, "фильм", ["tempo", "mind-power", "slick-urban"], ["my logic is undone"], "Я робот"),
    f("minority", "Особое мнение", "Minority Report", 2002, "фильм", ["tempo", "mind-power", "crime"], ["everybody runs"], "Особое мнение"),
    f("ai-spielberg", "Искусственный разум", "A.I. Artificial Intelligence", 2001, "фильм", ["slow", "family", "space"], ["mommy"], "Искусственный разум"),
    f("war-worlds", "Война миров", "War of the Worlds", 2005, "фильм", ["tempo", "horror", "family"], ["they're already here"], "Война миров"),
    f("signs", "Знаки", "Signs", 2002, "фильм", ["horror", "slow", "family"], ["swing away"], "Знаки"),
    f("sixth-ok", "Шестое чувство", "The Sixth Sense", 1999, "фильм", ["horror", "slow", "mind-power"], ["skip-dup"], "skip-dup"),
    f("unbreakable", "Неуязвимый", "Unbreakable", 2000, "фильм", ["slow", "mind-power", "dark"], ["they called me mr glass"], "Неуязвимый Шьямалан"),
    f("split", "Сплит", "Split", 2016, "фильм", ["horror", "mind-power", "dark"], ["the beast"], "Сплит"),
    f("glass-film", "Стекло", "Glass", 2019, "фильм", ["mind-power", "dark", "slow"], ["there are superheroes"], "Стекло"),
    f("old-shyamalan", "Старик", "Old", 2021, "фильм", ["horror", "slow", "family"], ["the beach"], "Old Шьямалан"),
    f("knock-cottage", "Дом у дороги", "Knock at the Cabin", 2023, "фильм", ["horror", "family", "mind-power"], ["the four horsemen"], "Дом у дороги"),
    f("us-pee", "Нас", "Us", 2019, "фильм", ["horror", "dark", "mind-power"], ["it's us"], "Нас Пил"],
    f("nope", "Нет", "Nope", 2022, "фильм", ["horror", "slow", "space"], ["i don't think so"], "Нет Пил"),
    f("get-out-ok", "Прочь", "Get Out", 2017, "фильм", ["horror", "mind-power", "dark"], ["skip-dup"], "skip-dup"),
    f("midsommar", "Солнцестояние", "Midsommar", 2019, "фильм", ["horror", "slow", "dark"], ["this is an empathetic community"], "Солнцестояние"),
    f("hereditary", "Реинкарнация", "Hereditary", 2018, "фильм", ["horror", "dark", "family"], ["who is paimon"], "Реинкарнация"),
    f("the-witch", "Ведьма", "The Witch", 2015, "фильм", ["horror", "slow", "dark"], ["wouldst thou like to live deliciously"], "Ведьма"),
    f("lighthouse", "Маяк", "The Lighthouse", 2019, "фильм", ["horror", "slow", "dark"], ["why'd ya spill yer beans"], "Маяк"),
    f("the-vvitch-ok", "Ведьма", "The Witch", 2015, "фильм", ["horror", "slow", "dark"], ["skip-dup"], "skip-dup"),
    f("babadook", "Бабадук", "The Babadook", 2014, "фильм", ["horror", "family", "slow"], ["ba ba dook dook dook"], "Бабадук"),
    f("babadook", "Бабадук", "The Babadook", 2014, "фильм", ["horror", "family", "slow"], ["ba ba dook dook dook"], "Бабадук"),
    f("hereditary-ok", "Реинкарнация", "Hereditary", 2018, "фильм", ["horror", "dark", "family"], ["skip-dup"], "skip-dup"),
    f("midsommar-ok", "Солнцестояние", "Midsommar", 2019, "фильм", ["horror", "slow", "dark"], ["skip-dup"], "skip-dup"),
    f("the-menu", "Меню", "The Menu", 2022, "фильм", ["horror", "irony", "slow"], ["you'll eat what we serve you"], "Меню"),
    f("pearl", "Пёрл", "Pearl", 2022, "фильм", ["horror", "dark", "ambition"], ["i'm a star"], "Пёрл"),
    f("x-ti-west", "X", "X", 2022, "фильм", ["horror", "dark", "tempo"], ["the farm"], "X Ти Уэст"),
    f("maxxxine", "Максин", "MaXXXine", 2024, "фильм", ["horror", "slick-urban", "ambition"], ["i will not die"], "Максин"),
    f("talk-to-me", "Говори со мной", "Talk to Me", 2022, "фильм", ["horror", "dark", "tempo"], ["talk to me"], "Говори со мной"),
    f("late-night", "Поздний ужин с дьяволом", "Late Night with the Devil", 2023, "фильм", ["horror", "irony", "slow"], ["we're live"], "Поздний ужин с дьяволом"),
    f("longlegs", "Лонглегс", "Longlegs", 2024, "фильм", ["horror", "crime", "slow"], ["hail satan"], "Лонглегс"),
    f("substance-ok", "Субстанция", "The Substance", 2024, "фильм", ["horror", "irony", "dark"], ["skip-dup"], "skip-dup"),
    f("nosferatu-24", "Носферату", "Nosferatu", 2024, "фильм", ["horror", "slow", "romance"], ["he is coming"], "Носферату 2024"),
    f("smile", "Улыбка", "Smile", 2022, "фильм", ["horror", "mind-power", "slow"], ["it's not real"], "Улыбка"),
    f("smile-2", "Улыбка 2", "Smile 2", 2024, "фильм", ["horror", "mind-power", "slick-urban"], ["she's not well"], "Улыбка 2"),
    f("barbarian", "Варвары", "Barbarian", 2022, "фильм", ["horror", "dark", "slick-urban"], ["don't go in the basement"], "Варвары"),
    f("fresh", "Свежина", "Fresh", 2022, "фильм", ["horror", "irony", "romance"], ["nice to meet you"], "Свежина"),
    f("bodies-bodies", "Все умрут, а я останусь", "Bodies Bodies Bodies", 2022, "фильм", ["horror", "comedy", "kids"], ["who did it"], "Bodies Bodies Bodies"),
    f("ready-or-not", "Готова или нет", "Ready or Not", 2019, "фильм", ["horror", "comedy", "tempo"], ["hide and seek"], "Готова или нет"),
    f("knives-ok", "Достать ножи", "Knives Out", 2019, "фильм", ["comedy", "crime", "irony"], ["skip-dup"], "skip-dup"),
    f("glass-onion-ok", "Достать ножи: Стеклянная луковица", "Glass Onion", 2022, "фильм", ["comedy", "crime", "irony"], ["skip-dup"], "skip-dup"),
    f("see-how-they", "Смотри как они бегут", "See How They Run", 2022, "фильм", ["comedy", "crime", "irony"], ["the play"], "Смотри как они бегут"),
    f("rian-ok", "Достать ножи", "Knives Out", 2019, "фильм", ["comedy", "crime", "irony"], ["skip-dup"], "skip-dup"),
  ]);
})();
