(function () {
  var f = window.pofrazeFilm;
  window.POFRAZE_FILMS = window.POFRAZE_FILMS.concat([
    f("ted-lasso", "Тед Лассо", "Ted Lasso", 2020, "сериал", ["comedy", "sport", "family"], ["be curious not judgemental", "believe", "richmond", "football is life", "я верю в вас"], "Тед Лассо"),
    f("severance", "Разделение", "Severance", 2022, "сериал", ["mind-power", "slow", "dark"], ["the work is mysterious and important", "innie", "outie", "lumon", "refine the numbers"], "Разделение Severance"),
    f("fallout", "Фоллаут", "Fallout", 2024, "сериал", ["chaotic", "irony", "war"], ["war never changes", "vault", "nuka cola", "ghoul", "братство стали"], "Фоллаут сериал"),
    f("yellowjackets", "Йеллоуджеккетс", "Yellowjackets", 2021, "сериал", ["horror", "dark", "slow"], ["wilderness", "команда", "выживание", "шаман"], "Йеллоуджеккетс"),
    f("from", "From", "From", 2022, "сериал", ["horror", "slow", "mind-power"], ["don't go out at night", "городок", "деревья", "талон"], "From сериал"),
    f("sandman", "Песочный человек", "The Sandman", 2022, "сериал", ["fantasy", "slow", "dark"], ["dream of the endless", "morpheus", "король снов"], "Песочный человек"),
    f("umbrella", "Академия Амбрелла", "The Umbrella Academy", 2019, "сериал", ["fantasy", "comedy", "family"], ["number five", "апокалипсис", "семь детей"], "Академия Амбрелла"),
    f("lucifer", "Люцифер", "Lucifer", 2016, "сериал", ["comedy", "crime", "irony"], ["what is it you truly desire", "devil of hell", "детектив"], "Люцифер сериал"),
    f("supernatural", "Сверхъестественное", "Supernatural", 2005, "сериал", ["horror", "family", "tempo"], ["saving people hunting things", "impala", "winchester", "драйвер 67"], "Сверхъестественное"),
    f("vampire-diaries", "Дневники вампира", "The Vampire Diaries", 2009, "сериал", ["romance", "horror", "kids"], ["hello brother", "mystic falls", "стефан", "деймон"], "Дневники вампира"),
    f("bridgerton", "Бриджертоны", "Bridgerton", 2020, "сериал", ["romance", "irony", "family"], ["dear gentle reader", "daphne", "лондонский сезон", "леди уистлдаун"], "Бриджертоны"),
    f("outlander", "Чужестранка", "Outlander", 2014, "сериал", ["romance", "war", "fantasy"], ["sassenach", "jamie", "шотландия", "время"], "Чужестранка"),
    f("vikings", "Викинги", "Vikings", 2013, "сериал", ["war", "family", "dark"], ["odin", "ragnar", "lagertha", "валхалла"], "Викинги"),
    f("last-kingdom", "Последнее королевство", "The Last Kingdom", 2015, "сериал", ["war", "slow", "family"], ["destiny is all", "утреду", "саксы", "даны"], "Последнее королевство"),
    f("house-of-cards", "Карточный домик", "House of Cards", 2013, "сериал", ["ambition", "dark", "slick-urban"], ["you might very well think that", "frank underwood", "whip", "я не проиграю"], "Карточный домик"),
    f("homeland", "Родина", "Homeland", 2011, "сериал", ["slow", "dark", "mind-power"], ["carrie mathison", "броди", "цру"], "Родина Homeland"),
    f("slow-horses", "Медленные лошади", "Slow Horses", 2022, "сериал", ["irony", "crime", "slick-urban"], ["slough house", "jackson lamb", "mi5", "отбросы разведки"], "Медленные лошади"),
    f("bodyguard", "Телохранитель", "Bodyguard", 2018, "сериал", ["tempo", "dark", "crime"], ["david budd", "министр", "теракт"], "Телохранитель сериал"),
    f("killing-eve", "Убивая Еву", "Killing Eve", 2018, "сериал", ["crime", "irony", "tempo"], ["villanelle", "eve", "я тебя найду", "убийца"], "Убивая Еву"),
    f("sex-education", "Половое воспитание", "Sex Education", 2019, "сериал", ["comedy", "romance", "kids"], ["otis", "маеве", "клиника"], "Половое воспитание"),
    f("wednesday-already", "Уэнсдей", "Wednesday", 2022, "сериал", ["irony", "horror", "kids"], ["i prefer to be feared"], "skip"),
    f("reacher", "Ричер", "Reacher", 2022, "сериал", ["tempo", "crime", "irony"], ["i'm a cop", "jack reacher", "большой"], "Ричер"),
    f("the-boys-already", "Пацаны", "The Boys", 2019, "сериал", ["irony", "dark", "tempo"], ["homelander"], "skip"),
    f("invincible", "Неуязвимый", "Invincible", 2021, "сериал", ["tempo", "family", "dark"], ["think mark", "omniman", "that's the neat part you don't"], "Неуязвимый"),
    f("arcane-already", "Аркейн", "Arcane", 2021, "сериал", ["fantasy", "family", "dark"], ["jinx"], "skip"),
    f("house-md-already", "Доктор Хаус", "House M.D.", 2004, "сериал", ["mind-power", "irony", "slow"], ["everybody lies"], "skip"),
    f("scrubs", "Клиника", "Scrubs", 2001, "сериал", ["comedy", "family", "irony"], ["my name is jd", "sacred heart", "янтор"], "Клиника Scrubs"),
    f("friends-more", "Друзья", "Friends", 1994, "сериал", ["comedy", "romance", "family"], ["how you doing"], "skip"),
    f("himym-already", "Как я встретил вашу маму", "How I Met Your Mother", 2005, "сериал", ["comedy", "romance", "family"], ["suit up"], "skip"),
    f("modern-family", "Американская семейка", "Modern Family", 2009, "сериал", ["comedy", "family", "irony"], ["phil dunphy", "claire", "камера"], "Американская семейка"),
    f("always-sunny", "В Филадельфии всегда солнечно", "It's Always Sunny in Philadelphia", 2005, "сериал", ["comedy", "chaotic", "irony"], ["the gang", "dennis system", "bird"], "В Филадельфии всегда солнечно"),
    f("iasip", "В Филадельфии всегда солнечно", "It's Always Sunny", 2005, "сериал", ["comedy", "chaotic", "irony"], ["skip"], "skip"),
    f("fargo-tv", "Фарго", "Fargo", 2014, "сериал", ["crime", "irony", "slow"], ["this is a true story", "minnesota", "коинциденция"], "Фарго сериал"),
    f("true-det-already", "Настоящий детектив", "True Detective", 2014, "сериал", ["crime", "dark", "slow"], ["time is a flat circle"], "skip"),
    f("mare", "Мэр Исттауна", "Mare of Easttown", 2021, "сериал", ["crime", "slow", "family"], ["mare", "pennsylvania", "убийство"], "Мэр Исттауна"),
    f("big-little", "Большая маленькая ложь", "Big Little Lies", 2017, "сериал", ["slow", "dark", "family"], ["monterey", "школа", "женщины"], "Большая маленькая ложь"),
    f("white-lotus-already", "Белый лотос", "The White Lotus", 2021, "сериал", ["irony", "dark", "slow"], ["resort"], "skip"),
    f("the-bear-already", "Медведь", "The Bear", 2022, "сериал", ["tempo", "ambition", "family"], ["yes chef"], "skip"),
    f("succession-already", "Наследники", "Succession", 2018, "сериал", ["ambition", "family", "irony"], ["l to the og"], "skip"),
    f("andor-already", "Андор", "Andor", 2022, "сериал", ["war", "slow", "space"], ["rebellion"], "skip"),
    f("mando-already", "Мандалорец", "The Mandalorian", 2019, "сериал", ["fantasy", "space", "family"], ["this is the way"], "skip"),
    f("ahsoka", "Асока", "Ahsoka", 2023, "сериал", ["fantasy", "space", "war"], ["thrawn", "sabine", "асока тано"], "Асока"),
    f("andor2", "Андор", "Andor", 2022, "сериал", ["war", "slow", "space"], ["skip"], "skip"),
    f("last-of-us-already", "Одни из нас", "The Last of Us", 2023, "сериал", ["dark", "family", "horror"], ["endure and survive"], "skip"),
    f("last-of-us-2s", "Одни из нас", "The Last of Us", 2023, "сериал", ["dark", "family", "horror"], ["look for the light"], "skip"),
    f("house-dragon-already", "Дом Дракона", "House of the Dragon", 2022, "сериал", ["family", "dark", "war"], ["fire and blood"], "skip"),
    f("rings-power", "Властелин колец: Кольца власти", "The Rings of Power", 2022, "сериал", ["fantasy", "war", "slow"], ["galadriel", "нуменор", "саурон"], "Кольца власти"),
    f("wheel-time", "Колесо времени", "The Wheel of Time", 2021, "сериал", ["fantasy", "war", "tempo"], ["the wheel weaves", "rand", "эгвин"], "Колесо времени"),
    f("witcher-already", "Ведьмак", "The Witcher", 2019, "сериал", ["fantasy", "dark", "war"], ["toss a coin"], "skip"),
    f("shadow-bone", "Тень и кость", "Shadow and Bone", 2021, "сериал", ["fantasy", "romance", "tempo"], ["grisha", "fold", "алина"], "Тень и кость"),
    f("stranger-already", "Очень странные дела", "Stranger Things", 2016, "сериал", ["horror", "kids", "fantasy"], ["friends don't lie", "upside down", "eggo"], "skip"),
    f("dark-already", "Тьма", "Dark", 2017, "сериал", ["mind-power", "slow", "family"], ["sic mundus"], "skip"),
    f("1899", "1899", "1899", 2022, "сериал", ["mind-power", "slow", "horror"], ["корабль", "пароход", "кто мы"], "1899 сериал"),
    f("dark-matter", "Тёмная материя", "Dark Matter", 2024, "сериал", ["mind-power", "slow", "family"], ["коробка", "мультивселенная", "jason"], "Тёмная материя сериал"),
    f("fallout-already", "Фоллаут", "Fallout", 2024, "сериал", ["chaotic", "irony", "war"], ["war never changes"], "skip"),
    f("the-last-of", "Одни из нас", "The Last of Us", 2023, "сериал", ["dark", "family", "horror"], ["skip"], "skip"),
    f("shogun", "Сёгун", "Shōgun", 2024, "сериал", ["slow", "war", "family"], ["anjin", "toranaga", "япония", "чёрные корабли"], "Сёгун"),
    f("gilded", "Позолоченный век", "The Gilded Age", 2022, "сериал", ["irony", "family", "slick-urban"], ["нью-йорк", "деньги", "старая знать"], "Позолоченный век"),
    f("the-crown-already", "Корона", "The Crown", 2016, "сериал", ["family", "slow", "ambition"], ["elizabeth"], "skip"),
    f("the-diplomat", "Дипломатка", "The Diplomat", 2023, "сериал", ["tempo", "ambition", "slick-urban"], ["посол", "лондон", "кризис"], "Дипломатка"),
    f("night-agent", "Ночной агент", "The Night Agent", 2023, "сериал", ["tempo", "crime", "mind-power"], ["white house", "телефон", "агент"], "Ночной агент"),
    f("reacher-already", "Ричер", "Reacher", 2022, "сериал", ["tempo", "crime", "irony"], ["jack reacher"], "skip"),
  ]);
  window.POFRAZE_FILMS = window.POFRAZE_FILMS.filter(function (film) {
    return film.watchQuery !== "skip";
  });
})();
