window.POFRAZE_CHIPS = [
  "в чём сила, брат",
  "я принимал эн зет",
  "первое правило бойцовского клуба",
  "зима близко",
  "я тот, кто стучит",
  "here's looking at you kid",
  "ты волшебник гарри",
  "я твой отец",
  "frankly my dear",
  "i see dead people",
  "houston we have a problem",
  "you can't handle the truth",
  "rosebud",
  "there's no place like home",
  "show me the money",
  "ложку не существует",
  "продай мне эту ручку",
  "why so serious",
  "you shall not pass",
  "i'll be back",
  "that's what she said",
  "we were on a break",
  "штирлиц задумался",
  "птичку жалко",
  "с лёгким паром",
  "чушпан",
  "ты не выдержишь правду",
  "я вижу мёртвых",
  "взболтать но не смешивать",
];

window.POFRAZE_VIBES = {
  "slick-urban": "гладкий город",
  "mind-power": "ум и власть",
  tempo: "темп",
  ambition: "амбиция",
  dark: "мрак",
  irony: "ирония",
  crime: "криминал",
  soviet: "советская классика",
  heist: "афера",
  space: "космос",
  family: "семья и долг",
  chaotic: "хаос",
  slow: "медленное напряжение",
  street: "улица",
  romance: "романтика",
  fantasy: "сказка и эпос",
  horror: "ужас",
  comedy: "комедия",
  war: "война",
  sport: "спорт",
  kids: "семейное",
};

window.POFRAZE_FILMS = [
  {
    id: "limitless",
    title: "Область тьмы",
    originalTitle: "Limitless",
    year: 2011,
    type: "фильм",
    initials: "ОТ",
    color: "#c9a36a",
    vibes: ["slick-urban", "mind-power", "tempo", "ambition"],
    quotes: [
      "я принимал nzt",
      "я принимал эн зет тэ",
      "это как видеть матрицу",
      "я стал лучше во всём",
      "таблетка которая открывает мозг",
    ],
    watchQuery: "Область тьмы Limitless",
  },
  {
    id: "brother",
    title: "Брат",
    originalTitle: "Brother",
    year: 1997,
    type: "фильм",
    initials: "БР",
    color: "#8fa3b8",
    vibes: ["street", "crime", "dark"],
    quotes: [
      "в чём сила брат",
      "сила в правде",
      "кто прав тот и сильней",
      "ты городской да",
    ],
    watchQuery: "Брат Бодров",
  },
  {
    id: "fight-club",
    title: "Бойцовский клуб",
    originalTitle: "Fight Club",
    year: 1999,
    type: "фильм",
    initials: "БК",
    color: "#d4b8a0",
    vibes: ["dark", "mind-power", "chaotic"],
    quotes: [
      "первое правило бойцовского клуба",
      "о бойцовском клубе не говорить",
      "мы с джаредом лето покупаем вещи которые нам не нужны",
      "ты не твоя работа",
    ],
    watchQuery: "Бойцовский клуб",
  },
  {
    id: "matrix",
    title: "Матрица",
    originalTitle: "The Matrix",
    year: 1999,
    type: "фильм",
    initials: "МХ",
    color: "#7dcf9f",
    vibes: ["mind-power", "tempo", "dark"],
    quotes: [
      "есть ложка",
      "ложку ты не сгибаешь",
      "следуй за белым кроликом",
      "добро пожаловать в реальный мир",
      "таблетка красная или синяя",
    ],
    watchQuery: "Матрица",
  },
  {
    id: "inception",
    title: "Начало",
    originalTitle: "Inception",
    year: 2010,
    type: "фильм",
    initials: "НЧ",
    color: "#9bb8d4",
    vibes: ["mind-power", "tempo", "slow"],
    quotes: [
      "идею как вирус",
      "нужен пинок",
      "мы должны идти глубже",
      "волчок ещё крутится",
    ],
    watchQuery: "Начало Inception",
  },
  {
    id: "pulp",
    title: "Криминальное чтиво",
    originalTitle: "Pulp Fiction",
    year: 1994,
    type: "фильм",
    initials: "КЧ",
    color: "#e0a070",
    vibes: ["crime", "irony", "chaotic"],
    quotes: [
      "римский гамбургер",
      "они называют его роял с чизом",
      "это что за чемодан",
      "биг кахану наггетс",
    ],
    watchQuery: "Криминальное чтиво",
  },
  {
    id: "diamond-arm",
    title: "Бриллиантовая рука",
    originalTitle: "",
    year: 1968,
    type: "фильм",
    initials: "БР",
    color: "#e8d48a",
    vibes: ["irony", "heist", "soviet"],
    quotes: [
      "чудны дела твои господи",
      "наше дело не так чтобы совсем наше",
      "рубай пальму",
      "клянусь я не виноват",
    ],
    watchQuery: "Бриллиантовая рука",
  },
  {
    id: "ivan-vasilievich",
    title: "Иван Васильевич меняет профессию",
    originalTitle: "",
    year: 1973,
    type: "фильм",
    initials: "ИВ",
    color: "#d9c4a0",
    vibes: ["irony", "heist", "soviet"],
    quotes: [
      "танцуют все",
      "я требую продолжения банкета",
      "царь очень занят",
      "я требую чтобы меня освободили",
    ],
    watchQuery: "Иван Васильевич меняет профессию",
  },
  {
    id: "gentlemen-luck",
    title: "Джентльмены удачи",
    originalTitle: "",
    year: 1971,
    type: "фильм",
    initials: "ДУ",
    color: "#c4b49a",
    vibes: ["irony", "heist", "soviet"],
    quotes: [
      "птичку жалко",
      "сейчас я вам покажу кузькину мать",
      "гады как вы меня достали",
    ],
    watchQuery: "Джентльмены удачи",
  },
  {
    id: "meeting",
    title: "Место встречи изменить нельзя",
    originalTitle: "",
    year: 1979,
    type: "сериал",
    initials: "МВ",
    color: "#b8a090",
    vibes: ["crime", "soviet", "slow"],
    quotes: [
      "чтобы ты жил на одну зарплату",
      "вор должен сидеть в тюрьме",
      "я мстислав",
    ],
    watchQuery: "Место встречи изменить нельзя",
  },
  {
    id: "joker",
    title: "Джокер",
    originalTitle: "Joker",
    year: 2019,
    type: "фильм",
    initials: "ДЖ",
    color: "#d9784a",
    vibes: ["dark", "chaotic", "street"],
    quotes: [
      "ты получаешь то что заслуживаешь",
      "я раньше думал что моя жизнь трагедия",
      "комедия",
    ],
    watchQuery: "Джокер 2019",
  },
  {
    id: "dark-knight",
    title: "Тёмный рыцарь",
    originalTitle: "The Dark Knight",
    year: 2008,
    type: "фильм",
    initials: "ТР",
    color: "#9aa0aa",
    vibes: ["dark", "crime", "slick-urban"],
    quotes: [
      "почему так серьёзно",
      "хаос это лестница",
      "либо умрёшь героем",
      "либо живёшь достаточно долго",
    ],
    watchQuery: "Тёмный рыцарь",
  },
  {
    id: "wolf",
    title: "Волк с Уолл-стрит",
    originalTitle: "The Wolf of Wall Street",
    year: 2013,
    type: "фильм",
    initials: "ВС",
    color: "#e2c27a",
    vibes: ["ambition", "chaotic", "slick-urban"],
    quotes: [
      "продай мне эту ручку",
      "я не покидаю корабль",
      "больше денег",
    ],
    watchQuery: "Волк с Уолл-стрит",
  },
  {
    id: "social",
    title: "Социальная сеть",
    originalTitle: "The Social Network",
    year: 2010,
    type: "фильм",
    initials: "СС",
    color: "#7aa0d4",
    vibes: ["ambition", "slick-urban", "mind-power"],
    quotes: [
      "ты не получишь 500 миллионов друзей",
      "без того чтобы кого-то не предать",
      "мы не в гарварде для вечеринок",
    ],
    watchQuery: "Социальная сеть",
  },
  {
    id: "drive",
    title: "Драйв",
    originalTitle: "Drive",
    year: 2011,
    type: "фильм",
    initials: "ДР",
    color: "#e07090",
    vibes: ["slick-urban", "slow", "crime"],
    quotes: [
      "я водитель",
      "пять минут я жду",
      "если что-то пойдёт не так я ничего о тебе не знаю",
    ],
    watchQuery: "Драйв Гослинг",
  },
  {
    id: "blade",
    title: "Бегущий по лезвию 2049",
    originalTitle: "Blade Runner 2049",
    year: 2017,
    type: "фильм",
    initials: "БЛ",
    color: "#d0b48c",
    vibes: ["slow", "dark", "slick-urban"],
    quotes: [
      "умереть за женщину",
      "ты настоящий",
      "все самые лучшие воспоминания",
    ],
    watchQuery: "Бегущий по лезвию 2049",
  },
  {
    id: "interstellar",
    title: "Интерстеллар",
    originalTitle: "Interstellar",
    year: 2014,
    type: "фильм",
    initials: "ИН",
    color: "#8ab4d4",
    vibes: ["space", "family", "slow"],
    quotes: [
      "мы должны идти дальше",
      "любовь это единственное что мы можем воспринимать",
      "не смотри вниз купер",
      "ты папин призрак",
    ],
    watchQuery: "Интерстеллар",
  },
  {
    id: "gladiator",
    title: "Гладиатор",
    originalTitle: "Gladiator",
    year: 2000,
    type: "фильм",
    initials: "ГЛ",
    color: "#d4a878",
    vibes: ["family", "dark", "ambition"],
    quotes: [
      "ты меня развлекаешь",
      "в следующей жизни",
      "силой и честью",
      "рим это тень",
    ],
    watchQuery: "Гладиатор",
  },
  {
    id: "leon",
    title: "Леон",
    originalTitle: "Léon",
    year: 1994,
    type: "фильм",
    initials: "ЛН",
    color: "#c8c0b0",
    vibes: ["crime", "family", "slow"],
    quotes: [
      "это растение",
      "я работаю чисто",
      "никто не обижает маттильду",
    ],
    watchQuery: "Леон",
  },
  {
    id: "shutter",
    title: "Остров проклятых",
    originalTitle: "Shutter Island",
    year: 2010,
    type: "фильм",
    initials: "ОП",
    color: "#9aa8b4",
    vibes: ["dark", "mind-power", "slow"],
    quotes: [
      "кто я монстр или герой",
      "это лучше чем жить как монстр",
      "маяк",
    ],
    watchQuery: "Остров проклятых",
  },
  {
    id: "gentlemen",
    title: "Джентльмены",
    originalTitle: "The Gentlemen",
    year: 2019,
    type: "фильм",
    initials: "ДЖ",
    color: "#c9b07a",
    vibes: ["crime", "irony", "slick-urban"],
    quotes: [
      "если ты не джентльмен",
      "это бизнес",
      "марихуана как вино",
    ],
    watchQuery: "Джентльмены Рейчи",
  },
  {
    id: "breaking-bad",
    title: "Во все тяжкие",
    originalTitle: "Breaking Bad",
    year: 2008,
    type: "сериал",
    initials: "ВТ",
    color: "#c47a3a",
    vibes: ["crime", "ambition", "dark"],
    quotes: [
      "я тот кто стучит",
      "я тот кто стучится в дверь",
      "скажи моё имя",
      "мы с гасом не партнёры",
    ],
    watchQuery: "Во все тяжкие",
  },
  {
    id: "got",
    title: "Игра престолов",
    originalTitle: "Game of Thrones",
    year: 2011,
    type: "сериал",
    initials: "ИП",
    color: "#b0a090",
    vibes: ["family", "dark", "ambition"],
    quotes: [
      "зима близко",
      "ты ничего не знаешь джон сноу",
      "дракон",
    ],
    watchQuery: "Игра престолов",
  },
  {
    id: "irony-fate",
    title: "Ирония судьбы, или С лёгким паром!",
    originalTitle: "",
    year: 1975,
    type: "фильм",
    initials: "ИС",
    color: "#e0c8c0",
    vibes: ["irony", "family", "soviet"],
    quotes: [
      "с легким паром",
      "я живу на третьей улице строителей",
      "какая гадость эта ваша заливная рыба",
    ],
    watchQuery: "Ирония судьбы",
  },
];
