window.POFRAZE_CHIPS = [
  "в чём сила, брат",
  "я принимал эн зет",
  "первое правило бойцовского клуба",
  "зима близко",
  "я тот, кто стучит",
  "я смотрю на тебя крошка",
  "ты волшебник гарри",
  "я твой отец",
  "откровенно говоря моя дорогая",
  "я вижу мёртвых",
  "хьюстон у нас проблема",
  "ты не выдержишь правды",
  "роузбад",
  "нет места лучше дома",
  "покажи мне деньги",
  "ложку не существует",
  "продай мне эту ручку",
  "почему так серьёзно",
  "ты не пройдёшь",
  "я вернусь",
  "это то что она сказала",
  "у нас был перерыв",
  "штирлиц задумался",
  "птичку жалко",
  "с лёгким паром",
  "чушпан",
  "ты не выдержишь правду",
  "я вижу мёртвых",
  "взболтать но не смешивать",
  "пепелац",
  "никто не ставит малышку в угол",
  "с нами не сидят",
  "у меня очень специфический набор навыков",
];

window.POFRAZE_VIBES = {
  "slick-urban": "гладкий город",
  "mind-power": "ум и власть",
  tempo: "темп",
  ambition: "амбиция",
  dark: "мрак",
  irony: "ирония",
  crime: "криминал",
  soviet: "советская классика",
  heist: "афера",
  space: "космос",
  family: "семья и долг",
  chaotic: "хаос",
  slow: "медленное напряжение",
  street: "улица",
  romance: "романтика",
  fantasy: "сказка и эпос",
  horror: "ужас",
  comedy: "комедия",
  war: "война",
  sport: "спорт",
  kids: "семейное",
};

window.POFRAZE_FILMS = [
  {
    id: "limitless",
    title: "Область тьмы",
    originalTitle: "Limitless",
    year: 2011,
    type: "фильм",
    initials: "ОТ",
    color: "#c9a36a",
    vibes: ["slick-urban", "mind-power", "tempo", "ambition"],
    quotes: [
      "я принимал nzt",
      "я принимал эн зет тэ",
      "это как видеть матрицу",
      "я стал лучше во всём",
      "таблетка которая открывает мозг",
    ],
    watchQuery: "Область тьмы Limitless",
  },
  {
    id: "brother",
    title: "Брат",
    originalTitle: "Brother",
    year: 1997,
    type: "фильм",
    initials: "БР",
    color: "#8fa3b8",
    vibes: ["street", "crime", "dark"],
    quotes: [
      "в чём сила брат",
      "сила в правде",
      "кто прав тот и сильней",
      "ты городской да",
    ],
    watchQuery: "Брат Бодров",
  },
  {
    id: "fight-club",
    title: "Бойцовский клуб",
    originalTitle: "Fight Club",
    year: 1999,
    type: "фильм",
    initials: "БК",
    color: "#d4b8a0",
    vibes: ["dark", "mind-power", "chaotic"],
    quotes: [
      "первое правило бойцовского клуба",
      "о бойцовском клубе не говорить",
      "the first rule of fight club is you do not talk about fight club",
      "the things you own end up owning you",
      "ты не твоя работа",
    ],
    watchQuery: "Бойцовский клуб",
  },
  {
    id: "matrix",
    title: "Матрица",
    originalTitle: "The Matrix",
    year: 1999,
    type: "фильм",
    initials: "МХ",
    color: "#7dcf9f",
    vibes: ["mind-power", "tempo", "dark"],
    quotes: [
      "ложки нет",
      "there is no spoon",
      "ложку ты не сгибаешь",
      "следуй за белым кроликом",
      "follow the white rabbit",
      "добро пожаловать в реальный мир",
      "таблетка красная или синяя",
    ],
    watchQuery: "Матрица",
  },
  {
    id: "inception",
    title: "Начало",
    originalTitle: "Inception",
    year: 2010,
    type: "фильм",
    initials: "НЧ",
    color: "#9bb8d4",
    vibes: ["mind-power", "tempo", "slow"],
    quotes: [
      "идею как вирус",
      "нужен пинок",
      "мы должны идти глубже",
      "волчок ещё крутится",
    ],
    watchQuery: "Начало Inception",
  },
  {
    id: "pulp",
    title: "Криминальное чтиво",
    originalTitle: "Pulp Fiction",
    year: 1994,
    type: "фильм",
    initials: "КЧ",
    color: "#e0a070",
    vibes: ["crime", "irony", "chaotic"],
    quotes: [
      "royal with cheese",
      "они называют его роял с чизом",
      "big kahuna burger",
      "это что за чемодан",
    ],
    watchQuery: "Криминальное чтиво",
  },
  {
    id: "diamond-arm",
    title: "Бриллиантовая рука",
    originalTitle: "",
    year: 1968,
    type: "фильм",
    initials: "БР",
    color: "#e8d48a",
    vibes: ["irony", "heist", "soviet"],
    quotes: [
      "чудны дела твои господи",
      "наше дело не так чтобы совсем наше",
      "не виноватая я он сам пришёл",
      "ключ от квартиры где деньги лежат",
    ],
    watchQuery: "Бриллиантовая рука",
  },
  {
    id: "ivan-vasilievich",
    title: "Иван Васильевич меняет профессию",
    originalTitle: "",
    year: 1973,
    type: "фильм",
    initials: "ИВ",
    color: "#d9c4a0",
    vibes: ["irony", "heist", "soviet"],
    quotes: [
      "я требую продолжения банкета",
      "царь очень занят",
      "на тебе царь",
      "я за себя не ручаюсь",
    ],
    watchQuery: "Иван Васильевич меняет профессию",
  },
  {
    id: "gentlemen-luck",
    title: "Джентльмены удачи",
    originalTitle: "",
    year: 1971,
    type: "фильм",
    initials: "ДУ",
    color: "#c4b49a",
    vibes: ["irony", "heist", "soviet"],
    quotes: [
      "птичку жалко",
      "сейчас я вам покажу кузькину мать",
      "гады как вы меня достали",
    ],
    watchQuery: "Джентльмены удачи",
  },
  {
    id: "meeting",
    title: "Место встречи изменить нельзя",
    originalTitle: "",
    year: 1979,
    type: "сериал",
    initials: "МВ",
    color: "#b8a090",
    vibes: ["crime", "soviet", "slow"],
    quotes: [
      "чтобы ты жил на одну зарплату",
      "вор должен сидеть в тюрьме",
      "чёрная кошка",
    ],
    watchQuery: "Место встречи изменить нельзя",
  },
  {
    id: "joker",
    title: "Джокер",
    originalTitle: "Joker",
    year: 2019,
    type: "фильм",
    initials: "ДЖ",
    color: "#d9784a",
    vibes: ["dark", "chaotic", "street"],
    quotes: [
      "ты получаешь то что заслуживаешь",
      "я раньше думал что моя жизнь трагедия",
      "комедия",
    ],
    watchQuery: "Джокер 2019",
  },
  {
    id: "dark-knight",
    title: "Тёмный рыцарь",
    originalTitle: "The Dark Knight",
    year: 2008,
    type: "фильм",
    initials: "ТР",
    color: "#9aa0aa",
    vibes: ["dark", "crime", "slick-urban"],
    quotes: [
      "why so serious",
      "почему так серьёзно",
      "some men just want to watch the world burn",
      "либо умрёшь героем",
      "либо живёшь достаточно долго чтобы стать злодеем",
    ],
    watchQuery: "Тёмный рыцарь",
  },
  {
    id: "wolf",
    title: "Волк с Уолл-стрит",
    originalTitle: "The Wolf of Wall Street",
    year: 2013,
    type: "фильм",
    initials: "ВС",
    color: "#e2c27a",
    vibes: ["ambition", "chaotic", "slick-urban"],
    quotes: [
      "продай мне эту ручку",
      "я не покидаю корабль",
      "больше денег",
    ],
    watchQuery: "Волк с Уолл-стрит",
  },
  {
    id: "social",
    title: "Социальная сеть",
    originalTitle: "The Social Network",
    year: 2010,
    type: "фильм",
    initials: "СС",
    color: "#7aa0d4",
    vibes: ["ambition", "slick-urban", "mind-power"],
    quotes: [
      "you don't get to 500 million friends without making a few enemies",
      "a million dollars isn't cool you know what's cool a billion dollars",
      "ты не получишь 500 миллионов друзей без того чтобы кого-то не предать",
    ],
    watchQuery: "Социальная сеть",
  },
  {
    id: "drive",
    title: "Драйв",
    originalTitle: "Drive",
    year: 2011,
    type: "фильм",
    initials: "ДР",
    color: "#e07090",
    vibes: ["slick-urban", "slow", "crime"],
    quotes: [
      "я водитель",
      "пять минут я жду",
      "если что-то пойдёт не так я ничего о тебе не знаю",
    ],
    watchQuery: "Драйв Гослинг",
  },
  {
    id: "blade",
    title: "Бегущий по лезвию 2049",
    originalTitle: "Blade Runner 2049",
    year: 2017,
    type: "фильм",
    initials: "БЛ",
    color: "#d0b48c",
    vibes: ["slow", "dark", "slick-urban"],
    quotes: [
      "dying for the right cause is the most human thing we can do",
      "you've never seen a miracle",
      "все самые лучшие воспоминания её",
    ],
    watchQuery: "Бегущий по лезвию 2049",
  },
  {
    id: "interstellar",
    title: "Интерстеллар",
    originalTitle: "Interstellar",
    year: 2014,
    type: "фильм",
    initials: "ИН",
    color: "#8ab4d4",
    vibes: ["space", "family", "slow"],
    quotes: [
      "do not go gentle into that good night",
      "stay",
      "love is the one thing we're capable of perceiving that transcends time and space",
      "я возвращаюсь",
    ],
    watchQuery: "Интерстеллар",
  },
  {
    id: "gladiator",
    title: "Гладиатор",
    originalTitle: "Gladiator",
    year: 2000,
    type: "фильм",
    initials: "ГЛ",
    color: "#d4a878",
    vibes: ["family", "dark", "ambition"],
    quotes: [
      "are you not entertained",
      "вас это не развлекает",
      "strength and honor",
      "сила и честь",
      "what we do in life echoes in eternity",
    ],
    watchQuery: "Гладиатор",
  },
  {
    id: "leon",
    title: "Леон",
    originalTitle: "Léon",
    year: 1994,
    type: "фильм",
    initials: "ЛН",
    color: "#c8c0b0",
    vibes: ["crime", "family", "slow"],
    quotes: [
      "это растение",
      "я люблю молоко",
      "is life always this hard or is it just when you're a kid",
    ],
    watchQuery: "Леон",
  },
  {
    id: "shutter",
    title: "Остров проклятых",
    originalTitle: "Shutter Island",
    year: 2010,
    type: "фильм",
    initials: "ОП",
    color: "#9aa8b4",
    vibes: ["dark", "mind-power", "slow"],
    quotes: [
      "which would be worse to live as a monster or to die as a good man",
      "это лучше чем жить как монстр",
      "маяк",
    ],
    watchQuery: "Остров проклятых",
  },
  {
    id: "gentlemen",
    title: "Джентльмены",
    originalTitle: "The Gentlemen",
    year: 2019,
    type: "фильм",
    initials: "ДЖ",
    color: "#c9b07a",
    vibes: ["crime", "irony", "slick-urban"],
    quotes: [
      "это бизнес",
      "there's only two types of men in this world",
      "если ты не джентльмен",
    ],
    watchQuery: "Джентльмены Рейчи",
  },
  {
    id: "breaking-bad",
    title: "Во все тяжкие",
    originalTitle: "Breaking Bad",
    year: 2008,
    type: "сериал",
    initials: "ВТ",
    color: "#c47a3a",
    vibes: ["crime", "ambition", "dark"],
    quotes: [
      "я тот кто стучит",
      "я тот кто стучит в дверь",
      "скажи моё имя",
      "мы с гасом не партнёры",
    ],
    watchQuery: "Во все тяжкие",
  },
  {
    id: "got",
    title: "Игра престолов",
    originalTitle: "Game of Thrones",
    year: 2011,
    type: "сериал",
    initials: "ИП",
    color: "#b0a090",
    vibes: ["family", "dark", "ambition"],
    quotes: [
      "зима близко",
      "winter is coming",
      "ты ничего не знаешь джон сноу",
      "you know nothing jon snow",
      "chaos is a ladder",
    ],
    watchQuery: "Игра престолов",
  },
  {
    id: "irony-fate",
    title: "Ирония судьбы, или С лёгким паром!",
    originalTitle: "",
    year: 1975,
    type: "фильм",
    initials: "ИС",
    color: "#e0c8c0",
    vibes: ["irony", "family", "soviet"],
    quotes: [
      "с легким паром",
      "я живу на третьей улице строителей",
      "какая гадость эта ваша заливная рыба",
    ],
    watchQuery: "Ирония судьбы",
  },
];
