(function () {
  var extra = {
    limitless: ["NZT-48", "I wasn't high I was clear"],
    brother: ["в чём сила брат", "сила в правде"],
    "brother-2": ["вы кто такие давайте до свидания"],
    "fight-club": [
      "the first rule of fight club is you do not talk about fight club",
      "his name is tyler durden",
      "you are not your fucking khakis",
      "i am jack's complete lack of surprise",
    ],
    matrix: [
      "there is no spoon",
      "follow the white rabbit",
      "unfortunately no one can be told what the matrix is",
      "i know kung fu",
      "welcome to the real world",
    ],
    inception: [
      "we need to go deeper",
      "an idea is like a virus",
      "you mustn't be afraid to dream a little bigger darling",
    ],
    pulp: [
      "a royal with cheese",
      "english motherfucker do you speak it",
      "ezekiel 25:17",
    ],
    joker: [
      "you get what you fucking deserve",
      "is it just me or is it getting crazier out there",
      "put on a happy face",
    ],
    "dark-knight": [
      "why so serious",
      "wanna know how i got these scars",
      "some men aren't looking for anything logical",
      "you either die a hero or you live long enough to see yourself become the villain",
    ],
    wolf: ["sell me this pen", "on the button"],
    social: [
      "a million dollars isn't cool you know what's cool a billion dollars",
      "if you guys were the inventors of facebook you'd have invented facebook",
    ],
    drive: ["i drive"],
    blade: ["dying for the right cause is the most human thing we can do"],
    interstellar: [
      "do not go gentle into that good night",
      "love is the one thing we're capable of perceiving that transcends time and space",
      "murphy's law",
    ],
    gladiator: [
      "are you not entertained",
      "what we do in life echoes in eternity",
      "strength and honor",
    ],
    leon: ["i like milk", "is life always this hard or is it just when you're a kid"],
    shutter: ["which would be worse to live as a monster or to die as a good man"],
    gentlemen: ["there's only two types of men in this world"],
    "breaking-bad": [
      "i am the one who knocks",
      "say my name",
      "i am the danger",
      "yeah science",
    ],
    got: [
      "winter is coming",
      "you know nothing jon snow",
      "a lannister always pays his debts",
      "chaos is a ladder",
      "valar morghulis",
      "valar dohaeris",
      "the night is dark and full of terrors",
    ],
    godfather: [
      "i'm gonna make him an offer he can't refuse",
      "leave the gun take the cannoli",
      "it's not personal it's strictly business",
    ],
    "godfather-2": ["keep your friends close but your enemies closer"],
    goodfellas: ["as far back as i can remember i always wanted to be a gangster", "funny how"],
    scarface: ["say hello to my little friend", "the world is yours"],
    "taxi-driver": ["you talkin to me"],
    "silence-lambs": [
      "a census taker once tried to test me",
      "good evening clarice",
      "hello clarice",
      "i ate his liver with some fava beans and a nice chianti",
    ],
    se7en: ["what's in the box"],
    "usual-suspects": ["the greatest trick the devil ever pulled was convincing the world he didn't exist"],
    "die-hard": ["yippee ki yay"],
    jaws: ["you're gonna need a bigger boat"],
    alien: ["in space no one can hear you scream"],
    aliens: ["get away from her you bitch", "game over man"],
    predator: ["if it bleeds we can kill it", "get to the chopper"],
    rocky: ["yo adrian"],
    "star-wars": ["may the force be with you", "that's no moon", "help me obi-wan kenobi"],
    empire: ["no i am your father", "do or do not there is no try"],
    indiana: ["why did it have to be snakes", "it belongs in a museum"],
    jurassic: ["life finds a way", "hold onto your butts"],
    et: ["et phone home"],
    "kill-bill": ["wiggle your big toe"],
    django: ["i like the way you die boy"],
    inglourious: ["au revoir shoshanna"],
    reservoir: ["are you gonna bark all day little doggy"],
    forrest: [
      "life is like a box of chocolates you never know what you're gonna get",
      "run forrest run",
      "stupid is as stupid does",
    ],
    shawshank: ["get busy living or get busy dying", "hope is a good thing maybe the best of things"],
    "green-mile": ["on the day of my judgment when i stand before god"],
    titanic: ["i'm the king of the world", "i'll never let go jack"],
    "home-alone": ["keep the change ya filthy animal", "merry christmas ya filthy animal"],
    "back-future": ["roads where we're going we don't need roads", "great scott", "1.21 gigawatts"],
    "terminator-2": ["hasta la vista baby", "i'll be back", "come with me if you want to live"],
    hp1: ["you're a wizard harry", "yer a wizard harry"],
    lotr: ["you shall not pass", "my precious", "one ring to rule them all"],
    shrek: ["ogres are like onions"],
    "lion-king": ["hakuna matata", "remember who you are"],
    pirates: ["why is the rum gone", "this is the day you will always remember as the day you almost caught captain jack sparrow"],
    intouchables: ["earth wind and fire"],
    parasite: ["you know what kind of plan never fails"],
    whiplash: ["not quite my tempo", "there are no two words in the english language more harmful than good job"],
    "john-wick": ["people keep asking if i'm back", "yeah i'm thinking i'm back"],
    "mad-max": ["witness me", "oh what a day what a lovely day"],
    dune: ["fear is the mind-killer", "the spice must flow"],
    oppenheimer: ["now i am become death the destroyer of worlds"],
    barbie: ["i'm just ken", "she's everything he's just ken"],
    sherlock: ["the game is on", "i am a high-functioning sociopath"],
    friends: ["how you doin", "we were on a break", "pivot", "smelly cat"],
    stranger: ["friends don't lie", "she is our friend and she is crazy"],
    squid: ["red light green light", "mugunghwa kkochi pieosseumnida"],
    witcher: ["toss a coin to your witcher", "hmm"],
    house: ["everybody lies", "it's not lupus"],
    "money-heist": ["bella ciao"],
    avengers: ["avengers assemble", "i am iron man", "on your left", "i love you 3000"],
    spider: ["with great power comes great responsibility"],
    deadpool: ["maximum effort", "chimichangas"],
    "iron-man": ["i am iron man"],
    frozen: ["let it go", "the cold never bothered me anyway"],
    moana: ["you're welcome", "i am moana of motunui"],
    "toy-story": ["to infinity and beyond", "there's a snake in my boot"],
    nemo: ["just keep swimming"],
    up: ["adventure is out there"],
    coco: ["remember me"],
    "inside-out": ["do you guys ever look at someone and wonder what is going on inside their head"],
    walle: ["eve"],
    httyd: ["everything we know about you guys is wrong"],
    despicable: ["bee-do bee-do"],
    guardians: ["i am groot"],
    "black-panther": ["wakanda forever"],
    logan: ["so this is what it feels like"],
    office: ["that's what she said", "bears beets battlestar galactica", "i declare bankruptcy"],
    mandalorian: ["this is the way", "i have spoken"],
    "last-of-us": ["endure and survive", "look for the light"],
    succession: ["you are not serious people"],
    "the-bear": ["yes chef", "let it rip"],
    boys: ["homelander", "the only man in the sky is you"],
    andor: ["rebellions are built on hope", "one way out"],
    "house-dragon": ["fire and blood"],
    wednesday: ["i prefer to be feared", "i am not a hugger"],
    peaky: ["by order of the peaky blinders"],
    "doctor-who": ["wibbly wobbly timey wimey stuff", "allons-y"],
    himym: ["suit up", "it's gonna be legen wait for it dary"],
    bigbang: ["bazinga", "soft kitty warm kitty"],
    lost: ["we have to go back", "4 8 15 16 23 42"],
    "prison-break": ["i'm going to break my brother out of prison"],
    dexter: ["tonight's the night"],
    narcos: ["plata o plomo"],
    westworld: ["these violent delights have violent ends"],
    "death-note": ["i am justice", "i am the god of the new world"],
    "attack-titan": ["tatakae"],
    "one-piece": ["i'm gonna be king of the pirates"],
    naruto: ["dattebayo", "i will become hokage"],
    "rick-morty": ["wubba lubba dub dub", "i'm pickle rick"],
    brooklyn: ["cool cool cool cool cool", "noice"],
    "ted-lasso": ["be curious not judgemental", "football is life"],
    severance: ["the work is mysterious and important"],
    fallout: ["war never changes"],
    lucifer: ["what is it you truly desire"],
    supernatural: ["saving people hunting things the family business"],
    "vampire-diaries": ["hello brother"],
    bridgerton: ["dear gentle reader"],
    invincible: ["think mark think"],
    casablanca: [
      "here's looking at you kid",
      "we'll always have paris",
      "of all the gin joints in all the towns in all the world she walks into mine",
      "play it sam",
    ],
    psycho: ["a boy's best friend is his mother"],
    "2001": ["open the pod bay doors hal", "i'm sorry dave i'm afraid i can't do that"],
    clockwork: ["i was cured all right"],
    apocalypse: ["i love the smell of napalm in the morning"],
    "full-metal": ["this is my rifle this is my gun"],
    "saving-ryan": ["earn this"],
    schindler: ["whoever saves one life saves the world entire"],
    braveheart: ["they may take our lives but they'll never take our freedom"],
    heat: ["don't let yourself get attached to anything you are not willing to walk out on in 30 seconds"],
    departed: ["i'm the guy who does his job you must be the other guy"],
    "no-country": ["what's the most you ever lost on a coin toss"],
    "there-will": ["i drink your milkshake"],
    "big-lebowski": ["the dude abides", "this aggression will not stand man"],
    "catch-me": ["people only know what you tell them"],
    "gone-girl": ["cool girl"],
    "top-gun": ["i feel the need the need for speed"],
    "knives-out": ["i suspect foul play"],
    everything: ["in another life i would have really liked just doing laundry and taxes with you"],
    "kungfu-panda": ["there is no secret ingredient"],
    encanto: ["we don't talk about bruno"],
    ratatouille: ["anyone can cook"],
    incredibles: ["no capes"],
    notebook: ["if you're a bird i'm a bird"],
    "pretty-woman": ["big mistake huge"],
    "true-detective": ["time is a flat circle"],
    chernobyl: ["what is the cost of lies"],
    "better-call": ["it's all good man"],
    wire: ["all the pieces matter"],
    sopranos: ["those who want respect give respect"],
    "word-of-boy": ["чушпан", "слово пацана"],
    it: ["you'll float too"],
    scream: ["what's your favorite scary movie"],
    "get-out": ["get out"],
    "quiet-place": ["who are we if we can't protect them"],
    arrival: ["if you could see your whole life from start to finish would you change things"],
    martian: ["i'm going to have to science the shit out of this"],
    lalaland: ["here's to the ones who dream"],
    oldboy: ["laugh and the world laughs with you weep and you weep alone"],
    amelie: ["times are hard for dreamers"],
    "life-beautiful": ["buongiorno principessa"],
    "blade-old": ["like tears in rain", "all those moments will be lost in time"],
    terminator: ["i'll be back"],
  };

  (window.POFRAZE_FILMS || []).forEach(function (film) {
    var add = extra[film.id];
    if (!add) return;
    add.forEach(function (q) {
      var t = String(q || "").trim();
      if (t.length < 3) return;
      if (film.quotes.indexOf(t) === -1) film.quotes.push(t);
    });
  });

  var drop = {
    "dark-knight": [
      "chaos is a ladder",
      "хаос это лестница",
    ],
    "star-wars": [
      "я твой отец",
      "i am your father",
      "luke i am your father",
    ],
    terminator: ["hasta la vista baby"],
    "iron-man": ["i love you 3000"],
    blade: [
      "tears in rain",
      "like tears in rain",
      "я видел такое что вам не приснится",
      "декарт",
      "время умирать",
      "all those moments will be lost in time",
    ],
    "breaking-bad": ["лучше звоните солу", "better call saul"],
    shrek: ["somebody once told me"],
    rocky: ["gonna fly now"],
    intouchables: ["1+1", "я твой сиделка"],
    "prison-break": ["structured days"],
    squid: ["muneoh kkirigi"],
    gladiator: ["руки в грязи", "отец брата"],
    shutter: ["this is a live monster"],
    got: ["валенуар", "ты ничего не знаешь джон снег"],
    se7en: ["what's in the boxx"],
    leon: ["никто не обижает маттильду"],
    "back-future": ["дороги нужны там где мы их прокладываем"],
    "ivan-vasilievich": ["танцуют все"],
    "diamond-arm": ["рубай пальму"],
    meeting: ["я мстислав"],
    interstellar: ["ты папин призрак"],
    gentlemen: ["марихуана как вино", "птичку жалко", "доцент"],
    guardians: ["i am groot i am groot"],
    house: ["it's never lupus"],
  };

  (window.POFRAZE_FILMS || []).forEach(function (film) {
    var bad = drop[film.id];
    if (!bad || !film.quotes) return;
    film.quotes = film.quotes.filter(function (q) {
      var t = String(q || "").toLowerCase();
      for (var i = 0; i < bad.length; i++) {
        if (t === String(bad[i]).toLowerCase()) return false;
      }
      return true;
    });
  });
})();
