(function () {
  var extra = {
    limitless: [
      "nzt 48",
      "эн зет",
      "таблетка для мозга",
      "я вижу связи",
      "четыре часа сна",
      "я читаю людей",
      "clear pill",
      "eddie morra",
      "bradley cooper таблетка",
    ],
    brother: [
      "в чем сила брат",
      "сила в правде",
      "кто сильней тот и прав",
      "ты мне брат",
      "немец крылья",
      "я тебя не трогал",
      "петербург девяностые",
      "данила багров",
      "я музыку слушал",
      "ты городской",
    ],
    "brother-2": [
      "давайте до свидания",
      "вы кто такие",
      "русский с американцем",
      "чикаго",
      "деньги есть",
      "хоккей",
      "я русский",
      "миша багров",
    ],
    "fight-club": [
      "первое правило",
      "первое правило бойцовского клуба",
      "ты не рассказываешь",
      "его зовут тайлер",
      "тайлер дёрден",
      "мы продаём мыло",
      "ты не твоя работа",
      "ты не твои джинсы",
      "i am jack's",
      "сжечь всё",
      "space monkeys",
    ],
    matrix: [
      "следуй за белым кроликом",
      "красная таблетка",
      "синяя таблетка",
      "ложку не существует",
      "there is no spoon",
      "я знаю кунг фу",
      "welcome to the real world",
      "морфеус",
      "trinity",
      "агент смит",
      "неон",
      "выбери таблетку",
    ],
    inception: [
      "мы должны идти глубже",
      "we need to go deeper",
      "тотем волчок",
      "идея как вирус",
      "kick",
      "limbo",
      "сон во сне",
      "доминик кобб",
      "mal",
    ],
    pulp: [
      "big kahuna burger",
      "royal with cheese",
      "езекииль",
      "ezekiel 25 17",
      "танцуй твист",
      "чемоданчик",
      "винсент вега",
      "джулс",
      "я собираюсь get medieval",
      "bring out the gimp",
    ],
    "diamond-arm": [
      "наш человек в гаване",
      "чёрный кот",
      "ключ от квартиры",
      "где деньги лежат",
      "лучше гор могут быть только горы",
      "чудны дела твои господи",
      "сеня",
      "не виноватая я",
      "руку сломали",
      "гипс",
      "контрабанда",
    ],
    "ivan-vasilievich": [
      "я требую продолжения банкета",
      "царь очень занят",
      "на тебе царь",
      "тфу пропасть",
      "швед",
      "машина времени",
      "японский магнитофон",
      "житный двор",
      "я за себя не ручаюсь",
    ],
    "gentlemen-luck": [
      "птичку жалко",
      "кузькина мать",
      "доцент",
      "васютка",
      "теперь горбатый",
      "я зубной техник",
      "малиновый пиджак",
      "воспитатель",
    ],
    gentlemen: [
      "джентльмены удачи",
      "птичку жалко",
      "доцент",
    ],
    meeting: [
      "вор должен сидеть в тюрьме",
      "и не в деревне у тёти",
      "шарапов",
      "жеглов",
      "чёрная кошка",
      "место встречи изменить нельзя",
      "мурка",
      "жили бы на одну зарплату",
    ],
    joker: [
      "you get what you deserve",
      "ты заслужил",
      "put on a happy face",
      "arthur fleck",
      "you wouldn't get it",
      "я не сумасшедший",
      "смех",
    ],
    "dark-knight": [
      "why so serious",
      "почему так серьёзно",
      "either die a hero",
      "live long enough",
      "chaos is a ladder",
      "some men just want to watch the world burn",
      "я джокер",
      "бэтмен",
      "харви дент",
    ],
    wolf: [
      "продай мне эту ручку",
      "sell me this pen",
      "jordan belfort",
      "я не ухожу",
      "stratton oakmont",
      "волк с уолл стрит",
    ],
    social: [
      "a million dollars isn't cool",
      "you better lawyer up",
      "if you guys were the inventors",
      "winklevoss",
      "facebook",
      "марк цукерберг",
      "drop out",
    ],
    drive: [
      "i drive",
      "five minutes",
      "scorpion jacket",
      "я водитель",
      "пять минут",
      "ночной гонщик",
    ],
    blade: [
      "я видел такое что вам не приснится",
      "tears in rain",
      "like tears in rain",
      "репликант",
      "время умирать",
      "декарт",
    ],
    "blade-old": [
      "tears in rain",
      "like tears in rain",
      "all those moments will be lost",
      "репликант",
      "больше света",
    ],
    interstellar: [
      "do not go gentle",
      "into that good night",
      "love is the one thing",
      "murphy's law",
      "мы фермеры",
      "кукуруза",
      "червоточина",
      "купер",
    ],
    gladiator: [
      "are you not entertained",
      "strength and honor",
      "maximus",
      "win the crowd",
      "отец брата",
      "я раб",
      "рим",
    ],
    leon: [
      "i like milk",
      "everyone has a choice",
      "mathilda",
      "растение",
      "я чистильщик",
      "no women no kids",
    ],
    shutter: [
      "which would be worse",
      "teddy daniels",
      "остров проклятых",
      "рахед",
      "кто я",
    ],
    "breaking-bad": [
      "i am the one who knocks",
      "я тот кто стучит",
      "say my name",
      "скажи моё имя",
      "heisenberg",
      "хайзенберг",
      "yeah science",
      "i am the danger",
      "я опасность",
      "walter white",
      "jesse pinkman",
      "лучше звоните солу",
    ],
    got: [
      "winter is coming",
      "зима близко",
      "you know nothing jon snow",
      "ты ничего не знаешь джон снег",
      "a lannister always pays his debts",
      "драконы",
      "iron throne",
      "валенуар",
      "холд дверь",
      "hodor",
      "the night is dark",
    ],
    "irony-fate": [
      "с легким паром",
      "с лёгким паром",
      "третья улица строителей",
      "дом 25",
      "заливная рыба",
      "надежда",
      "ипполит",
      "женя лукашин",
      "никто не придёт",
    ],
    "irony-fate-2": [
      "третья улица строителей",
      "с легким паром снова",
      "женечка",
    ],
    godfather: [
      "предложение от которого нельзя отказаться",
      "an offer he can't refuse",
      "sleeps with the fishes",
      "leave the gun take the cannoli",
      "i'm gonna make him an offer",
      "это семейное",
      "сонни",
      "майкл",
    ],
    "godfather-2": [
      "keep your friends close",
      "друзей держи близко",
      "врагов ещё ближе",
      "майкл корлеоне",
    ],
    "star-wars": [
      "да пребудет с тобой сила",
      "may the force be with you",
      "help me obi wan",
      "that's no moon",
      "это не луна",
      "use the force",
      "я твой отец",
      "эти не те дроиды",
    ],
    empire: [
      "я твой отец",
      "i am your father",
      "luke i am your father",
      "нет это неправда",
      "do or do not",
      "there is no try",
      "йода",
    ],
    forrest: [
      "life is like a box of chocolates",
      "жизнь как коробка шоколадных конфет",
      "run forrest run",
      "беги форрест",
      "stupid is as stupid does",
      "jenny",
      "ping pong",
    ],
    shawshank: [
      "hope is a good thing",
      "надежда это хорошо",
      "get busy living",
      "or get busy dying",
      "andy dufresne",
      "реди",
      "побег",
    ],
    "home-alone": [
      "keep the change ya filthy animal",
      "merry christmas ya filthy animal",
      "kevin mccallister",
      "я забыл кевина",
      "один дома",
      "бандиты",
    ],
    terminator: [
      "i'll be back",
      "я вернусь",
      "hasta la vista baby",
      "come with me if you want to live",
    ],
    "terminator-2": [
      "hasta la vista baby",
      "i'll be back",
      "come with me if you want to live",
      "я вернусь",
      "жидкий металл",
      "джон коннор",
    ],
    casablanca: [
      "here's looking at you kid",
      "play it sam",
      "play it again sam",
      "we'll always have paris",
      "of all the gin joints",
      "луис это начало прекрасной дружбы",
      "as time goes by",
    ],
    hp1: [
      "you're a wizard harry",
      "yer a wizard harry",
      "ты волшебник гарри",
      "девять и три четверти",
      "hogwarts",
      "хогвартс",
      "expelliarmus",
      "платформа девять и три четверти",
      "гарри поттер",
    ],
    lotr: [
      "you shall not pass",
      "ты не пройдёшь",
      "my precious",
      "моя прелесть",
      "one ring to rule them all",
      "одно кольцо",
      "frodo",
      "gandalf",
      "фродо",
      "even the smallest person",
    ],
    frozen: [
      "let it go",
      "отпусти и забудь",
      "the cold never bothered me",
      "do you want to build a snowman",
      "хочешь слепить снеговика",
      "эльза",
      "анна",
    ],
    "iron-man": [
      "i am iron man",
      "я железный человек",
      "jarvis",
      "i love you 3000",
      "genius billionaire",
    ],
    avengers: [
      "avengers assemble",
      "мстители общий сбор",
      "on your left",
      "я железный человек",
      "i can do this all day",
    ],
    office: [
      "that's what she said",
      "это то что она сказала",
      "bears beets battlestar galactica",
      "i declare bankruptcy",
      "дандер миффлин",
      "майкл скотт",
      "identity theft is not a joke",
    ],
    mandalorian: [
      "this is the way",
      "это путь",
      "i have spoken",
      "baby yoda",
      "grogu",
      "малыш",
    ],
    "death-note": [
      "i am justice",
      "я бог нового мира",
      "kira",
      "тетрадь смерти",
      "ryuk",
      "я кира",
    ],
    "one-piece": [
      "я стану королём пиратов",
      "king of the pirates",
      "meat",
      "nakama",
      "соломенная шляпа",
      "луффи",
    ],
    naruto: [
      "я стану хокаге",
      "believe it",
      "dattebayo",
      "даттебаё",
      "расенган",
      "саске",
    ],
    friends: [
      "how you doing",
      "ну как дела",
      "we were on a break",
      "у нас был перерыв",
      "pivot",
      "поворачивай",
      "central perk",
      "джо",
      "smelly cat",
      "the one where",
    ],
    stalker: [
      "зона",
      "комната",
      "желание",
      "проводник",
      "сталкер",
      "мясорубка",
      "писатель профессор",
    ],
    "operation-y": [
      "надо фёдор надо",
      "кто не работает тот ест",
      "наваждение",
      "операция ы",
      "шурик",
      "трус балбес бывалый",
    ],
    caucasian: [
      "студент который всегда готов",
      "ай да пушкин",
      "инжир",
      "кавказская пленница",
      "саахов",
      "третий тост",
      "за здравие",
    ],
    "office-romance": [
      "новосельцев",
      "калугина",
      "секретарша",
      "я буду жаловаться",
      "статистика знает всё",
      "служебный роман",
    ],
    "moscow-tears": [
      "в сорок лет жизнь только начинается",
      "москва слезам не верит",
      "катя тихомирова",
      "шоколадная фабрика",
    ],
    "kin-dza-dza": [
      "ку",
      "пепелац",
      "чаппа",
      "цак",
      "планета плюк",
      "пацак",
      "кин дза дза",
    ],
    "guest-future": [
      "алиса селезнёва",
      "коллетор",
      "миэлофон",
      "гостья из будущего",
      "москва 2084",
    ],
    "twelve-chairs": [
      "остап бендер",
      "командовать парадом буду я",
      "стулья",
      "киса воробьянинов",
      "ледокол",
    ],
    "national-hunt": [
      "особенности национальной охоты",
      "финн",
      "баня",
      "медведь",
    ],
    grom: [
      "майор гром",
      "чумной доктор",
      "петербург",
      "игорь гром",
    ],
    "word-of-boy": [
      "слово пацана",
      "казань",
      "маларь",
      "яма",
      "чушпан",
      "чушпаны",
      "ты чушпан",
      "пацан сказал пацан сделал",
    ],
    kitchen: [
      "шеф",
      "виктор баранов",
      "клоп",
      "кухня сериал",
      "ресторан",
    ],
    "green-mile": [
      "джон коффи",
      "убить мышь",
      "зелёная миля",
      "электрический стул",
      "чудо",
    ],
    titanic: [
      "i'm the king of the world",
      "я король мира",
      "never let go",
      "джек доусон",
      "роза",
      "heart of the ocean",
      "рисунок",
    ],
    "back-future": [
      "great scott",
      "1 21 gigawatts",
      "where we're going we don't need roads",
      "дороги нам не нужны",
      "делorean",
      "марти",
      "док",
    ],
    shrek: [
      "огры как луковицы",
      "onions have layers",
      "я осёл",
      "жить болотом",
      "somebody once told me",
    ],
    "lion-king": [
      "hakuna matata",
      "помни кто ты",
      "remember who you are",
      "круг жизни",
      "circle of life",
      "симба",
      "муфаса",
    ],
    pirates: [
      "why is the rum gone",
      "где ром",
      "savvy",
      "this is the day you will always remember",
      "джек воробей",
      "чёрная жемчужина",
      "пиратский кодекс",
    ],
    intouchables: [
      "1 1",
      "неприкасаемые",
      "earth wind and fire",
      "дрисс",
      "филипп",
      "парализованный",
    ],
    parasite: [
      "jessica only child",
      "план",
      "полуподвал",
      "запах",
      "богатые и бедные",
      "дождь",
    ],
    whiplash: [
      "not quite my tempo",
      "не мой темп",
      "were you rushing",
      "good job",
      "барабаны",
      "флетчер",
    ],
    "john-wick": [
      "baba yaga",
      "continental",
      "они убили мою собаку",
      "карандаш",
      "джон уик",
    ],
    "mad-max": [
      "witness me",
      "witness",
      "what a lovely day",
      "furiosa",
      "chrome",
      "war boys",
    ],
    dune: [
      "the spice must flow",
      "lisan al gaib",
      "fear is the mind killer",
      "страх убийца разума",
      "песчаный червь",
      "арракис",
    ],
    oppenheimer: [
      "now i am become death",
      "destroyer of worlds",
      "я смерть разрушитель миров",
      "тринити",
      "бомба",
    ],
    barbie: [
      "i'm just ken",
      "я просто кен",
      "hi barbie",
      "пластиковый мир",
      "патриархат",
    ],
    sherlock: [
      "the game is on",
      "игра началась",
      "high functioning sociopath",
      "джон ватсон",
      "221b",
      "элементарно",
    ],
    stranger: [
      "friends don't lie",
      "upside down",
      "перевёрнутый мир",
      "eggo",
      "eleven",
      "одиннадцать",
      "hawkins",
    ],
    squid: [
      "red light green light",
      "тише едешь",
      "игра в кальмара",
      "456",
      "далькона",
      "маска",
    ],
    witcher: [
      "toss a coin to your witcher",
      "брось монетку",
      "геральт",
      "хук",
      "destined",
    ],
    house: [
      "everybody lies",
      "все врут",
      "it's not lupus",
      "это не волчанка",
      "викадин",
      "хаус",
    ],
    "money-heist": [
      "bella ciao",
      "профессор",
      "бумажный дом",
      "токийо",
      "маска дали",
    ],
    spider: [
      "with great power",
      "большая сила",
      "friendly neighborhood",
      "паучок",
      "дядя бен",
    ],
    deadpool: [
      "maximum effort",
      "chimichanga",
      "четвертая стена",
      "wade wilson",
      "красивый урод",
    ],
    goodfellas: [
      "as far back as i can remember",
      "я всегда хотел быть гангстером",
      "funny how",
      "how am i funny",
    ],
    scarface: [
      "say hello to my little friend",
      "скажи привет моему маленькому другу",
      "the world is yours",
      "мир твой",
      "tony montana",
    ],
    "taxi-driver": [
      "you talkin to me",
      "ты говоришь со мной",
      "travis bickle",
      "are you talkin to me",
    ],
    "silence-lambs": [
      "hello clarice",
      "кларисса",
      "a census taker",
      "Hannibal",
      "ягнёнок",
      "завари чай",
    ],
    se7en: [
      "what's in the box",
      "что в коробке",
      "what's in the boxx",
      "семь смертных грехов",
      "john doe",
    ],
    "usual-suspects": [
      "the greatest trick the devil ever pulled",
      "кайзер сёзе",
      "keyser soze",
      "verbal kint",
    ],
    "die-hard": [
      "yippee ki yay",
      "йиппи кай эй",
      "now i have a machine gun",
      "наккатоми",
      "джон маклейн",
    ],
    jaws: [
      "we're gonna need a bigger boat",
      "нам понадобится лодка побольше",
      "акула",
      "you're gonna need a bigger boat",
    ],
    alien: [
      "in space no one can hear you scream",
      "в космосе никто не услышит",
      "ксеноморф",
      "рипли",
    ],
    aliens: [
      "get away from her you bitch",
      "game over man",
      "морпехи",
    ],
    predator: [
      "if it bleeds we can kill it",
      "если оно кровоточит",
      "get to the chopper",
      "к вертолёту",
    ],
    rocky: [
      "adrian",
      "адриан",
      "yo adrian",
      "going the distance",
      "филадельфия",
    ],
    indiana: [
      "snakes why did it have to be snakes",
      "змеи почему змеи",
      "it belongs in a museum",
      "это принадлежит музею",
    ],
    jurassic: [
      "life finds a way",
      "жизнь находит путь",
      "hold on to your butts",
      "welcome to jurassic park",
    ],
    et: [
      "et phone home",
      "позвони домой",
      "phone home",
    ],
    "kill-bill": [
      "wiggle your big toe",
      "невеста",
      "жёлтый комбинезон",
      "five point palm",
    ],
    django: [
      "i like the way you die boy",
      "джанго",
      "доктор шульц",
    ],
    inglourious: [
      "say au revoir to your nazi balls",
      "карточка",
      "итальянский",
      "ханс ланда",
    ],
    reservoir: [
      "are you gonna bark all day",
      "мистер розовый",
      "ухо",
      "like a virgin",
    ],
    amelie: [
      "маленькие радости",
      "гном",
      "монмартр",
      "крейон",
    ],
    spirited: [
      "хаку",
      "тихиро",
      "баня духов",
      "безликий",
      "каонаси",
    ],
    "your-name": [
      "как тебя зовут",
      "комета",
      "мунэока",
      "мицуха",
    ],
    oldboy: [
      "laugh and the world laughs with you",
      "15 лет",
      "молоток",
      "who are you",
    ],
    "train-busan": [
      "зомби в поезде",
      "пусан",
      "держись за поручень",
    ],
    arrival: [
      "language is the first weapon",
      "гептаподы",
      "нелинейное время",
    ],
    martian: [
      "i'm gonna have to science the shit out of this",
      "картошка на марсе",
      "я буду заниматься наукой",
    ],
    gravity: [
      "in the void",
      "отсоединись",
      "houston",
    ],
    lalaland: [
      "city of stars",
      "город звёзд",
      "here's to the ones who dream",
    ],
    "get-out": [
      "get out",
      "уезжай",
      "sunken place",
      "погружение",
    ],
    "quiet-place": [
      "don't make a sound",
      "не издавай звука",
      "тишина",
    ],
    it: [
      "you'll float too",
      "мы все плывём",
      "пеннивайз",
      "клоун",
    ],
    scream: [
      "what's your favorite scary movie",
      "какой твой любимый фильм ужасов",
      "ghostface",
    ],
    moana: [
      "you're welcome",
      "океан выбрал",
      "maui",
      "how far i'll go",
    ],
    "toy-story": [
      "to infinity and beyond",
      "до бесконечности и далее",
      "there's a snake in my boot",
      "базз",
    ],
    nemo: [
      "just keep swimming",
      "просто плыви",
      "short term memory loss",
    ],
    up: [
      "adventure is out there",
      "приключение ждёт",
      "шарики",
      "элли",
    ],
    coco: [
      "remember me",
      "помните меня",
      "un poco loco",
      "дядя коко",
    ],
    "inside-out": [
      "sadness",
      "радость",
      "штаб эмоций",
      "core memories",
    ],
    walle: [
      "eve",
      "directive",
      "earth",
    ],
    httyd: [
      "беззубик",
      "иккинг",
      "a downed dragon",
    ],
    despicable: [
      "minions",
      "миньоны",
      "bee do",
      "гру",
    ],
    guardians: [
      "i am groot",
      "я грут",
      "awesome mix",
      "star lord",
    ],
    "black-panther": [
      "wakanda forever",
      "ваканда навсегда",
    ],
    logan: [
      "wolverine",
      "росомаха",
      "old man",
    ],
    psycho: [
      "shower scene",
      "norman bates",
      "a boy's best friend is his mother",
      "мотель бейтса",
    ],
    "2001": [
      "open the pod bay doors",
      "i'm sorry dave",
      "hal 9000",
      "монолит",
      "daisy daisy",
    ],
    clockwork: [
      "ultra violence",
      "ludovico technique",
      "i was cured all right",
      "молоко",
    ],
    apocalypse: [
      "i love the smell of napalm in the morning",
      "the horror",
      "never get out of the boat",
      "charlie don't surf",
    ],
    "full-metal": [
      "this is my rifle",
      "born to kill",
      "me so horny",
      "private joker",
    ],
    "saving-ryan": [
      "earn this",
      "james ryan",
      "омаха бич",
    ],
    schindler: [
      "whoever saves one life saves the world entire",
      "power is when we have every justification",
      "список",
    ],
    braveheart: [
      "they may take our lives but they'll never take our freedom",
      "freedom",
      "свобода",
      "william wallace",
    ],
    heat: [
      "don't let yourself get attached",
      "a guy told me one time",
      "кофе хана и макколи",
    ],
    departed: [
      "i'm the guy who does his job",
      "who's the rat",
      "costello",
    ],
    "no-country": [
      "what's the most you ever lost on a coin toss",
      "call it",
      "монетка",
      "chigurh",
    ],
    "there-will": [
      "i drink your milkshake",
      "молочный коктейль",
      "i am a family man",
    ],
    "big-lebowski": [
      "the dude abides",
      "this aggression will not stand man",
      "where is the money lebowski",
      "ковёр",
    ],
    oceans11: [
      "rusty",
      "danny ocean",
      "we're gonna rob three casinos",
    ],
    "catch-me": [
      "frank abagnale",
      "the yankees win",
      "чеки",
      "поймай меня",
    ],
    "gone-girl": [
      "cool girl",
      "я крутая девчонка",
      "amazing amy",
    ],
    zodiac: [
      "this is the zodiac speaking",
      "i am not afraid of the zodiac",
    ],
    prisoners: [
      "where is she",
      "pray for us",
    ],
    sicario: [
      "you are not a wolf",
      "and this is the land of wolves",
    ],
    nightcrawler: [
      "if it bleeds it leads",
      "i'd like to think i'd never cut a throat",
    ],
    "ex-machina": [
      "turing test",
      "ava",
      "bluebook",
    ],
    her: [
      "os1",
      "samantha",
      "theodore",
      "я влюблён в ос",
    ],
    "top-gun": [
      "i feel the need",
      "the need for speed",
      "talk to me goose",
      "маверик",
    ],
    "top-gun-2": [
      "talk to me goose",
      "don't think just do",
      "the need for speed",
    ],
    "mi-fallout": [
      "your mission should you choose to accept it",
      "this message will self destruct",
      "ethan hunt",
    ],
    "john-wick-4": [
      "baba yaga",
      "how you doin john",
      "continental",
    ],
    "knives-out": [
      "i suspect foul play",
      "blanc",
      "doughnut",
    ],
    everything: [
      "hot dog fingers",
      "in another life i would have really liked",
      "bagel",
      "googly eyes",
    ],
    "eeaaowait": [
      "lisan al gaib",
      "power over spice is power over all",
      "я пустынная мышь",
    ],
    "spiderman-into": [
      "anyone can wear the mask",
      "leap of faith",
      "what's up danger",
      "miles morales",
    ],
    "kungfu-panda": [
      "there is no secret ingredient",
      "skadoosh",
      "yesterday is history",
    ],
    zootopia: [
      "try everything",
      "i popped the weasel",
      "judy hopps",
    ],
    encanto: [
      "we don't talk about bruno",
      "bruno",
      "no se habla de bruno",
    ],
    soul: [
      "spark",
      "joe gardner",
      "the great before",
    ],
    ratatouille: [
      "anyone can cook",
      "not everyone can become a great artist",
      "remy",
    ],
    incredibles: [
      "no capes",
      "i'm not happy bob",
      "dash",
    ],
    "finding-dory": [
      "just keep swimming",
      "i suffer from short term memory loss",
    ],
    "a-star": [
      "shallow",
      "maybe it's time to let the old ways die",
    ],
    bohemian: [
      "we are the champions",
      "is this the real life",
      "live aid",
    ],
    "big-short": [
      "the bubble",
      "subprime",
      "truth is like poetry",
    ],
    moneyball: [
      "how can you not be romantic about baseball",
      "adapt or die",
    ],
    imitation: [
      "sometimes it is the people no one imagines",
      "are you paying attention",
      "enigma",
    ],
    revenant: [
      "as long as you can still grab a breath",
      "revenge is in god's hands",
    ],
    notebook: [
      "if you're a bird i'm a bird",
      "it wasn't over",
      "noah",
    ],
    "pretty-woman": [
      "big mistake huge",
      "royalty",
      "pretty woman walking down the street",
    ],
    "3idiots": [
      "all is well",
      "aal izz well",
      "pursue excellence",
    ],
    slumdog: [
      "it is written",
      "who wants to be a millionaire",
    ],
    sopranos: [
      "those who want respect",
      "gabagool",
      "toni soprano",
      "я не в настроении",
    ],
    wire: [
      "all the pieces matter",
      "you come at the king",
      "the game is the game",
      "балтимор",
    ],
    "better-call": [
      "better call saul",
      "it's all good man",
      "саул гудман",
      "jimmy mcgill",
    ],
    "true-detective": [
      "time is a flat circle",
      "время плоский круг",
      "the world needs bad men",
      "расти коле",
    ],
    chernobyl: [
      "not a hero",
      "rbrmk reactor",
      "what is the cost of lies",
      "цена лжи",
    ],
    "dark-netflix": [
      "the question is not if but when",
      "sic mundus creatus est",
      "винден",
    ],
    "black-mirror": [
      "nosedive",
      "white christmas",
      "san junipero",
      "технология против нас",
    ],
    "last-of-us": [
      "endure and survive",
      "look for the light",
      "джоэл",
      "элли",
      "clickers",
    ],
    succession: [
      "l to the og",
      "you are not serious people",
      "boar on the floor",
    ],
    "the-bear": [
      "yes chef",
      "да шеф",
      "hands",
      "let it rip",
    ],
    arcane: [
      "jinx",
      "powder",
      "oil and water",
      "заун",
    ],
    boys: [
      "homelander",
      "supe",
      "the boys",
      "бьючер",
    ],
    andor: [
      "rebellions are built on hope",
      "i've been in this fight since i was six",
      "one way out",
    ],
    "house-dragon": [
      "fire and blood",
      "the song of ice",
      "драконы",
      "aegon",
    ],
    wednesday: [
      "i prefer to be feared",
      "я уэнсдей аддамс",
      "невермор",
      "thing",
    ],
    peaky: [
      "by order of the peaky blinders",
      "in the bleak midwinter",
      "томас шелби",
    ],
    "doctor-who": [
      "wibbly wobbly timey wimey",
      "allons y",
      "тардис",
      "я доктор",
    ],
    himym: [
      "suit up",
      "легенда ждал",
      "true story",
      "blue french horn",
      "барни стинсон",
    ],
    bigbang: [
      "bazinga",
      "базинга",
      "soft kitty",
      "шелдон",
    ],
    lost: [
      "we have to go back",
      "4 8 15 16 23 42",
      "the island",
      "see you in another life",
    ],
    "prison-break": [
      "the tattoo is the plan",
      "майкл скофилд",
      "sucre",
    ],
    dexter: [
      "tonight's the night",
      "dark passenger",
      "тёмный попутчик",
    ],
    narcos: [
      "plata o plomo",
      "пабло эскобар",
      "silver or lead",
    ],
    westworld: [
      "these violent delights",
      "have violent ends",
      "does it look like i have a choice",
    ],
    mindhunter: [
      "proactive",
      "профайлинг",
      "holden ford",
    ],
    "alice-border": [
      "games",
      "карты",
      "джикер",
    ],
    "attack-titan": [
      "tatakae",
      "уничтожить титанов",
      "эрен йегер",
      "sasageyo",
    ],
    "demon-slayer": [
      "незуко",
      "танджиро",
      "hinokami",
    ],
    jujutsu: [
      "throughout heaven and earth",
      "i alone am the honored one",
      "годзё",
    ],
    "spy-family": [
      "anya waku waku",
      "операция страйк",
      "peanuts",
    ],
    "rick-morty": [
      "wubba lubba dub dub",
      "i'm pickle rick",
      "портальная пушка",
      "schwifty",
    ],
    "south-no": [
      "doh",
      "d'oh",
      "eat my shorts",
      "гомер",
    ],
    brooklyn: [
      "cool cool cool cool",
      "noice",
      "title of your sex tape",
      "nine nine",
    ],
    community: [
      "six seasons and a movie",
      "darkest timeline",
      "troy and abed in the morning",
    ],
    parks: [
      "treat yo self",
      "li'l sebastian",
      "лесли ноуп",
    ],
    "white-lotus": [
      "these rich people",
      "resort",
      "майк уайт",
    ],
    euphoria: [
      "rue",
      "zendaya",
      "special episode",
    ],
    "ted-lasso": [
      "be curious not judgemental",
      "believe",
      "football is life",
      "biscuits",
    ],
    severance: [
      "the work is mysterious and important",
      "innie",
      "outie",
      "refine",
    ],
    fallout: [
      "war never changes",
      "vault tec",
      "nuka cola",
      "okey dokey",
    ],
    from: [
      "don't go out at night",
      "talisman",
      "the trees",
    ],
    sandman: [
      "dream of the endless",
      "morpheus",
      "the sandman",
    ],
    umbrella: [
      "number five",
      "the apocalypse is cancelled",
    ],
    lucifer: [
      "what is it you truly desire",
      "devil of hell",
      "люцифер морнингстар",
    ],
    supernatural: [
      "saving people hunting things",
      "the family business",
      "driver picks the music",
      "impala",
    ],
    "vampire-diaries": [
      "hello brother",
      "mystic falls",
      "dear diary",
    ],
    bridgerton: [
      "dear gentle reader",
      "lady whistledown",
      "the ton",
    ],
    outlander: [
      "sassenach",
      "jamie fraser",
      "dinna fash",
    ],
    vikings: [
      "odin",
      "valhalla",
      "ragnar lothbrok",
    ],
    "last-kingdom": [
      "destiny is all",
      "wyrd bid ful araed",
      "утреду",
    ],
    "house-of-cards": [
      "you might very well think that",
      "i couldn't possibly comment",
      "frank underwood",
    ],
    invincible: [
      "think mark",
      "that's the neat part you don't",
      "omniman",
    ],
    scrubs: [
      "my name is jd",
      "where do you think we are",
    ],
    "modern-family": [
      "phil dunphy",
      "claire",
      "how you doin lily",
    ],
    "always-sunny": [
      "the implication",
      "dennis system",
      "wildcard bitches",
    ],
    shogun: [
      "anjin",
      "toranaga",
      "crimp",
    ],
    "white-sun": [
      "восток дело тонкое",
      "таможня даёт добро",
      "сухов",
      "петруха",
      "гильзы",
      "джамал",
    ],
    mimino: [
      "ларису ивановну хочу",
      "валерико кока",
      "я мимино",
      "палермо",
    ],
    "dog-heart": [
      "разруха не в клозетах а в головах",
      "абвырвалг",
      "дать шприц",
      "шариков",
      "преображенский",
    ],
    "love-pigeons": [
      "вася кузякин",
      "курорт",
      "надя",
      "голуби",
    ],
    garage: [
      "кооператив",
      "собрание пайщиков",
      "гараж рязанов",
    ],
    afonya: [
      "афоня сантехник",
      "водочка",
    ],
    "beware-car": [
      "дети цветы жизни",
      "деточкин",
      "угон у богатых",
    ],
    "formula-love": [
      "граф калиостро",
      "прасковья тулупова",
      "любовный эликсир",
    ],
    charodei: [
      "три белых коня",
      "скажите девушки",
      "институт волшебства",
    ],
    "carnival-night": [
      "есть ли жизнь на марсе",
      "огурцов",
      "пять минут",
    ],
    electronics: [
      "сыроежкин",
      "я робот",
      "электроник",
      "сыркин",
    ],
    "golden-calf": [
      "командовать парадом буду я",
      "остап бендер",
      "автопробег",
    ],
    bumer: [
      "бумер",
      "коламбия",
      "девяностые",
      "тазик",
    ],
    zhmurki: [
      "чемодан",
      "перепутали",
      "бандиты девяностых",
    ],
    "night-watch": [
      "светлые и тёмные",
      "гесер",
      "дозор",
    ],
    "election-day": [
      "наш кандидат",
      "радио",
      "день выборов",
    ],
    "legend-17": [
      "харламов",
      "суперсерия",
      "канадец",
    ],
    "moving-up": [
      "мюнхен 72",
      "сборная ссср",
      "баскетбол",
    ],
    holop: [
      "крепостное право",
      "барская усадьба",
      "холоп",
    ],
    cheburashka: [
      "я чебурашка",
      "геша",
      "апельсин",
    ],
    "ninth-company": [
      "афганистан",
      "девятая рота",
      "высота",
    ],
    liquidation: [
      "гоцман",
      "одесса",
      "бандиты после войны",
    ],
    brigade: [
      "саша белый",
      "белоо",
      "братва",
    ],
    interns: [
      "быков",
      "интерны",
      "кто здесь врач",
    ],
    univer: [
      "универ общага",
      "маша",
      "кузя",
    ],
    "real-boys": [
      "нижний тагил",
      "колян",
      "реальные пацаны",
    ],
    rublevka: [
      "полицейский с рублёвки",
      "гриша измайлов",
    ],
    method: [
      "меглин",
      "есеня",
      "метод",
    ],
    topi: [
      "болото",
      "топи",
      "пропавшие студенты",
    ],
    "streets-lights": [
      "менты",
      "улицы разбитых фонарей",
      "опера",
    ],
    soldiers: [
      "дембель",
      "учебка",
      "солдаты сериал",
    ],
    svaty: [
      "будько",
      "сваты",
      "дача",
    ],
    assa: [
      "мы ждём перемен",
      "виктор цой",
      "перемен требуют наши сердца",
    ],
    needle: [
      "цой",
      "игла",
      "алма ата",
    ],
    solaris: [
      "океан солярис",
      "харри",
      "кельвин",
    ],
    "andrei-rublev": [
      "колокол",
      "рублёв",
      "тарковский",
    ],
    "come-see": [
      "иди и смотри",
      "флёра",
      "каратели",
    ],
    "only-old-men": [
      "маэстро",
      "в бой идут одни старики",
      "песня",
    ],
    officers: [
      "есть такая профессия родину защищать",
      "офицер",
    ],
    "seventeen-moments": [
      "штирлиц задумался",
      "мюллер",
      "радистка кэт",
      "семнадцать мгновений",
    ],
    "sherlock-holmes-ru": [
      "элементарно ватсон",
      "ливанов",
      "баскервиль",
    ],
    leviathan: [
      "левиафан",
      "дом снесут",
      "чиновник",
    ],
    "grom-2": [
      "призрак",
      "майор гром игра",
    ],
    durak: [
      "трещина в общежитии",
      "сантехник быков",
    ],
    gruz: [
      "груз 200",
      "балабанов",
    ],
    challenge: [
      "хирург в космосе",
      "вызов фильм",
      "мкс",
    ],
  };

  (window.POFRAZE_FILMS || []).forEach(function (film) {
    var add = extra[film.id];
    if (!add) return;
    add.forEach(function (q) {
      var t = String(q || "").trim();
      if (t.length < 2 || t === "skip" || t.indexOf("insta") !== -1) return;
      if (film.quotes.indexOf(t) === -1 && film.quotes.indexOf(q) === -1) {
        film.quotes.push(t);
      }
    });
  });
})();
