(function () {
  function key(s) {
    return String(s || "")
      .toLowerCase()
      .replace(/ё/g, "е")
      .replace(/['’]/g, "")
      .replace(/[^a-zа-я0-9]+/g, " ")
      .replace(/\s+/g, " ")
      .trim();
  }

  var dub = {
    "there is no spoon": "ложки нет",
    "follow the white rabbit": "следуй за белым кроликом",
    "i know kung fu": "я знаю кунг фу",
    "welcome to the real world": "добро пожаловать в реальный мир",
    "unfortunately no one can be told what the matrix is": "к сожалению матрицу нельзя объяснить",
    "the first rule of fight club is you do not talk about fight club": "первое правило бойцовского клуба никому не рассказывать о бойцовском клубе",
    "you are not your fucking khakis": "ты не свои чёртовы брюки",
    "his name is tyler durden": "его зовут тайлер дёрден",
    "i am jacks complete lack of surprise": "я полное отсутствие удивления джека",
    "the things you own end up owning you": "вещи которыми ты владеешь в итоге владеют тобой",
    "may the force be with you": "да пребудет с тобой сила",
    "thats no moon": "это не луна",
    "help me obi wan kenobi youre my only hope": "помоги мне оби ван кеноби ты моя единственная надежда",
    "help me obi wan kenobi": "помоги мне оби ван кеноби",
    "help me obi wan": "помоги мне оби ван",
    "these arent the droids youre looking for": "это не те дроиды которых вы ищете",
    "use the force": "используй силу",
    "i am your father": "я твой отец",
    "no i am your father": "нет я твой отец",
    "luke i am your father": "люк я твой отец",
    "do or do not there is no try": "делай или не делай не надо пытаться",
    "do or do not": "делай или не делай",
    "there is no try": "не надо пытаться",
    "i am a jedi like my father before me": "я джедай как мой отец",
    "chewie were home": "чуви мы дома",
    "rebellions are built on hope": "восстания строятся на надежде",
    "ill be back": "я вернусь",
    "i ll be back": "я вернусь",
    "come with me if you want to live": "пойдём со мной если хочешь жить",
    "hasta la vista baby": "hasta la vista baby",
    "you talkin to me": "ты это мне",
    "you talking to me": "ты это мне",
    "heres looking at you kid": "я смотрю на тебя крошка",
    "well always have paris": "у нас всегда останется париж",
    "of all the gin joints in all the towns in all the world she walks into mine": "из всех баров во всех городах мира она вошла в мой",
    "play it sam": "сыграй сэм",
    "play it again sam": "сыграй это снова сэм",
    "frankly my dear i dont give a damn": "откровенно говоря моя дорогая мне наплевать",
    "frankly my dear": "откровенно говоря моя дорогая",
    "after all tomorrow is another day": "в конце концов завтра будет новый день",
    "theres no place like home": "нет места лучше дома",
    "toto ive a feeling were not in kansas anymore": "тото мне кажется мы уже не в канзасе",
    "lions and tigers and bears oh my": "львы тигры и медведи о боже",
    "rosebud": "роузбад",
    "youre gonna need a bigger boat": "нам понадобится лодка побольше",
    "you cant handle the truth": "ты не выдержишь правды",
    "show me the money": "покажи мне деньги",
    "you complete me": "ты делаешь меня целым",
    "you had me at hello": "ты взял меня на здравствуйте",
    "houston we have a problem": "хьюстон у нас проблема",
    "houston weve had a problem": "хьюстон у нас проблема",
    "failure is not an option": "провал недопустим",
    "i see dead people": "я вижу мёртвых",
    "why so serious": "почему так серьёзно",
    "wanna know how i got these scars": "хочешь узнать откуда у меня шрамы",
    "some men just want to watch the world burn": "некоторые просто хотят смотреть как горит мир",
    "you either die a hero or you live long enough to see yourself become the villain": "либо умрёшь героем либо проживёшь достаточно долго чтобы стать злодеем",
    "you shall not pass": "ты не пройдёшь",
    "my precious": "моя прелесть",
    "one ring to rule them all": "одно кольцо чтобы править всеми",
    "even the smallest person": "даже самый маленький",
    "im going on an adventure": "я отправляюсь в приключение",
    "i am fire i am death": "я огонь я смерть",
    "my friends you bow to no one": "друзья мои вы не кланяетесь никому",
    "for frodo": "за фродо",
    "shall i describe it to you or would you like me to find you a box": "описать тебе или найти ящик",
    "yer a wizard harry": "ты волшебник гарри",
    "youre a wizard harry": "ты волшебник гарри",
    "i solemnly swear that i am up to no good": "я торжественно клянусь что замышляю только шалость",
    "i must not tell lies": "я не должен лгать",
    "happiness can be found even in the darkest of times": "счастье можно найти даже в самые тёмные времена",
    "not my daughter you bitch": "только не мою дочь",
    "ill be in my bedroom making no noise and pretending that i dont exist": "я буду в спальне не шуметь и делать вид что меня нет",
    "life is like a box of chocolates": "жизнь как коробка шоколадных конфет",
    "life is like a box of chocolates you never know what youre gonna get": "жизнь как коробка шоколадных конфет никогда не знаешь что тебе попадётся",
    "run forrest run": "беги форрест беги",
    "stupid is as stupid does": "глуп тот кто глупости делает",
    "im the king of the world": "я король мира",
    "ill never let go jack": "я никогда тебя не отпущу джек",
    "get busy living or get busy dying": "или живи или умри",
    "hope is a good thing maybe the best of things": "надежда это хорошо может быть самое лучшее что есть",
    "hope is a good thing": "надежда это хорошо",
    "to infinity and beyond": "к бесконечности и далее",
    "theres a snake in my boot": "в моём сапоге змея",
    "just keep swimming": "просто плыви",
    "adventure is out there": "приключение ждёт",
    "remember me": "помните меня",
    "let it go": "отпусти и забудь",
    "the cold never bothered me anyway": "холод меня никогда не беспокоил",
    "do you want to build a snowman": "хочешь слепить снеговика",
    "into the unknown": "в неизвестность",
    "hakuna matata": "hakuna matata",
    "remember who you are": "помни кто ты",
    "ogres are like onions": "огры как луковицы",
    "onions have layers": "у луковиц есть слои",
    "i am iron man": "я железный человек",
    "avengers assemble": "мстители общий сбор",
    "i love you 3000": "я люблю тебя 3000",
    "on your left": "я слева",
    "we have a hulk": "а у нас есть халк",
    "im always angry": "я всегда злой",
    "i am inevitable": "я неизбежен",
    "why is gamora": "почему гамора",
    "hes a friend from work": "он друг с работы",
    "ive come to bargain": "я пришёл торговаться",
    "so was i": "я тоже",
    "i am groot": "я грут",
    "wakanda forever": "ваканда навсегда",
    "mutant and proud": "мутант и горжусь этим",
    "i am vengeance": "я возмездие",
    "with great power comes great responsibility": "с большой силой приходит большая ответственность",
    "maximum effort": "максимум усилий",
    "if youre nothing without the suit you shouldnt have it": "если ты ничто без костюма он тебе не нужен",
    "ive got red in my ledger": "у меня красное в книге",
    "winter is coming": "зима близко",
    "you know nothing jon snow": "ты ничего не знаешь джон сноу",
    "a lannister always pays his debts": "ланнистер всегда платит свои долги",
    "chaos is a ladder": "хаос это лестница",
    "the night is dark and full of terrors": "ночь темна и полна ужасов",
    "valar morghulis": "valar morghulis",
    "valar dohaeris": "valar dohaeris",
    "i am the one who knocks": "я тот кто стучит в дверь",
    "say my name": "скажи моё имя",
    "i am the danger": "я опасность",
    "yeah science": "да наука",
    "thats what she said": "это то что она сказала",
    "we were on a break": "у нас был перерыв",
    "how you doin": "ну как дела",
    "how you doing": "ну как дела",
    "pivot": "разворот",
    "suit up": "надевай костюм",
    "its gonna be legen wait for it dary": "это будет лег подожди ендарно",
    "everybody lies": "все лгут",
    "its not lupus": "это не волчанка",
    "the game is on": "игра началась",
    "friends dont lie": "друзья не лгут",
    "this is the way": "таков путь",
    "i have spoken": "я сказал",
    "yes chef": "да шеф",
    "you are not serious people": "вы несерьёзные люди",
    "by order of the peaky blinders": "по приказу острых козырьков",
    "we have to go back": "мы должны вернуться",
    "endure and survive": "терпи и выживай",
    "red light green light": "красный свет зелёный свет",
    "im pickle rick": "я огурчик рик",
    "wubba lubba dub dub": "wubba lubba dub dub",
    "bazinga": "bazinga",
    "im gonna make him an offer he cant refuse": "я сделаю ему предложение от которого он не сможет отказаться",
    "leave the gun take the cannoli": "оставь пистолет возьми канноли",
    "keep your friends close but your enemies closer": "держи друзей близко а врагов ещё ближе",
    "its not personal its strictly business": "это не лично это только бизнес",
    "as far back as i can remember i always wanted to be a gangster": "сколько себя помню я всегда хотел быть гангстером",
    "funny how": "забавно как",
    "say hello to my little friend": "скажи привет моему маленькому другу",
    "the world is yours": "мир принадлежит тебе",
    "good evening clarice": "добрый вечер кларисса",
    "hello clarice": "здравствуй кларисса",
    "i ate his liver with some fava beans and a nice chianti": "я съел его печень с бобами и хорошим кьянти",
    "a census taker once tried to test me": "переписчик как то пытался проверить меня",
    "whats in the box": "что в коробке",
    "the greatest trick the devil ever pulled was convincing the world he didnt exist": "величайший трюк дьявола убедить мир что его нет",
    "yippee ki yay": "йиппи кай эй",
    "in space no one can hear you scream": "в космосе никто не услышит твой крик",
    "get away from her you bitch": "отойди от неё",
    "if it bleeds we can kill it": "если оно кровоточит мы можем его убить",
    "get to the chopper": "к вертолёту",
    "yo adrian": "йо адриан",
    "life finds a way": "жизнь найдёт выход",
    "hold onto your butts": "держитесь",
    "why did it have to be snakes": "почему обязательно змеи",
    "it belongs in a museum": "это должно быть в музее",
    "et phone home": "и ти позвони домой",
    "roads where were going we dont need roads": "там куда мы едем дороги не нужны",
    "great scott": "великий скотт",
    "1 21 gigawatts": "1 21 гигаватта",
    "keep the change ya filthy animal": "сдачи не надо мерзкое животное",
    "merry christmas ya filthy animal": "счастливого рождества мерзкое животное",
    "heres johnny": "а вот и джонни",
    "all work and no play makes jack a dull boy": "труд без отдыха превращает джека в скучного мальчика",
    "are you not entertained": "вас это не развлекает",
    "what we do in life echoes in eternity": "то что мы делаем в жизни отзывается в вечности",
    "strength and honor": "сила и честь",
    "father to a murdered son husband to a murdered wife": "отец убитого сына муж убитой жены",
    "i like milk": "я люблю молоко",
    "is life always this hard or is it just when youre a kid": "жизнь всегда такая тяжёлая или только когда ты ребёнок",
    "which would be worse to live as a monster or to die as a good man": "что хуже жить монстром или умереть хорошим человеком",
    "do not go gentle into that good night": "не уходи смиренно в эту добрую ночь",
    "love is the one thing were capable of perceiving that transcends time and space": "любовь единственное что мы способны воспринимать сквозь время и пространство",
    "sell me this pen": "продай мне эту ручку",
    "a million dollars isnt cool you know whats cool a billion dollars": "миллион это не круто знаешь что круто миллиард",
    "you get what you fucking deserve": "ты получаешь то что заслужил",
    "i drive": "я водитель",
    "english motherfucker do you speak it": "по английски твою мать ты понимаешь",
    "a royal with cheese": "роял с сыром",
    "ezekiel 25 17": "иезекииль 25 17",
    "we need to go deeper": "нам нужно спуститься глубже",
    "an idea is like a virus": "идея как вирус",
    "you mustnt be afraid to dream a little bigger darling": "не бойся мечтать чуть масштабнее дорогая",
    "nobody puts baby in a corner": "никто не ставит малышку в угол",
    "you cant sit with us": "с нами не сидят",
    "on wednesdays we wear pink": "по средам мы носим розовое",
    "life moves pretty fast": "жизнь проносится слишком быстро",
    "ill have what shes having": "мне то же что и ей",
    "well nobodys perfect": "впрочем никто не совершенен",
    "as if": "как бы не так",
    "greed is good": "жадность это хорошо",
    "greed for lack of a better word is good": "жадность за неимением лучшего слова это хорошо",
    "im walkin here": "я тут иду",
    "im as mad as hell and im not going to take this anymore": "я зол как чёрт и больше не намерен это терпеть",
    "plastics": "пластмассы",
    "i coulda been a contender": "я мог бы быть претендентом",
    "i am big its the pictures that got small": "это я большая это картины стали мелкими",
    "gentlemen you cant fight in here this is the war room": "господа здесь нельзя драться это военный кабинет",
    "as you wish": "как пожелаете",
    "inconceivable": "немыслимо",
    "hello my name is inigo montoya you killed my father prepare to die": "меня зовут иниго монтойя ты убил моего отца приготовься умереть",
    "its just a flesh wound": "это всего лишь царапина",
    "hes not the messiah hes a very naughty boy": "он не мессия он очень непослушный мальчик",
    "o captain my captain": "о капитан мой капитан",
    "carpe diem seize the day": "лови момент",
    "how do you like them apples": "ну как тебе такие яблочки",
    "its not your fault": "это не твоя вина",
    "im an excellent driver": "я отличный водитель",
    "i have a very particular set of skills": "у меня очень специфический набор навыков",
    "who you gonna call": "кого вы будете вызывать",
    "dont get them wet": "не мочи их",
    "dont feed them after midnight": "не корми их после полуночи",
    "its showtime": "шоу начинается",
    "wax on wax off": "натирай вытирай",
    "dead or alive youre coming with me": "живым или мёртвым ты пойдёшь со мной",
    "choose life": "выбирай жизнь",
    "i have to return some videotapes": "мне надо вернуть кассеты",
    "look closer": "присмотрись",
    "meet me in montauk": "встретимся в монтоке",
    "im just a girl standing in front of a boy asking him to love her": "я просто девушка которая стоит перед парнем и просит полюбить её",
    "to me you are perfect": "для меня ты идеальна",
    "florals for spring groundbreaking": "цветочный принт весной революция",
    "what like its hard": "что это сложно",
    "i burn i pine i perish": "пылай томись погибай",
    "the power of christ compels you": "сила христа повелевает тобой",
    "theyre here": "они здесь",
    "ditto": "и я тебя",
    "whatever you do dont fall asleep": "что бы ты ни делал не засыпай",
    "was it the boogeyman": "это был бугимен",
    "a boys best friend is his mother": "лучший друг мальчика его мать",
    "open the pod bay doors hal": "открой шлюз отсека хол",
    "im sorry dave im afraid i cant do that": "прости дэйв боюсь я не могу этого сделать",
    "i love the smell of napalm in the morning": "я люблю запах напалма поутру",
    "this is my rifle this is my gun": "это моя винтовка это моё ружьё",
    "earn this": "заслужи это",
    "they may take our lives but theyll never take our freedom": "они могут отнять наши жизни но никогда не отнимут нашу свободу",
    "i drink your milkshake": "я выпью твой молочный коктейль",
    "whats the most you ever lost on a coin toss": "сколько максимум ты проигрывал на броске монеты",
    "the dude abides": "чувак пребывает",
    "this aggression will not stand man": "эта агрессия не пройдёт чувак",
    "dont let yourself get attached to anything you are not willing to walk out on in 30 seconds": "не привязывайся ни к чему от чего не готов отказаться за 30 секунд",
    "im the guy who does his job you must be the other guy": "я тот кто делает работу значит ты другой",
    "i feel the need the need for speed": "мне нужна скорость",
    "big mistake huge": "большая ошибка огромная",
    "a martini shaken not stirred": "мартини взболтать но не смешивать",
    "shaken not stirred": "взболтать но не смешивать",
    "no mr bond i expect you to die": "нет мистер бонд я рассчитываю что вы умрёте",
    "bond james bond": "бонд джеймс бонд",
    "do i look like i give a damn": "разве я похож на того кому не всё равно",
    "take the bloody shot": "стреляй уже",
    "pop quiz hotshot": "контрольная умник",
    "alrighty then": "ну тогда ладно",
    "so youre telling me theres a chance": "так ты хочешь сказать что есть шанс",
    "ssssmokin": "дымится",
    "somebody stop me": "кто нибудь остановите меня",
    "we lost doug": "мы потеряли дага",
    "what happens in vegas": "что происходит в вегасе",
    "you called me mclovin": "ты назвал меня маклавин",
    "im kind of a big deal": "я в некотором роде важная шишка",
    "stay classy san diego": "оставайтесь стильными сан диего",
    "did we just become best friends": "мы что только что стали лучшими друзьями",
    "i got you babe": "я поймал тебя детка",
    "good morning and in case i dont see you good afternoon good evening and good night": "доброе утро и если не увидимся добрый день добрый вечер и спокойной ночи",
    "may the odds be ever in your favor": "пусть удача всегда будет на вашей стороне",
    "and so the lion fell in love with the lamb": "и тогда лев влюбился в ягнёнка",
    "please look after this bear": "пожалуйста присмотрите за этим медведем",
    "if were kind and polite the world will be right": "если мы добры и вежливы мир будет в порядке",
    "this is sparta": "это спарта",
    "tonight we dine in hell": "сегодня мы пируем в аду",
    "are you watching closely": "вы внимательно смотрите",
    "we live in a twilight world": "мы живём в сумеречном мире",
    "dont try to understand it feel it": "не пытайся понять почувствуй",
    "i was perfect": "я была идеальна",
    "live die repeat": "живи умри повтори",
    "everybody runs": "все бегут",
    "they called me mr glass": "они звали меня мистер стекло",
    "wouldst thou like to live deliciously": "не хочешь ли ты жить в сладости",
    "talk to me": "говори со мной",
    "its us": "это мы",
    "i dont think so": "я так не думаю",
    "who is paimon": "кто такой паймон",
    "ba ba dook dook dook": "ба ба дук дук дук",
    "youll eat what we serve you": "вы будете есть то что мы подадим",
    "i am steve": "я стив",
    "chicken jockey": "куриный жокей",
    "have you ever dreamt of a better version of yourself": "ты когда нибудь мечтал о лучшей версии себя",
    "certainty is the great enemy of unity": "уверенность главный враг единства",
    "the truth is out there": "истина где то рядом",
    "i want to believe": "я хочу верить",
    "the owls are not what they seem": "совы не то чем кажутся",
    "damn fine coffee": "чёртовски хороший кофе",
    "i aim to misbehave": "я намерен нарушать",
    "so say we all": "так говорим мы все",
    "see you space cowboy": "увидимся космический ковбой",
    "i m the last airbender": "я последний маг воздуха",
    "im the last airbender": "я последний маг воздуха",
    "a heart is a heavy burden": "сердце тяжёлая ноша",
    "see with eyes unclouded": "смотри незамутнёнными глазами",
    "the net is vast and infinite": "сеть огромна и бесконечна",
    "think mark think": "думай марк думай",
    "oh my god they killed kenny": "боже мой они убили кенни",
    "thats too much man": "это слишком мужик",
    "be curious not judgemental": "будь любопытным не осуждай",
    "football is life": "футбол это жизнь",
    "the work is mysterious and important": "работа таинственна и важна",
    "dear gentle reader": "дорогой любезный читатель",
    "war never changes": "война никогда не меняется",
    "i am dream of the endless": "я сон бесконечных",
    "if you fail they will be slaughtered": "если не успеешь их перебьют",
    "dont shoot we have a message": "не стреляйте у нас сообщение",
    "you is kind you is smart you is important": "ты добрая ты умная ты важная",
    "if youre a bird im a bird": "если ты птица то и я птица",
    "you have bewitched me body and soul": "ты околдовала меня телом и душой",
    "this is me": "это я",
    "speed i am speed": "скорость я скорость",
    "silenzio bruno": "тишина бруно",
    "no capes": "никаких плащей",
    "we dont talk about bruno": "мы не говорим про бруно",
    "its a me mario": "это я марио",
    "youre too slow": "ты слишком медленный",
    "if we burn you burn with us": "если мы сгорим сгорите и вы",
    "i have a hulk": "у нас есть халк",
    "he may have been your father boy but he wasnt your daddy": "он мог быть твоим отцом но он не был твоим папой",
    "i love you guys": "я люблю вас ребята",
    "just because someone stumbles and loses their path": "если человек оступился и сбился с пути",
    "choice is an illusion": "выбор это иллюзия",
    "everything that has a beginning has an end": "у всего что имеет начало есть конец",
    "i live my life a quarter mile at a time": "я живу жизнь четверть мили за раз",
    "i dont have friends i got family": "у меня нет друзей у меня семья",
    "this tape will self destruct": "эта плёнка самоуничтожится",
    "he chose poorly": "он выбрал плохо",
    "the park is open": "парк открыт",
    "let them fight": "пусть дерутся",
    "ape not kill ape": "обезьяна не убивает обезьяну",
    "big things have small beginnings": "большое начинается с малого",
    "they drew first blood": "они пролили первую кровь",
    "how can the same shit happen to the same guy twice": "как одно и то же может случиться с одним человеком дважды",
    "every good thing in this world started with a dream": "всё хорошее в этом мире начиналось с мечты",
    "so long partner": "прощай партнёр",
    "we scare because we care": "мы пугаем потому что нам не всё равно",
    "try everything": "пробуй всё",
    "im bad and thats good": "я плохой и это хорошо",
    "i have magic hair that glows when i sing": "у меня волшебные волосы они светятся когда я пою",
    "supercalifragilisticexpialidocious": "суперкалифраджилистикэкспиалидошес",
    "these are a few of my favorite things": "вот лишь малая часть моих любимых вещей",
    "when youre a jet": "когда ты джет",
    "to love another person is to see the face of god": "любить другого человека значит видеть лицо бога",
    "its the same knife": "это тот же нож",
    "i dont want to survive i want to live": "я не хочу выживать я хочу жить",
    "explain this to me like im a four year old": "объясни мне это как четырёхлетнему",
    "the worlds full of lonely people": "мир полон одиноких людей",
    "youre not a nazi jojo youre ten": "ты не нацист джоджо тебе десять",
    "i play the piano": "я играю на пианино",
    "i work at nasa": "я работаю в наса",
    "you never really understand a person until you consider things from his point of view": "ты никогда по настоящему не поймёшь человека пока не посмотришь на вещи его глазами",
    "in the jungle you must wait": "в джунглях надо ждать",
    "welcome to the jungle": "добро пожаловать в джунгли",
    "im going to steal the declaration of independence": "я украду декларацию независимости",
    "we are the music makers and we are the dreamers of dreams": "мы творцы музыки и мечтатели",
    "so i have to be extra clever": "значит мне нужно быть особенно умной",
    "if they ever tell my story": "если когда нибудь расскажут мою историю",
    "why should i trade one tyrant three thousand miles away": "зачем мне менять одного тирана за три тысячи миль",
    "28 days 6 hours 42 minutes 12 seconds": "28 дней 6 часов 42 минуты 12 секунд",
    "the closer you look the less you see": "чем ближе смотришь тем меньше видишь",
    "hello im johnny cash": "здравствуйте я джонни кэш",
    "and all that jazz": "и весь этот джаз",
    "youre my best friend": "ты мой лучший друг",
    "my name is harvey milk and im here to recruit you": "меня зовут харви милк и я здесь чтобы завербовать вас",
    "were not supposed to be friends": "нам нельзя дружить",
    "i am haunted by humans": "меня преследуют люди",
    "and so it goes with god": "так бывает и с богом",
    "wilson": "уилсон",
    "happiness only real when shared": "счастье реально только когда им делятся",
    "who is you": "кто ты такой",
    "call me by your name": "назови меня своим именем",
    "i want to live through something": "я хочу что то пережить",
    "i am the superhero of this story": "в этой истории супергерой я",
    "we are infinite": "мы бесконечны",
    "ok ok": "окей окей",
    "live boldly": "живи смело",
    "ps i love you": "п эс я люблю тебя",
    "this is a story of boy meets girl": "это история о том как мальчик встретил девочку",
    "how can it be happening here": "как это может происходить здесь",
    "who watches the watchmen": "кто наблюдает за хранителями",
    "its so fluffy": "такой пушистый",
    "inner peace": "внутренний покой",
    "thats my son": "это мой сын",
    "this is our home": "это наш дом",
    "live happily ever after": "жили долго и счастливо",
    "courage dear heart": "мужайся милое сердце",
    "people stay in the oasis because the oasis is the only place they want to be": "люди остаются в оазисе потому что только там они хотят быть",
    "dont have a good day have a great day": "не хорошего дня отличного дня",
    "i must go now prawns": "мне пора креветки",
    "my logic is undone": "моя логика разрушена",
    "theyre already here": "они уже здесь",
    "swing away": "бей",
    "the beast": "зверь",
    "there are superheroes": "супергерои существуют",
    "this is an empathetic community": "это сообщество сопереживания",
    "whyd ya spill yer beans": "зачем ты просыпал бобы",
    "im a star": "я звезда",
    "i will not die": "я не умру",
    "were live": "мы в эфире",
    "hail satan": "слава сатане",
    "he is coming": "он идёт",
    "its not real": "это не реально",
    "shes not well": "с ней не всё в порядке",
    "dont go in the basement": "не ходи в подвал",
    "nice to meet you": "приятно познакомиться",
    "who did it": "кто это сделал",
    "hide and seek": "прятки",
    "the play": "пьеса",
    "i am expendable": "я расходный",
    "i cant feel pain": "я не чувствую боли",
    "im not what you think": "я не то чем ты меня считаешь",
    "im anxiety": "я тревога",
    "welcome to the mcu pal": "добро пожаловать в киновселенную приятель",
    "good to see you again": "рад снова тебя видеть",
    "may thy knife chip and shatter": "да выщербится и сломается твой нож",
    "lisan al gaib": "лисаан аль гаиб",
    "fear is the mind killer": "страх убийца разума",
    "the spice must flow": "пряность должна течь",
    "not quite my tempo": "не совсем мой темп",
    "there are no two words in the english language more harmful than good job": "нет двух более вредных слов чем молодец",
    "i am the one who knocks": "я тот кто стучит",
    "dying for the right cause is the most human thing we can do": "умереть за правое дело самое человеческое что мы можем сделать",
    "youve never seen a miracle": "ты никогда не видел чуда",
    "like tears in rain": "как слёзы под дождём",
    "all those moments will be lost in time": "все эти мгновения исчезнут во времени",
    "time to die": "время умирать",
    "i wasnt high i was clear": "я был не под кайфом я был ясен",
    "nzt 48": "эн зет 48",
    "its all good man": "всё в порядке человек",
    "time is a flat circle": "время плоский круг",
    "what is the cost of lies": "какова цена лжи",
    "all the pieces matter": "все детали важны",
    "toss a coin to your witcher": "брось монетку ведьмаку",
    "i prefer to be feared": "я предпочитаю чтобы меня боялись",
    "i am moana of motunui": "я моана с мотунуи",
    "youre welcome": "пожалуйста не за что",
    "witness me": "засвидетельствуй меня",
    "oh what a day what a lovely day": "ну и денёк чудесный денёк",
    "now i am become death the destroyer of worlds": "ныне я стал смертью разрушителем миров",
    "im just ken": "я просто кен",
    "heres to the ones who dream": "за тех кто мечтает",
    "get out": "убирайся",
    "im going to have to science the shit out of this": "придётся выкрутиться с помощью науки",
    "times are hard for dreamers": "мечтателям сейчас нелегко",
    "buongiorno principessa": "буонджорно принцесса",
    "laugh and the world laughs with you weep and you weep alone": "смейся и мир будет смеяться с тобой плачь и будешь плакать в одиночестве",
    "anyone can cook": "готовить может каждый",
    "i like the way you die boy": "мне нравится как ты умираешь парень",
    "the d is silent": "д не произносится",
    "au revoir shoshanna": "о ревуар шошанна",
    "are you gonna bark all day little doggy": "ты весь день лаять будешь маленький пёс",
    "wiggle your big toe": "пошевели большим пальцем ноги",
    "five point palm exploding heart technique": "техника пяти точек взрыва сердца",
    "people keep asking if im back": "люди всё спрашивают вернулся ли я",
    "yeah im thinking im back": "да я думаю я вернулся",
    "im just a dad": "я просто папа",
    "let off some steam bennett": "выпусти пар беннетт",
    "im too old for this": "я слишком стар для этого",
    "get your ass to mars": "тащи свою задницу на марс",
    "fuhgeddaboudit": "забудь об этом",
    "its what it is": "есть как есть",
    "when you have to shoot shoot dont talk": "когда надо стрелять стреляй не болтай",
    "deserves got nothing to do with it": "заслуги тут ни при чём",
    "when you love someone you gotta trust them": "когда любишь нужно доверять",
    "i know im human": "я знаю что я человек",
    "nobody trusts anybody now": "теперь никто никому не верит",
    "multipass": "мультипасс",
    "aziz light": "азиз свет",
    "you know the difference between you and me i make this look good": "знаешь в чём разница между нами у меня это выглядит круто",
    "i do some dumb things": "я делаю глупости",
    "are you happy": "ты счастлив",
    "higher further faster": "выше дальше быстрее",
    "and now i must warn you": "а теперь я должен тебя предупредить",
    "ill have both": "я возьму оба",
    "its not who i am underneath but what i do that defines me": "важно не кто я внутри а что я делаю",
    "you are my son": "ты мой сын",
    "its not about deserve its about what you believe": "дело не в том заслужил ли ты а в том во что ты веришь",
    "im going home": "я иду домой",
    "the next war will be mutant": "следующая война будет войной мутантов",
    "will you follow me one last time": "пойдёте за мной в последний раз",
    "it is the unknown we fear when we look upon death and darkness": "мы боимся неизвестного когда смотрим на смерть и тьму",
    "my philosophy is that worrying means you suffer twice": "моя философия беспокойство значит страдать дважды",
    "the needs of the many": "нужды большинства",
    "the needs of the many outweigh the needs of the few": "нужды многих важнее нужд немногих",
    "khan": "хан",
    "the secretary will disavow": "министр открестится",
    "the compass doesnt point north": "компас не указывает на север",
    "hoist the colours": "поднять цвета",
    "youve been in my life so long i cant remember anything else": "ты так давно в моей жизни что я ничего другого не помню",
    "serve in heaven or reign in hell": "служить на небесах или править в аду",
    "im back": "я вернулся",
    "one step at a time one punch at a time": "шаг за шагом удар за ударом",
    "if i can change and you can change everybody can change": "если я могу измениться и ты можешь измениться каждый может измениться",
    "defying gravity": "бросая вызов гравитации",
    "we know the way": "мы знаем путь",
    "i m a warrior": "я воин",
    "im a warrior": "я воин",
    "elements dont mix": "стихии не смешиваются",
    "this is going to be a piece of cake": "это будет проще простого",
    "i want to be a pirate": "я хочу быть пиратом",
    "it is better to be the right hand of the devil than in his path": "лучше быть правой рукой дьявола чем стоять у него на пути",
    "i belong with my warrior friends": "мне место с моими братьями воинами",
    "a king may move a man": "король может двигать человека",
    "i think world war two just started": "кажется только что началась вторая мировая",
    "i cant hear you": "я вас не слышу",
    "give em hell 54th": "задай им жару 54 й",
    "i got a lotta problems": "у меня куча проблем",
    "i want you to help me catch a killer of women": "я хочу чтобы ты помог мне поймать убийцу женщин",
    "we bury our sins here dave we wash them clean": "мы хороним грехи здесь дэйв мы смываем их",
    "who am i": "кто я",
    "everything you have seen is an illusion": "всё что ты видел иллюзия",
    "the following is my explanation": "далее моё объяснение",
    "you and i share a secret": "у нас с тобой общий секрет",
    "i got a woman": "у меня есть женщина",
    "i want love": "я хочу любовь",
    "lights up on washington heights": "свет над вашингтон хайтс",
    "silence": "тишина",
    "its the sense of touch": "это чувство прикосновения",
    "we are all connected": "мы все связаны",
    "youre never wrong to do the right thing": "правильно поступать никогда не ошибка",
    "i aint goin down": "я не сдамся",
    "dont lose it": "не теряй это",
    "no rope": "без верёвки",
    "the mountain": "гора",
    "ok": "окей",
    "i m gonna win": "я выиграю",
    "im gonna win": "я выиграю",
    "i am the fifth": "я пятая",
    "what kind of american are you": "какой ты американец",
    "if you feel it chase it": "если чувствуешь гонись",
    "im a stuntman": "я каскадёр",
    "i have the world to eat": "мне есть весь мир",
    "did you kill your husband": "вы убили мужа",
    "i want to live how i want": "я хочу жить как хочу",
    "i find the world a bitter and complicated place": "я нахожу мир горьким и сложным местом",
    "you dream in a language i cant understand": "ты видишь сны на языке который я не понимаю",
    "can you find the wolves in this picture": "можешь найти волков на этой картине",
    "i m oz cobb": "я оз кобб",
    "im oz cobb": "я оз кобб",
    "were lost": "мы заблудились",
    "hollywood": "голливуд",
    "one take": "одним дублем",
    "remember the cant": "помните кент",
    "that was uncharted": "это было неизведанно",
    "indeed": "именно так",
    "this is a true story": "это правдивая история",
    "hello you": "привет ты",
    "number five": "номер пять",
    "the keys": "ключи",
    "the rings of power": "кольца власти",
    "the wheel weaves": "колесо ткёт",
    "psychohistory": "психоистория",
    "the silo": "сило",
    "the sisterhood": "сестринство",
    "the trial": "испытание",
    "jazz is not just music": "джаз это не просто музыка",
    "you didnt think i was going to eat you did you": "ты же не думал что я тебя съем",
    "im not fat its all this fur": "я не толстый это всё шерсть",
    "i was born in the dark": "я родился во тьме",
    "you called me mclovin": "ты назвал меня маклавин",
    "fetch": "фетч",
    "bueller bueller": "бьюллер бьюллер",
    "whatever": "как скажешь",
    "ni": "ни",
    "uh oh": "ой ой",
    "family": "семья",
    "drift": "дрифт",
    "is that a monkey": "это обезьяна",
    "i want to be with you": "я хочу быть с тобой",
    "dont look back": "не оглядывайся",
    "ill save you even if it kills me": "я спасу тебя даже ценой жизни",
    "a lesson without pain is meaningless": "урок без боли бессмыслен",
    "equivalent exchange": "равноценный обмен",
    "you should enjoy the little detours": "нужно наслаждаться маленькими крюками",
    "congratulations": "поздравляю",
    "i am no jedi": "я не джедай",
    "ragnar": "рагнар",
    "odin": "один",
    "plaza": "плаза",
    "jeffrey": "jeffrey",
    "clinic": "клиника",
    "dust": "пыль",
    "brisingr": "брисингр",
    "go to camp": "в лагерь",
    "london": "лондон",
    "arcade": "аркада",
    "are you an effective team": "вы эффективная команда",
    "we can save everyone": "мы можем спасти всех",
    "i am consciousness": "я сознание",
    "mommy": "мама",
    "the beach": "пляж",
    "the four horsemen": "четыре всадника",
    "the farm": "ферма",
    "the south": "юг",
    "anora": "анора",
    "it is not enough to be hungry": "голода недостаточно",
    "un hombre": "ун омбре",
    "i work for these guys": "я работаю на этих ребят",
    "no women no kids": "ни женщин ни детей",
    "plant": "растение",
    "mathilda": "матильда",
    "everyone has a choice": "у каждого есть выбор",
    "i like the way you die boy": "мне нравится как ты умираешь парень",
    "a royale with cheese": "роял с сыром",
    "remember remember the fifth of november": "помни помни пятое ноября",
    "whoever saves one life saves the world entire": "кто спасает одну жизнь спасает весь мир",
    "not quite my tempo": "не совсем мой темп",
    "heres to the ones who dream": "за тех кто мечтает",
    "get out": "убирайся",
    "i want you to get out": "я хочу чтобы ты убрался",
    "you know what kind of plan never fails": "знаешь какой план никогда не подводит",
    "you know what kind of plan never fails a no plan": "знаешь какой план никогда не подводит никакой",
    "in another life i would have really liked just doing laundry and taxes with you": "в другой жизни я бы с удовольствием стирал бельё и платил налоги с тобой",
    "now i am become death the destroyer of worlds": "ныне я стал смертью разрушителем миров",
    "im just ken": "я просто кен",
    "i was cured all right": "меня вылечили да",
    "all those moments will be lost in time like tears in rain": "все эти мгновения потеряются во времени как слёзы в дожде",
    "dying for the right cause is the most human thing we can do": "умереть за правое дело самое человеческое что мы можем сделать",
    "witness me": "засвидетельствуй меня",
    "im going to have to science the shit out of this": "придётся выкрутиться наукой",
    "i hate space": "ненавижу космос",
    "dont you forget about me": "не забывай меня",
    "were all pretty bizarre some of us are just better at hiding it": "мы все довольно странные просто кто то лучше это скрывает",
    "stellaaaa": "стелла",
    "lets do the time warp again": "давайте снова станцуем тайм ворп",
    "hi im chucky wanna play": "привет я чаки хочешь поиграть",
    "whats your favorite scary movie": "какой твой любимый фильм ужасов",
    "youll float too": "ты тоже будешь плавать",
    "we all need mirrors to remind ourselves who we are": "всем нужны зеркала чтобы помнить кто мы",
    "laugh and the world laughs with you weep and you weep alone": "смейся и мир смеётся с тобой плачь и плачешь один",
    "once you do something you never forget": "сделав что то однажды уже не забудешь",
    "your name": "твоё имя",
    "they are not going to scheme against us": "они не будут строить против нас козни",
    "a sword by itself rules nothing": "меч сам по себе ничем не правит",
    "dont think feel": "не думай чувствуй",
    "you never got me down ray": "ты так и не сбил меня рэй",
    "i am moana of motunui": "я моана с мотунуи",
    "you aint never had a friend like me": "у тебя никогда не было такого друга как я",
    "be our guest": "будь нашим гостем",
    "anyone can cook": "готовить может каждый",
    "there is no secret ingredient": "секретного ингредиента нет",
    "everything we know about you guys is wrong": "всё что мы знали о вас неправда",
    "its all good man": "всё в порядке мужик",
    "those who want respect give respect": "кто хочет уважения тот уважает",
    "all the pieces matter": "все детали важны",
    "time is a flat circle": "время это плоский круг",
    "what is the cost of lies": "какова цена лжи",
    "fire and blood": "огонь и кровь",
    "the only man in the sky is you": "единственный человек в небе это ты",
    "wibbly wobbly timey wimey stuff": "вилли валли время штучки",
    "tonights the night": "сегодняшняя ночь",
    "these violent delights have violent ends": "жестокие утехи имеют жестокий конец",
    "the question is not if but when": "вопрос не если а когда",
    "toss a coin to your witcher": "кинь монетку своему ведьмаку",
    "i prefer to be feared": "я предпочитаю чтобы меня боялись",
    "doh": "доу",
    "cool cool cool cool cool": "круто круто круто круто круто",
    "treat yo self": "побалуй себя",
    "six seasons and a movie": "шесть сезонов и фильм",
    "i am aware of my duty": "я сознаю свой долг",
    "plata o plomo": "plata o plomo",
    "on the day of my judgment": "в день моего суда",
    "at least i tried": "по крайней мере я пытался",
    "too many notes": "слишком много нот",
    "you are the only thing that i see": "ты единственное что я вижу",
    "carpe diem": "лови день",
    "dont ever let somebody tell you you cant do something": "никогда не позволяй кому то говорить что ты не сможешь",
    "it is written": "так написано",
    "times are hard for dreamers": "мечтателям сейчас нелегко",
    "earth wind and fire": "земля ветер и огонь",
    "this is the zodiac speaking": "говорит зодиак",
    "cool girl": "крутая девчонка",
    "i suspect foul play": "подозреваю преступление",
    "yeah im thinking im back": "да я думаю я вернулся",
    "people keep asking if im back": "люди всё спрашивают вернулся ли я",
    "hello my name is inigo montoya": "меня зовут иниго монтойя",
    "its a four leaf clover you know why because its lucky": "это четырёхлистный клевер знаешь почему потому что он счастливый",
    "its been emotional": "это было эмоционально",
    "people only know what you tell them": "люди знают только то что ты им скажешь",
    "the yankees win because the yankees have you": "янки побеждают потому что у янки есть ты",
    "because the house always wins": "потому что казино всегда выигрывает",
    "hang on lads ive got a great idea": "погодите ребят у меня отличная идея",
    "your mission should you choose to accept it": "твоя миссия если согласишься её принять",
    "this is not a drill": "это не учение",
    "i am not complete": "я не цел",
    "hold me": "обними меня",
    "whats this": "что это",
    "be wise be brave be tricky": "будь мудрой будь храброй будь хитрой",
    "a long time ago in the underground realm": "давным давно в подземном царстве",
    "unable to perceive the shape of you": "не в силах постичь твой облик",
    "if you could see your whole life from start to finish would you change things": "если бы ты видел всю свою жизнь от начала до конца ты бы что то изменил",
    "fear is the mind killer": "страх убийца разума",
    "the spice must flow": "спайс должен течь",
    "may thy knife chip and shatter": "да сломается и затупится твой нож",
    "live long and prosper": "живи долго и процветай",
    "a martini shaken or stirred": "мартини взболтать или смешать",
    "where is this going": "куда это ведёт",
    "i have a voice": "у меня есть голос",
    "i am the president of the united states of america clothed in immense power": "я президент соединённых штатов облечённый огромной властью",
    "i will not fall into despair": "я не впаду в отчаяние",
    "au revoir shoshanna": "au revoir шошана",
    "are you gonna bark all day little doggy": "ты весь день лаять будешь щенок",
    "wiggle your big toe": "пошевели большим пальцем",
    "now thats some tasty burger": "вот это вкусный бургер",
    "noodles": "лапша",
    "when you have to shoot shoot dont talk": "когда надо стрелять стреляй не болтай",
    "deserves got nothing to do with it": "заслуги тут ни при чём",
    "thatll be the day": "вот тогда и посмотрим",
    "ive got to be the one": "это должен быть я",
    "who are those guys": "кто эти ребята",
    "lets go": "пошли",
    "call it": "называй",
    "i just dont understand it": "я просто не понимаю",
    "truth is like poetry and most people fucking hate poetry": "правда как поэзия и большинство поэзию ненавидит",
    "this is it this is the dream": "вот оно это мечта",
    "uh as if": "как бы не так",
    "you do what you gotta do": "делаешь что должен",
    "honest to blog": "честное блогово",
    "sometimes i think ive felt everything im ever gonna feel": "иногда мне кажется я уже всё почувствовал что мог",
    "to be human is to be fucked": "быть человеком значит быть обречённым",
    "who are we if we cant protect them": "кто мы если не можем их защитить",
    "hey wayne": "эй уэйн",
    "its not the house its their son": "дело не в доме а в их сыне",
    "im scared to close my eyes": "мне страшно закрывать глаза",
    "we are not infected": "мы не заражены",
    "you have to save her": "ты должен её спасти",
    "i want to remember": "я хочу помнить",
    "what did he look like": "как он выглядел",
    "i didnt kill him": "я его не убивал",
    "if it bleeds it leads": "если кровь то в эфир",
    "there are no two words in the english language more harmful than good job": "нет двух более вредных слов чем хорошо сыграно",
    "people this is why we cant have nice things": "люди вот почему у нас нет ничего хорошего",
    "as long as you can still grab a breath you fight": "пока можешь дышать ты сражаешься",
    "two days ago i saw a vehicle that would haul that tanker": "два дня назад я видел машину которая утянет этот танкер",
    "i know im human": "я знаю что я человек",
    "time to die": "пора умирать",
    "get your ass to mars": "тащись на марс",
    "let off some steam bennett": "выпусти пар беннетт",
    "welcome to the party pal": "добро пожаловать на вечеринку приятель",
    "im too old for this": "я слишком стар для этого",
    "welcome to the rock": "добро пожаловать на скалу",
    "define irony": "определи иронию",
    "i could eat a peach for hours": "я мог бы есть персик часами",
    "i dont even know who i am": "я даже не знаю кто я",
    "i can tell you the license plate numbers of all six cars outside": "я могу назвать номера всех шести машин снаружи",
    "i need a gun": "мне нужен пистолет",
    "im just a dad": "я просто папа",
    "im going to hurt you": "я причиню тебе боль",
    "when you love someone you gotta trust them": "когда любишь нужно доверять",
    "in the end we screwed it all up": "в итоге мы всё испортили",
    "fuggedaboutit": "забудь об этом",
    "here comes the pain": "вот и боль",
    "its what it is": "есть как есть",
    "easy ez": "спокойно изи",
    "aziz light": "азиз свет",
    "first rule of fight club": "первое правило бойцовского клуба",
    "dream within a dream": "сон внутри сна",
    "royal with cheese": "роял с сыром",
    "big kahuna burger": "биг кахуна бургер",
    "you get what you deserve": "ты получаешь то что заслужил",
    "you wouldnt get it": "ты не поймёшь",
    "put on a happy face": "сделай счастливое лицо",
    "either die a hero": "либо умрёшь героем",
    "live long enough to see yourself become the villain": "проживёшь достаточно долго чтобы стать злодеем",
    "live long enough": "проживёшь достаточно долго",
    "jordan belfort": "джордан белфорт",
    "im not leaving": "я не ухожу",
    "a million dollars isnt cool": "миллион это не круто",
    "you better lawyer up": "лучше найми адвоката",
    "scorpion jacket": "куртка со скорпионом",
    "do not go gentle": "не уходи смиренно",
    "love is the one thing": "любовь единственное",
    "father to a murdered son": "отец убитого сына",
    "which would be worse": "что хуже",
    "teddy daniels": "тедди дэниелс",
    "ill make him an offer he cant refuse": "я сделаю ему предложение от которого он не сможет отказаться",
    "im gonna make him an offer": "я сделаю ему предложение",
    "an offer he cant refuse": "предложение от которого он не сможет отказаться",
    "sleeps with the fishes": "спит с рыбами",
    "get busy living": "или живи",
    "or get busy dying": "или умри",
    "kevin mccallister": "кевин маккаллистер",
    "the cold never bothered me": "холод меня никогда не беспокоил",
    "bears beets battlestar galactica": "медведи свёкла звёздный крейсер галактика",
    "i declare bankruptcy": "я объявляю банкротство",
    "i wasnt high i was clear": "я не был под кайфом я был ясным",
    "is it just me or is it getting crazier out there": "мне кажется или вокруг всё безумнее",
    "some men arent looking for anything logical": "некоторые не ищут ничего логичного",
    "on the button": "на кнопку",
    "if you guys were the inventors of facebook youd have invented facebook": "если бы вы изобрели фейсбук вы бы изобрели фейсбук",
    "if you guys were the inventors": "если бы вы были изобретателями",
    "game over man": "гейм овер мужик",
    "help me obi wan kenobi": "помоги мне оби ван кеноби",
    "on the day of my judgment when i stand before god": "в день моего суда когда я предстану перед богом",
    "youve never seen a miracle": "ты никогда не видел чуда",
    "tears in rain": "слёзы в дожде",
    "like tears in rain": "как слёзы в дожде",
    "all those moments will be lost": "все эти мгновения потеряются",
    "into that good night": "в эту добрую ночь",
    "win the crowd": "завоюй толпу",
    "the night is dark": "ночь темна",
    "keep your friends close": "держи друзей близко",
    "theres only two types of men in this world": "в этом мире только два типа мужчин",
    "space monkeys": "космические обезьяны",
    "bring out the gimp": "выведи раба",
    "youre not your fucking khakis": "ты не свои чёртовы брюки",
    "nzt 48": "эн зет 48",
  };

  var keepLatin = {
    "hasta la vista baby": 1,
    "hakuna matata": 1,
    "valar morghulis": 1,
    "valar dohaeris": 1,
    "bazinga": 1,
    "wubba lubba dub dub": 1,
    "nzt 48": 1,
    "bella ciao": 1,
    "dattebayo": 1,
    "bankai": 1,
    "buongiorno principessa": 1,
    "silenzio bruno": 1,
    "lisan al gaib": 1,
    "brisingr": 1,
    "multipass": 1,
    "plata o plomo": 1,
    "aziz light": 1,
    "au revoir shoshanna": 1,
  };

  function isEnglish(q) {
    var k = key(q);
    if (keepLatin[k]) return false;
    var letters = q.replace(/[^a-zа-яё]/gi, "");
    if (letters.length < 4) return false;
    var lat = (letters.match(/[a-z]/gi) || []).length;
    return lat / letters.length >= 0.72;
  }

  function translate(q) {
    var k = key(q);
    if (dub[k]) return dub[k];
    return q;
  }

  function uniq(list) {
    var seen = {};
    var out = [];
    list.forEach(function (q) {
      var t = String(q || "").trim();
      if (!t) return;
      var k = key(t);
      if (!k || seen[k]) return;
      seen[k] = 1;
      out.push(t);
    });
    return out;
  }

  (window.POFRAZE_FILMS || []).forEach(function (film) {
    if (!film.quotes) film.quotes = [];
    var next = film.quotes.map(translate);
    var ru = next.filter(function (q) {
      return !isEnglish(q);
    });
    if (!ru.length) {
      ru = [film.title].concat(next);
      ru = ru.filter(function (q) {
        return !isEnglish(q);
      });
    }
    if (!ru.length) ru = [film.title];
    film.quotes = uniq(ru);
  });

  if (window.POFRAZE_CHIPS) {
    window.POFRAZE_CHIPS = uniq(window.POFRAZE_CHIPS.map(translate)).filter(function (q) {
      return !isEnglish(q);
    });
  }
})();
