(function () {
  function norm(s) {
    return String(s || "")
      .toLowerCase()
      .replace(/ё/g, "е")
      .replace(/^the\s+/, "")
      .replace(/[^a-zа-я0-9]+/g, " ")
      .replace(/\s+/g, " ")
      .trim();
  }

  var byId = {
    brother: [
      "в чём сила брат",
      "сила в правде",
      "я музыку слушал",
    ],
    "brother-2": [
      "вы кто такие давайте до свидания",
      "в чём сила брат",
    ],
    "operation-y": ["надо федя надо", "надо фёдор надо"],
    caucasian: [
      "студент который всегда готов",
      "жить хорошо а хорошо жить ещё лучше",
      "чей туфля",
      "ай да пушкин",
    ],
    "office-romance": [
      "я буду жаловаться",
      "статистика знает всё",
    ],
    "moscow-tears": ["москва слезам не верит"],
    "gentlemen-luck": ["птичку жалко", "теперь горбатый"],
    "diamond-arm": [
      "не виноватая я он сам пришёл",
      "чудны дела твои господи",
    ],
    "ivan-vasilievich": [
      "я требую продолжения банкета",
      "царь очень занят",
    ],
    meeting: ["вор должен сидеть в тюрьме"],
    "irony-fate": [
      "с лёгким паром",
      "какая гадость эта ваша заливная рыба",
    ],
    mimino: ["ларису ивановну хочу"],
    "white-sun": ["восток дело тонкое", "таможня даёт добро"],
    "dog-heart": ["разруха не в клозетах а в головах"],
    charodei: ["три белых коня"],
    "carnival-night": ["есть ли жизнь на марсе"],
    "kin-dza-dza": ["ку", "пепелац", "чаппала"],
    "twelve-chairs": ["лёд тронулся господа присяжные заседатели"],
    "guest-future": ["вы забыли поменять воду в аквариуме"],
    "word-of-boy": ["чушпан", "слово пацана"],
    "seventeen-moments": ["штирлиц задумался"],
    eeaaowait: ["may thy knife chip and shatter", "lisan al gaib"],
    groundhog: ["i got you babe"],
    hangover: ["we lost doug"],
    superbad: ["you called me mclovin"],
    "winter-soldier": ["on your left"],
    "thor-ragnarok": ["he's a friend from work"],
    "doctor-strange": ["i've come to bargain"],
    paddington: ["please look after this bear"],
    "hunger-games": ["may the odds be ever in your favor"],
    "v-vendetta": ["remember remember the fifth of november"],
    prestige: ["are you watching closely"],
    "x-files": ["the truth is out there", "i want to believe"],
    "twin-peaks": ["the owls are not what they seem", "damn fine coffee"],
    firefly: ["i aim to misbehave"],
    "cast-away": ["wilson"],
    "edge-tomorrow": ["live die repeat"],
    unbreakable: ["they called me mr glass"],
    "talk-to-me": ["talk to me"],
    "gladiator-2": ["strength and honor"],
  };

  var byTitle = {
    "godfather": [
      "i'm gonna make him an offer he can't refuse",
      "leave the gun take the cannoli",
    ],
    "godfather part ii": [
      "keep your friends close but your enemies closer",
    ],
    "casablanca": [
      "here's looking at you kid",
      "we'll always have paris",
      "of all the gin joints in all the towns in all the world she walks into mine",
      "play it sam",
    ],
    "gone with the wind": [
      "frankly my dear i don't give a damn",
      "after all tomorrow is another day",
    ],
    "wizard of oz": [
      "there's no place like home",
      "toto i've a feeling we're not in kansas anymore",
    ],
    "citizen kane": ["rosebud"],
    "psycho": ["a boy's best friend is his mother"],
    "2001 a space odyssey": [
      "open the pod bay doors hal",
      "i'm sorry dave i'm afraid i can't do that",
    ],
    "terminator": ["i'll be back"],
    "terminator 2": ["hasta la vista baby"],
    "terminator 2 judgment day": ["hasta la vista baby"],
    "star wars": [
      "may the force be with you",
      "that's no moon",
      "help me obi wan kenobi you're my only hope",
    ],
    "empire strikes back": ["no i am your father", "do or do not there is no try"],
    "the empire strikes back": ["no i am your father"],
    "matrix": ["there is no spoon", "follow the white rabbit"],
    "the matrix": ["there is no spoon"],
    "fight club": [
      "the first rule of fight club is you do not talk about fight club",
    ],
    "pulp fiction": [
      "english motherfucker do you speak it",
      "a royale with cheese",
    ],
    "forrest gump": [
      "life is like a box of chocolates",
      "run forrest run",
    ],
    "titanic": ["i'm the king of the world", "i'll never let go jack"],
    "jaws": ["you're gonna need a bigger boat"],
    "alien": ["in space no one can hear you scream"],
    "aliens": ["get away from her you bitch"],
    "rocky": ["yo adrian"],
    "taxi driver": ["you talkin to me"],
    "silence of the lambs": [
      "good evening clarice",
      "i ate his liver with some fava beans and a nice chianti",
    ],
    "the silence of the lambs": [
      "good evening clarice",
    ],
    "apocalypse now": ["i love the smell of napalm in the morning"],
    "full metal jacket": ["this is my rifle this is my gun"],
    "saving private ryan": ["earn this"],
    "schindler's list": ["whoever saves one life saves the world entire"],
    "braveheart": ["they may take our lives but they'll never take our freedom"],
    "gladiator": [
      "are you not entertained",
      "what we do in life echoes in eternity",
    ],
    "lord of the rings": ["you shall not pass", "my precious"],
    "the lord of the rings the fellowship of the ring": ["you shall not pass"],
    "harry potter and the philosopher's stone": ["yer a wizard harry"],
    "harry potter and the sorcerer's stone": ["yer a wizard harry"],
    "back to the future": [
      "roads where we're going we don't need roads",
      "great scott",
    ],
    "home alone": ["keep the change ya filthy animal"],
    "die hard": ["yippee ki yay"],
    "the shining": ["here's johnny", "all work and no play makes jack a dull boy"],
    "et": ["et phone home"],
    "e t": ["et phone home"],
    "e t the extra terrestrial": ["et phone home"],
    "jurassic park": ["life finds a way", "hold onto your butts"],
    "raiders of the lost ark": ["why did it have to be snakes"],
    "indiana jones and the raiders of the lost ark": ["it belongs in a museum"],
    "goodfellas": ["as far back as i can remember i always wanted to be a gangster"],
    "scarface": ["say hello to my little friend"],
    "the dark knight": ["why so serious"],
    "inception": ["you mustn't be afraid to dream a little bigger darling"],
    "interstellar": ["do not go gentle into that good night"],
    "whiplash": ["not quite my tempo"],
    "la la land": ["here's to the ones who dream"],
    "get out": ["get out"],
    "parasite": ["you know what kind of plan never fails"],
    "everything everywhere all at once": [
      "in another life i would have really liked just doing laundry and taxes with you",
    ],
    "oppenheimer": ["now i am become death the destroyer of worlds"],
    "barbie": ["i'm just ken"],
    "iron man": ["i am iron man"],
    "avengers endgame": [
      "avengers assemble",
      "i love you 3000",
      "i am iron man",
    ],
    "spider man no way home": ["with great power comes great responsibility"],
    "black panther": ["wakanda forever"],
    "guardians of the galaxy": ["i am groot"],
    "the wolf of wall street": ["sell me this pen"],
    "the social network": [
      "a million dollars isn't cool you know what's cool a billion dollars",
    ],
    "joker": ["you get what you fucking deserve"],
    "the departed": ["i'm the guy who does his job you must be the other guy"],
    "no country for old men": ["what's the most you ever lost on a coin toss"],
    "there will be blood": ["i drink your milkshake"],
    "the big lebowski": ["the dude abides"],
    "heat": [
      "don't let yourself get attached to anything you are not willing to walk out on in 30 seconds",
    ],
    "se7en": ["what's in the box"],
    "seven": ["what's in the box"],
    "the usual suspects": [
      "the greatest trick the devil ever pulled was convincing the world he didn't exist",
    ],
    "a clockwork orange": ["i was cured all right"],
    "blade runner": ["all those moments will be lost in time like tears in rain"],
    "blade runner 2049": [
      "dying for the right cause is the most human thing we can do",
    ],
    "mad max fury road": ["witness me"],
    "the martian": ["i'm going to have to science the shit out of this"],
    "gravity": ["i hate space"],
    "top gun": ["i feel the need the need for speed"],
    "jerry maguire": ["show me the money", "you had me at hello"],
    "a few good men": ["you can't handle the truth"],
    "apollo 13": ["houston we've had a problem"],
    "goldfinger": ["a martini shaken not stirred", "no mr bond i expect you to die"],
    "pretty woman": ["big mistake huge"],
    "ghost": ["ditto"],
    "dirty dancing": ["nobody puts baby in a corner"],
    "mean girls": ["on wednesdays we wear pink", "you can't sit with us"],
    "the breakfast club": [
      "don't you forget about me",
      "we're all pretty bizarre some of us are just better at hiding it",
    ],
    "ferris bueller's day off": ["life moves pretty fast"],
    "clueless": ["as if"],
    "when harry met sally": ["i'll have what she's having"],
    "some like it hot": ["well nobody's perfect"],
    "sunset boulevard": ["i am big it's the pictures that got small"],
    "network": ["i'm as mad as hell and i'm not going to take this anymore"],
    "taxi driver": ["you talkin to me"],
    "wall street": ["greed is good"],
    "a streetcar named desire": ["stellaaaa"],
    "dr strangelove": ["gentlemen you can't fight in here this is the war room"],
    "the graduate": ["plastics"],
    "midnight cowboy": ["i'm walkin here"],
    "rocky horror": ["let's do the time warp again"],
    "the exorcist": ["the power of christ compels you"],
    "halloween": ["was it the boogeyman"],
    "a nightmare on elm street": ["whatever you do don't fall asleep"],
    "poltergeist": ["they're here"],
    "child's play": ["hi i'm chucky wanna play"],
    "scream": ["what's your favorite scary movie"],
    "it": ["you'll float too"],
    "the sixth sense": ["i see dead people"],
    "the sixth sense": ["i see dead people"],
    "memento": ["we all need mirrors to remind ourselves who we are"],
    "oldboy": ["laugh and the world laughs with you weep and you weep alone"],
    "spirited away": ["once you do something you never forget"],
    "your name": ["your name"],
    "parasite": ["they are not going to scheme against us"],
    "crouching tiger hidden dragon": ["a sword by itself rules nothing"],
    "enter the dragon": ["don't think feel"],
    "the karate kid": ["wax on wax off"],
    "rocky iv": ["if i can change and you can change everybody can change"],
    "raging bull": ["you never got me down ray"],
    "on the waterfront": ["i coulda been a contender"],
    "the wizard of oz": ["there's no place like home"],
    "mary poppins": ["supercalifragilisticexpialidocious"],
    "the sound of music": ["these are a few of my favorite things"],
    "frozen": ["the cold never bothered me anyway"],
    "moana": ["i am moana of motunui"],
    "toy story": ["to infinity and beyond"],
    "finding nemo": ["just keep swimming"],
    "up": ["adventure is out there"],
    "coco": ["remember me"],
    "shrek": ["ogres are like onions"],
    "the lion king": ["hakuna matata", "remember who you are"],
    "aladdin": ["you ain't never had a friend like me"],
    "beauty and the beast": ["be our guest"],
    "frozen 2": ["into the unknown"],
    "encanto": ["we don't talk about bruno"],
    "ratatouille": ["anyone can cook"],
    "the incredibles": ["no capes"],
    "kung fu panda": ["there is no secret ingredient"],
    "how to train your dragon": ["everything we know about you guys is wrong"],
    "game of thrones": [
      "winter is coming",
      "you know nothing jon snow",
      "valar morghulis",
      "chaos is a ladder",
    ],
    "breaking bad": ["i am the one who knocks", "say my name"],
    "better call saul": ["it's all good man"],
    "the sopranos": ["those who want respect give respect"],
    "the wire": ["all the pieces matter"],
    "true detective": ["time is a flat circle"],
    "chernobyl": ["what is the cost of lies"],
    "the office": ["that's what she said"],
    "friends": ["we were on a break", "how you doin"],
    "how i met your mother": ["suit up", "it's gonna be legen wait for it dary"],
    "the big bang theory": ["bazinga"],
    "lost": ["we have to go back"],
    "stranger things": ["friends don't lie"],
    "the mandalorian": ["this is the way"],
    "andor": ["rebellions are built on hope"],
    "house of the dragon": ["fire and blood"],
    "the last of us": ["endure and survive"],
    "succession": ["you are not serious people"],
    "the bear": ["yes chef"],
    "the boys": ["the only man in the sky is you"],
    "peaky blinders": ["by order of the peaky blinders"],
    "sherlock": ["the game is on"],
    "doctor who": ["wibbly wobbly timey wimey stuff"],
    "house": ["everybody lies"],
    "dexter": ["tonight's the night"],
    "westworld": ["these violent delights have violent ends"],
    "dark": ["the question is not if but when"],
    "dark": ["the question is not if but when"],
    "squid game": ["red light green light"],
    "the witcher": ["toss a coin to your witcher"],
    "wednesday": ["i prefer to be feared"],
    "rick and morty": ["wubba lubba dub dub", "i'm pickle rick"],
    "the simpsons": ["d'oh"],
    "brooklyn nine nine": ["cool cool cool cool cool"],
    "parks and recreation": ["treat yo self"],
    "community": ["six seasons and a movie"],
    "severance": ["the work is mysterious and important"],
    "fallout": ["war never changes"],
    "the crown": ["i am aware of my duty"],
    "narcos": ["plata o plomo"],
    "money heist": ["bella ciao"],
    "la casa de papel": ["bella ciao"],
    "dark knight": ["why so serious"],
    "the green mile": ["on the day of my judgment"],
    "the shawshank redemption": [
      "get busy living or get busy dying",
      "hope is a good thing maybe the best of things",
    ],
    "one flew over the cuckoo's nest": ["at least i tried"],
    "amadeus": ["too many notes"],
    "rain man": ["i'm an excellent driver"],
    "a beautiful mind": ["you are the only thing that i see"],
    "dead poets society": ["o captain my captain", "carpe diem"],
    "good will hunting": ["how do you like them apples"],
    "the pursuit of happyness": ["don't ever let somebody tell you you can't do something"],
    "slumdog millionaire": ["it is written"],
    "life is beautiful": ["buongiorno principessa"],
    "amelie": ["times are hard for dreamers"],
    "the intouchables": ["earth wind and fire"],
    "intouchables": ["earth wind and fire"],
    "leon": ["is life always this hard or is it just when you're a kid"],
    "leon the professional": ["i like milk"],
    "the professional": ["i like milk"],
    "se7en": ["what's in the box"],
    "zodiac": ["this is the zodiac speaking"],
    "gone girl": ["cool girl"],
    "knives out": ["i suspect foul play"],
    "john wick": ["yeah i'm thinking i'm back"],
    "john wick chapter 4": ["people keep asking if i'm back"],
    "the notebook": ["if you're a bird i'm a bird"],
    "pride and prejudice": ["you have bewitched me body and soul"],
    "notting hill": ["i'm just a girl standing in front of a boy asking him to love her"],
    "love actually": ["to me you are perfect"],
    "the princess bride": ["as you wish", "inconceivable", "hello my name is inigo montoya"],
    "monty python and the holy grail": ["it's just a flesh wound"],
    "life of brian": ["he's not the messiah he's a very naughty boy"],
    "snatch": ["it's a four leaf clover you know why because it's lucky"],
    "lock stock and two smoking barrels": ["it's been emotional"],
    "trainspotting": ["choose life"],
    "requiem for a dream": ["i got a lotta problems"],
    "american beauty": ["look closer"],
    "american psycho": ["i have to return some videotapes"],
    "the wolf of wall street": ["sell me this pen"],
    "catch me if you can": ["people only know what you tell them"],
    "catch me if you can": ["the yankees win because the yankees have you"],
    "ocean's eleven": ["because the house always wins"],
    "the italian job": ["hang on lads i've got a great idea"],
    "mission impossible": ["your mission should you choose to accept it"],
    "mission impossible fallout": ["this is not a drill"],
    "indiana jones and the last crusade": ["he chose poorly"],
    "the fifth element": ["multipass", "aziz light"],
    "men in black": ["you know the difference between you and me i make this look good"],
    "ghostbusters": ["who you gonna call"],
    "gremlins": ["don't get them wet"],
    "beetlejuice": ["it's showtime"],
    "edward scissorhands": ["i am not complete"],
    "edward scissorhands": ["hold me"],
    "the nightmare before christmas": ["what's this"],
    "coraline": ["be wise be brave be tricky"],
    "pan's labyrinth": ["a long time ago in the underground realm"],
    "the shape of water": ["unable to perceive the shape of you"],
    "arrival": ["if you could see your whole life from start to finish would you change things"],
    "dune": ["fear is the mind killer", "the spice must flow"],
    "dune part two": ["may thy knife chip and shatter"],
    "star trek": ["live long and prosper"],
    "star trek ii the wrath of khan": ["khan"],
    "the empire strikes back": ["no i am your father"],
    "return of the jedi": ["i am a jedi like my father before me"],
    "the force awakens": ["chewie we're home"],
    "rogue one": ["rebellions are built on hope"],
    "a new hope": ["that's no moon"],
    "dr no": ["bond james bond"],
    "casino royale": ["a martini shaken or stirred"],
    "skyfall": ["where is this going"],
    "the king's speech": ["i have a voice"],
    "lincoln": ["i am the president of the united states of america clothed in immense power"],
    "12 years a slave": ["i don't want to survive i want to live"],
    "12 years a slave": ["i will not fall into despair"],
    "django unchained": ["i like the way you die boy"],
    "inglourious basterds": ["au revoir shoshanna"],
    "reservoir dogs": ["are you gonna bark all day little doggy"],
    "kill bill": ["wiggle your big toe"],
    "kill bill volume 1": ["wiggle your big toe"],
    "once upon a time in hollywood": ["now that's some tasty burger"],
    "once upon a time in america": ["noodles"],
    "the good the bad and the ugly": ["when you have to shoot shoot don't talk"],
    "unforgiven": ["deserve's got nothing to do with it"],
    "the searchers": ["that'll be the day"],
    "high noon": ["i've got to be the one"],
    "butch cassidy and the sundance kid": ["who are those guys"],
    "the wild bunch": ["let's go"],
    "no country for old men": ["call it"],
    "fargo": ["i just don't understand it"],
    "the big short": ["truth is like poetry and most people fucking hate poetry"],
    "margin call": ["this is it this is the dream"],
    "the intern": ["you're never wrong to do the right thing"],
    "the devil wears prada": ["florals for spring groundbreaking"],
    "legally blonde": ["what like it's hard"],
    "10 things i hate about you": ["i burn i pine i perish"],
    "clueless": ["uh as if"],
    "easy a": ["i am the superhero of this story"],
    "lady bird": ["i want to live through something"],
    "little miss sunshine": ["you do what you gotta do"],
    "juno": ["honest to blog"],
    "eternal sunshine of the spotless mind": ["meet me in montauk"],
    "her": ["sometimes i think i've felt everything i'm ever gonna feel"],
    "ex machina": ["to be human is to be fucked"],
    "hereditary": ["who is paimon"],
    "midsommar": ["this is an empathetic community"],
    "the witch": ["wouldst thou like to live deliciously"],
    "get out": ["i want you to get out"],
    "us": ["it's us"],
    "nope": ["i don't think so"],
    "a quiet place": ["who are we if we can't protect them"],
    "the conjuring": ["hey wayne"],
    "insidious": ["it's not the house it's their son"],
    "the bungie": ["they're here"],
    "poltergeist": ["they're here"],
    "the blair witch project": ["i'm scared to close my eyes"],
    "rec": ["we are not infected"],
    "train to busan": ["you have to save her"],
    "parasite": ["you know what kind of plan never fails a no plan"],
    "oldboy": ["i want to remember"],
    "memories of murder": ["what did he look like"],
    "decision to leave": ["i didn't kill him"],
    "drive": ["i drive"],
    "nightcrawler": ["if it bleeds it leads"],
    "whiplash": ["there are no two words in the english language more harmful than good job"],
    "birdman": ["people this is why we can't have nice things"],
    "the revenant": ["as long as you can still grab a breath you fight"],
    "mad max 2": ["two days ago i saw a vehicle that would haul that tanker"],
    "the thing": ["i know i'm human"],
    "alien romulus": ["in space no one can hear you scream"],
    "prometheus": ["big things have small beginnings"],
    "blade runner": ["time to die"],
    "total recall": ["get your ass to mars"],
    "robocop": ["dead or alive you're coming with me"],
    "the terminator": ["i'll be back"],
    "predator": ["if it bleeds we can kill it", "get to the chopper"],
    "commando": ["let off some steam bennett"],
    "die hard": ["welcome to the party pal"],
    "lethal weapon": ["i'm too old for this"],
    "speed": ["pop quiz hotshot"],
    "the rock": ["welcome to the rock"],
    "con air": ["define irony"],
    "face off": ["i could eat a peach for hours"],
    "mission impossible": ["this tape will self destruct"],
    "bourne identity": ["i don't even know who i am"],
    "the bourne identity": ["i can tell you the license plate numbers of all six cars outside"],
    "taken": ["i have a very particular set of skills"],
    "john wick": ["i need a gun"],
    "nobody": ["i'm just a dad"],
    "the equalizer": ["i'm going to hurt you"],
    "casino": ["when you love someone you gotta trust them"],
    "casino": ["in the end we screwed it all up"],
    "goodfellas": ["funny how"],
    "donnie brasco": ["fuggedaboutit"],
    "carlito's way": ["here comes the pain"],
    "scarface": ["the world is yours"],
    "the irishman": ["it's what it is"],
    "once upon a time in hollywood": ["easy ez"],
  };

  function addAll(film, list) {
    if (!list || !film.quotes) return;
    var i;
    for (i = 0; i < list.length; i += 1) {
      var t = String(list[i] || "").trim();
      if (t.length < 3) continue;
      if (film.quotes.indexOf(t) === -1) film.quotes.push(t);
    }
  }

  (window.POFRAZE_FILMS || []).forEach(function (film) {
    addAll(film, byId[film.id]);
    var keys = [norm(film.originalTitle), norm(film.title)];
    var k;
    for (k = 0; k < keys.length; k += 1) {
      if (keys[k] && byTitle[keys[k]]) addAll(film, byTitle[keys[k]]);
    }
  });
})();
